### ISSUE TITLE
PhoneNumberTextField edit formatting error

### ISSUE THREAD

**Issue by shawnwall** [marmelroy/PhoneNumberKit#101]
If I create a `PhoneNumberTextField` and edit the text and type:

`4125555555`

everything works as expected and the number becomes:

`(412) 555-5555`

If I then hit the backspace key in the keyboard backing up to:

`(412) 555`

...then type:

`5555`

...the text field displays: 

`(412) 5555555`

expectation:

`(412) 555-5555`

**Comment by jazzgil** [comment]
I've noticed that this happens because of the parenthesis. If you manually remove the parens, formatting returns.

**Comment by marmelroy** [comment]
Fix merged.

**Comment by templeman15** [comment]
This also occurs when using `PartialFormatter().formatPartial()` directly. Is there any specific reason why or should it be fixed in the PartialFormatter and not in the `TextField`?
