### ISSUE TITLE
Editable struct

### ISSUE THREAD

**Issue by davbeck** [marmelroy/PhoneNumberKit#111]
Is there a particular reason that PhoneNumber's properties are all immutable? My backend API returns phone numbers with the extensions separately. It would be really nice to parse the main phone number from the API, then set the extension on the returned model.

**Comment by marmelroy** [comment]
Thanks for this @davbeck. PhoneNumber objects are immutable struct by defaults to allow for better thread safety and speed. There is no plan to change that currently.
