### ISSUE TITLE
Extension with semicolon not recognized

### ISSUE THREAD

**Issue by appsforall** [marmelroy/PhoneNumberKit#113]
We run into a lot of phone numbers that use a semicolon as extension separator.
Examples:
(586) 485-7783;55
303-977-1001;127

However these are not recognised by PhoneNumberKit as valid phone numbers. I suggest to change the regex patterns to also allow these kind of extension formatting by replacing the part "[,xｘX#＃~～]" by "[,xｘX#＃~～;]"

**Comment by marmelroy** [comment]
Thanks @appsforall. I like this suggestion and would like to encourage you to make a PR with this update (the more contributors the merrier).

**Comment by appsforall** [comment]
Of course. Not sure how you manage collaboration, but looking at existing PR's this seems the way to go. https://github.com/marmelroy/PhoneNumberKit/pull/114

**Comment by appsforall** [comment]
@marmelroy See above comment + my PR. Any chance you can review the PR and give feedback? Thanks!

**Comment by marmelroy** [comment]
Merged.
