### ISSUE TITLE
Mobile number is invalid

### ISSUE THREAD

**Issue by javiyavandan** [marmelroy/PhoneNumberKit#116]
Hello , 
I am using your library for my project . Here is my sample number which are valid but when i try to validate it using Phonenumberkit it gives error .

e.g +918160355434,+918323467899 
Please help me to solve this .

if you need anything from my side please let me know .

**Comment by kuyazee** [comment]
Same problem I'm getting here. This is a valid Indonesian number 87723232065 but it says that the mobile number is invalid. I'm using the Swift 2.3 Branch

**Comment by marmelroy** [comment]
Hi @javiyavandan,

PhoneNumberKit is validating the number from a given region code. On the phone this defaults to the phone's SIM's country. In the simulator it defaults to the US. You can override the region code with a given country code (i.e IN). 

"+918160355434" is not a valid number when called from the US, hence why it gives an error.

However, on an Indian device, or when overriding the default, it returns a valid number:
phoneNumberKit.parse("918160355434", withRegion: "IN")

**Comment by Nahatakyan** [comment]
@kuyazee Your problem fixed?
