### ISSUE TITLE
Feature Request: Max Chars for PhoneNumberTextField

### ISSUE THREAD

**Issue by jtezanos** [marmelroy/PhoneNumberKit#118]
I know this issue was brought up at #58 - but there is validity to what was brought up. Each country has a specific count on their numbers, so exact character count should apply to each country individually. If we really think about it, this actually should have been one of the first features built in for PhoneNumberTextField as it makes using PhoneNumberTextField useless until you build in this functionality for your own project.

**Comment by irace** [comment]
Agreed – I’m finding myself not using `TextField`, and instead using `PartialFormatter` directly with a hardcoded max. length value that I’m also checking. Would be great if you could configure `PartialFormatter` with a “length checking mode” (e.g. for those of us who don’t plan to support extensions).

**Comment by marmelroy** [comment]
Thanks @jtezanos. This will be considered for a future version.
