### ISSUE TITLE
Get countryCode

### ISSUE THREAD

**Issue by Chakery** [marmelroy/PhoneNumberKit#119]
Can I get countryCode based on phoneNumber?
E.g.
```
do {
    let phoneNumber = try PhoneNumber(rawNumber: "13788888888")
    let code = phoneNumber.countryCode // I hope display 86
} catch { }
```

**Comment by marmelroy** [comment]
Hi @Chakery, yes you can - as long as the raw number is valid from the current region (defaults to US on simulator and sim's local country on the phone).

**Comment by Chakery** [comment]
Sorry, it was my wrong expression that made you misunderstood.
I would like to obtain the corresponding country code according to the mobile phone number, but not directly get the country code for the location of the phone.
Thank you so much.

**Comment by dhipin** [comment]
> I would like to obtain the corresponding country code according to the mobile phone number, but not directly get the country code for the location of the phone.

Any updates on this yet. Seems the thread should be opened to get this solved.
