### ISSUE TITLE
Cocoapod install error

### ISSUE THREAD

**Issue by kpavankotesh** [marmelroy/PhoneNumberKit#12]
He,

I'm getting this error when attempting to install the pod. Not sure if there's a way around this – do you have any suggestions?

[!] The 'Pods' target has transitive dependencies that include static binaries:

I am using Xcode 7.2 Swift 2

**Comment by marmelroy** [comment]
Just tried to replicate with the same set-up and it's working fine. Can you share some code so we can better identify what the issue is (at least the Podfile)?

**Comment by kpavankotesh** [comment]
inhibit_all_warnings!

pod 'IQKeyboardManager'
pod 'RestKit', '0.24.1'
pod 'MagicalRecord'
pod '500px-iOS-api'
pod 'FDWaveformView'
pod 'SDWebImage', '~> 3.7'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Inflections'
pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
pod 'SKTagView'
pod 'UICollectionViewLeftAlignedLayout'
pod 'Analytics/Segmentio'
pod 'Analytics/Localytics'
pod 'UAProgressView'
pod 'HPGrowingTextView'

**Comment by marmelroy** [comment]
Ah... I see... PhoneNumberKit is a Swift-only framework and to integrate with Cocoapods you will need to add the use_fraemworks flag. All of the pods you are using support framework targets except Localytics. You will need to remove it. 

This will install without any issues:
```use_frameworks!
inhibit_all_warnings!

pod 'PhoneNumberKit'
pod 'IQKeyboardManager'
pod 'RestKit', '0.24.1'
pod 'MagicalRecord'
pod '500px-iOS-api'
pod 'FDWaveformView'
pod 'SDWebImage', '~> 3.7'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Inflections'
pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
pod 'SKTagView'
pod 'UICollectionViewLeftAlignedLayout'
pod 'Analytics/Segmentio'
pod 'UAProgressView'
pod 'HPGrowingTextView'```
