### ISSUE TITLE
In v0.85, it looks like formatting doesn't work.

### ISSUE THREAD

**Issue by pradeepb28** [marmelroy/PhoneNumberKit#120]
let formattedPhoneNumber = phoneNumberKit.parseMultiple(["2223334444"]).first?.toNational()
or
let formattedPhoneNumber = phoneNumberKit.parseMultiple(["2223334444"], region: "US").first?.toNational()
or
let formattedPhoneNumber = phoneNumberKit.parseMultiple(["2223334444"], region: "US").first?.toInternational()
or 
let formattedPhoneNumber = phoneNumberKit.parseMultiple(["2223334444"], region: "US").first?.rawNumber

I have tried all those ways, they all work on simulator but not on device, even though it was tested on U.S sim provider.

**Comment by marmelroy** [comment]
Hi @pradeepb28,

The number you are testing with is not a valid number. Invalid numbers are not returned when you parse more than one string so you should always get nil. 

Also, you should use the newest version of PhoneNumberKit (lots of syntax changes).
