### ISSUE TITLE
Mobile number validation doesn't completely work

### ISSUE THREAD

**Issue by kuyazee** [marmelroy/PhoneNumberKit#121]
The default value for PH mobile numbers look like this `+639xxxxxxxxx` or `09xxxxxxxxx`, but the library validates `+6309xxxxxxxxx` as a correct number.

For ID too it doesn't validate the numbers correctly, it this time it won't accept correct values for the numbers

Here's my code
```
let raw = "Some Number Here"
do {
     let number = try PhoneNumber(rawNumber: raw)
     print(number.isValidNumber, number.rawNumber)
} catch {
     print("Phone number parsing error", error)
}
```

**Comment by marmelroy** [comment]
Hi @kuyazee,

PhoneNumberKit is using metadata from Google's libPhoneNumber project that powers most mobile phone number validation on the web and on mobile. 

They consider +6309xxxxxxxxxx as a correct format for PH. See: https://libphonenumber.appspot.com/phonenumberparser?number=%2B630918+899+2866&country=PH

**Comment by kuyazee** [comment]
@marmelroy actually it isn't cause I live in the Philippines and there is no such number that is +6309(10 digits) what you showed i.e. [this](https://libphonenumber.appspot.com/phonenumberparser?number=%2B630918+899+2866&country=PH) is +6309(9 digits) which is possible.

+6309(10 digits) Not valid 
+6309(9 digits) valid

**Comment by marmelroy** [comment]
I had one extra x in my reply.

This is the number I tested with:
+630918 899 2866 

Again, please see:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B630918+899+2866&country=PH

**Comment by bargangilo** [comment]
@marmelroy: I'm also having issues getting PhoneNumberKit to validate a mobile number from the Philippines as a valid number. No matter how I enter the number in I either get notANumber or unknownType errors.

**Comment by marmelroy** [comment]
hi @bargangilo, libPhoneNumber also says that this number is invalid. isValidNumberForRegion is **false** in the link you attached.

**Comment by bargangilo** [comment]
@marmelroy: Ok, if I add the zero in it also returns isValidNumberForRegion as false. I guess this is a libphonenumber issue then? Because I most definitely have a working number. 

Is PHK only looking at the isValidNumberForRegion? Is there any way to turn that off and only check isValidNumber and isPossibleNumber?

**Comment by marmelroy** [comment]
In the Swift 2.3 version there's no way to turn it off. In the Swift 3.0 version there is a way to ignore the type validation, which is close to Goolgle's isValidNumber.

**Comment by bargangilo** [comment]
But not the regional validation?

**Comment by bargangilo** [comment]
Also I've submitted an issue to libphonenumber: https://github.com/googlei18n/libphonenumber/issues/1710

**Comment by marmelroy** [comment]
the type validation is the same thing as the regional validation

**Comment by johnolwamba** [comment]
Is there an example number? I have looked it up and not found it. Its there in libphonenumber. Please assist
