### ISSUE TITLE
Expose some of `MetadataManager`

### ISSUE THREAD

**Issue by mxcl** [marmelroy/PhoneNumberKit#122]
I need a list of international prefixes, I see that this data is part of PhoneNumberKit but it is not accessible publicly.

Also: project-pulse-test: Mar-7th-2017

**Comment by mxcl** [comment]
My bad, the `PhoneNumberKit` class exposes this information.

**Comment by marmelroy** [comment]
Yup.

What's project-pulse-test?

**Comment by mxcl** [comment]
There's many dead projects on GitHub, glad this isn't one!

So far this has been a super useful project, many thanks for it.
