### ISSUE TITLE
Feature request: disabling PhoneNumberTextField formatting

### ISSUE THREAD

**Issue by ilandbt** [marmelroy/PhoneNumberKit#126]
Hey,
I'm using PhoneNumberTextField to get the users phone number but also to enter a verification code he gets in a SMS.

Is there a way to disable the formatting of the text?

Thanks

**Comment by marmelroy** [comment]
Hi @ilandbt,

Thanks for the suggestion. Currently, there isn't. This is something that will be considered for the next big release.

**Comment by eliburke** [comment]
Old issue.. but you can use phoneNumberTextField.isPartialFormatterEnabled = true / false to enable and disable number formatting when setting .text = "123"

**Comment by hungeric** [comment]
I would second this feature request
