### ISSUE TITLE
Parsing string containing numbers

### ISSUE THREAD

**Issue by Sudarshanshetty** [marmelroy/PhoneNumberKit#127]
Is there any way can just pass a string data  and get all the numbers , country code and also find is it toll free  ?

**Comment by marmelroy** [comment]
Do you mean multiple numbers in the same string or a string with just one number? 

Multiple numbers - No.
Single number string - Yes. That's the main point:
try phoneNumberKit.parse("+33 6 89 017383")

**Comment by Sudarshanshetty** [comment]
Ya we are looking for multiple numbers,  saw the equivalent Android lib. that has a method Findnumbers to get all the numbers in text

**Comment by KheangSenghort** [comment]
I really love your SDK phoneNumberKit, because it help our terms developer make easy & faster to load local contact to process other transaction.
