### ISSUE TITLE
countryCode(for: <REGION_CODE>) not working correctly

### ISSUE THREAD

**Issue by Blackjacx** [marmelroy/PhoneNumberKit#128]
Hi there,

when I do this:

```
let phoneNumberKit = PhoneNumberKit()
let locale = Locale.current
let isoRegionCodes = Locale.isoRegionCodes
let countryNames = isoRegionCodes.flatMap { locale.localizedString(forRegionCode: $0) }
let dialingCodes = isoRegionCodes.flatMap { phoneNumberKit.countryCode(for: $0) }
```

the dialling codes contain lots "1" 's ! When I compare other mappings like this one  http://stackoverflow.com/questions/13022601/list-of-countries-and-country-dialing-codes-for-ios?noredirect=1&lq=1 the country name "Anguilla" is mapped to "+1 264". Maybe this is a bug in the PhoneNumberKit.

Cheers 
Stefan

**Comment by marmelroy** [comment]
Hey Stefan, 

PhoneNumberKit is powered by metadata from Google's libPhoneNumber project (that powers most of the web/mobile's dealings with phone numbers). In the raw metadata, they consider Anguilla's country code as +1 (with 264 being part of the "national number").

We consider Google as the source of truth on this so this won't be considered a bug. 

To play with Google's own version - try https://libphonenumber.appspot.com.

**Comment by Blackjacx** [comment]
Oh thank you :-)
