### ISSUE TITLE
PhoneNumberKit doesn't recognize extensions with fewer than three characters

### ISSUE THREAD

**Issue by pzearfoss** [marmelroy/PhoneNumberKit#13]
We're using PhoneNumberKit in our app, but are having issues with it correctly identifying extensions.  For example the phone number `2129316760 x28` always loses the x28 extension.

```
(lldb) po phoneNumber
▿ PhoneNumber
  - countryCode : 1
  - leadingZero : false
  - nationalNumber : 2129316760
  - numberExtension : nil
  - rawNumber : "12125556760 x28"
```

We would expect common cases like x28 to be recognized as a valid extension.  Additionally, [this link](https://libphonenumber.appspot.com/) which appears to use google's phone number lib parses the phone number correctly.

**Comment by pzearfoss** [comment]
After doing some more exploration, theres some connection to the number of digits and parsing of the extension value:
```
(lldb) po PhoneNumber(rawNumber: "7035205555 x555")
▿ PhoneNumber
  - countryCode : 1
  - leadingZero : false
  - nationalNumber : 7035205555
  ▿ numberExtension : Optional("555")
    - Some : "555"
  - rawNumber : "7035205555 x555"

(lldb) po PhoneNumber(rawNumber: "7035205555 x5555")
▿ PhoneNumber
  - countryCode : 1
  - leadingZero : false
  - nationalNumber : 7035205555
  ▿ numberExtension : Optional("5555")
    - Some : "5555"
  - rawNumber : "7035205555 x5555"

(lldb) po PhoneNumber(rawNumber: "7035205555 x55")
▿ PhoneNumber
  - countryCode : 1
  - leadingZero : false
  - nationalNumber : 7035205555
  - numberExtension : nil
  - rawNumber : "7035205555 x55"

(lldb) po PhoneNumber(rawNumber: "7035205555 x5")
▿ PhoneNumber
  - countryCode : 1
  - leadingZero : false
  - nationalNumber : 7035205555
  - numberExtension : nil
  - rawNumber : "7035205555 x5"
```

**Comment by pzearfoss** [comment]
I've forked the library and dug in a bit, and this problem is actually caused by `NSDataDetector` in RegularExpressions.swift in the `phoneDataDetectorMatches` method.

This code snippet highlights the issue. Drop into a play ground to see it in action.  

```swift
import Foundation

let dataDetector = try! NSDataDetector(types: NSTextCheckingType.PhoneNumber.rawValue)

var nsString = "7035551234 x42" as NSString
var stringRange = NSMakeRange(0, nsString.length)
var matches = dataDetector.matchesInString("7035551234 x42", options: [], range: stringRange)

matches.forEach { (result) -> () in
    print(result.phoneNumber)   // prints "Optional("7035551234")"
}

nsString = "7035551234 x422" as NSString
stringRange = NSMakeRange(0, nsString.length)
matches = dataDetector.matchesInString("7035551234 x422", options: [], range: stringRange)

matches.forEach { (result) -> () in
    print(result.phoneNumber)   // prints "Optional("7035551234;422")"
}
```

I guess the question is, long term, whether PhoneNumberKit should rely on the iOS data detectors.

**Comment by marmelroy** [comment]
Thanks a lot for looking into this @pzearfoss, very interesting bug... 

The NSDataDetector was added for efficiency as part of the effort to boost parsing speeds. If it fails there is a fallback to libPhoneNumber's original Regular Expression. The problem here is that it doesn't technically fail but doesn't produce the expected result either. 

I will have a solution for this soon...

**Comment by pzearfoss** [comment]
Thanks @marmelroy, this is great news.  

We can work around it in the meantime.  Do you think this represents a bug with NSDataDetector? It seems like it to me, but it's *so* obvious that I can't believe it would be missed.  I think I might file a radar for it.

**Comment by mitchellporter** [comment]
Any updates on this?

**Comment by marmelroy** [comment]
Not yet. It definitely seems like a bug in NSDataDetector but I need to properly benchmark the benefit of using it vs the custom regular expression before deciding on the next move.

**Comment by mitchellporter** [comment]
@marmelroy Thanks for the update!

**Comment by marmelroy** [comment]
Quick update to say that this is still an issue...

**Comment by marmelroy** [comment]
Fixed (finally) by https://github.com/marmelroy/PhoneNumberKit/commit/b71cbadf1180814048608286985875437ace78e9
