### ISSUE TITLE
Feature Request: Allow app to specify path to PhoneNumberMetadata.json

### ISSUE THREAD

**Issue by mrubin** [marmelroy/PhoneNumberKit#131]
It would be great if there was a way for the app to provide the path/url to "PhoneNumberMetadata.json". It looks like [populateTerritories()](https://github.com/marmelroy/PhoneNumberKit/blob/78acba2e32d0f2a16851910e94f00d51d509a8cf/PhoneNumberKit/MetadataManager.swift#L46) hardcodes it to the framework's bundle.

The reason this would be great is because my app can go a long time between updates - I can't just release a new version if there is an update to the metadata - but I could remotely update the metadata if I were loading it from my app's bundle and not PhoneNumberKit's.

Thank you for your consideration.

**Comment by marmelroy** [comment]
Hi @mrubin. This is something that was considered at one point. The idea at the time was to actually host the JSON file on GitHub. 

I like your idea better. Will keep this issue open in consideration for the next big release.
