### ISSUE TITLE
Possible discrepancy with libphonenumber when using leading 0 with AU number

### ISSUE THREAD

**Issue by mrubin** [marmelroy/PhoneNumberKit#132]
From my understanding, you can specify the following Australian number with or without the leading zero (after the '61' country code):

+610403745123
+61403745123

[libphonenumber](https://libphonenumber.appspot.com/phonenumberparser?number=%2B610403745123) appears to deem both forms as valid. However, the latest PhoneNumberKit does not validate the form with the leading 0.

Is this a bug?

**Comment by marmelroy** [comment]
Hi @mrubin, just tested and both numbers are valid in the latest version of PhoneNumberKit.

(with region specified as either "US" or "AU")
