### ISSUE TITLE
"AU" local format not recognised

### ISSUE THREAD

**Issue by malikaferoze** [marmelroy/PhoneNumberKit#145]
Hi guys,
I've run into a bit of a dead end here. I'm using "PhoneNumberTextField" but when I enter a local Australian number without the state code in the format of XXXX XXXX (instead of X XXXX XXXX), it does not format it properly. I took the following steps and have ruled out the below mentioned possible causes. 

- I checked and confirmed that my region was auto selected to be AU.
- I went through "PhoneNumberMetadata.json" and found the following snippet under `"id": "AU"`
```
"mainCountryForCode": "true",
"fixedLine": {
    "possibleLengths": {
        "national": "9",
        "localOnly": "8"
    },
    "nationalNumberPattern": "[237]\\d{8}|8(?:[6-8]\\d{3}|9(?:[02-9]\\d{2}|1(?:[0-57-9]\\d|6[0135-9])))\\d{4}",
    "possibleNumberPattern": "\\d{8,9}",
    "exampleNumber": "212345678"
 }
```
The `localOnly` attribute tells me that the json does support an 8 digit local number but for some reason it is not being reflected by the formatter. Could you look into it please?

**Comment by rweindl** [comment]
Having the same issue for Australian `0440` prefixed numbers. Would be awesome to take a look into that!

**Comment by swiftlyfalling** [comment]
Can you provide valid AU sample phone numbers that exhibit the problem? (i.e. Can you find a phone number that's tested to work - ex. for a local business that posts it publicly - that meets either of your failure criteria?)

If you enter those same phone numbers into [libphonenumber's Javascript Demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), do they also fail?

(The earlier excerpt that @arslanmalik provided is only a small section of the AU phone number rules.)

**Comment by kuyazee** [comment]
The PhoneNumberKit metadata has been updated a few releases later.
