### ISSUE TITLE
Swift 4: Cannot convert return expression of type '[Character]?' to return type '[String]?'

### ISSUE THREAD

**Issue by dmcgloin** [marmelroy/PhoneNumberKit#147]
I know Swift 4 (and Xcode 9 Beta 1) is fresh out of the oven, but it would be nice to achieve cross-compile-ability as we begin migration.

In PhoneNumberKit.swift, the following function has the error shown below:

```
public func countries(withCode countryCode: UInt64) -> [String]? {
        let results = metadataManager.filterTerritories(byCode: countryCode)?.map{$0.codeID}.flatMap{$0}
        return results
    }
```

Error:

> Cannot convert return expression of type '[Character]?' to return type '[String]?'
    
The good news is that this is the only error/warning I'm seeing in Xcode 9 beta 1.

**Comment by marmelroy** [comment]
This should be fixed in 2.0.0
