### ISSUE TITLE
Need to check if a phone number has a country code

### ISSUE THREAD

**Issue by srcreigh** [marmelroy/PhoneNumberKit#148]
I wanted to use this library to check if a phone number includes a country code. However, if you give `PhoneNumberKit` an American phone number without a country code, it automatically inserts a 1.

I looked at the source and tried to use `PhoneNumberParser` but that API isn't exposed in the library.

How can I check if a phone number contains a country code?

**Comment by ponomarenkoartur** [comment]
extension PhoneNumberKit {
    var allCountryCodes: [UInt64] {
        return allCountries().compactMap { countryCode(for: $0) }
    }
    
    func isValidNumberWithCountryCode(_ number: String) -> Bool {
        // Check if number is valid
        do {
            let _ = try PhoneNumberKit().parse(number)
        } catch {
            return false
        }
        
        for countryCode in allCountryCodes {
        // Check if number starts with country code
            if number =~ "^\\+?\(countryCode).*" {
                return true
            }
        }
        return false
    }
}




'=~' is wrapper for regex. 

infix operator =~
func =~ (input: String, pattern: String) -> Bool {
    return Regex(pattern)?.test(input) ?? false
}

class Regex {
    let internalExpression: NSRegularExpression
    let pattern: String
    
    init?(_ pattern: String) {
        self.pattern = pattern
        if let internalExpression = try? NSRegularExpression(pattern: pattern, options: .caseInsensitive) {
            self.internalExpression = internalExpression
        } else {
            return nil
        }
    }
    
    func test(_ input: String) -> Bool {
        let matches = self.internalExpression.matches(in: input, options: .anchored, range: NSRange(location: 0, length: input.count))
        return matches.count > 0
    }
}

**Comment by kuyazee** [comment]
Fixed by #300
