### ISSUE TITLE
Add framework archive to release

### ISSUE THREAD

**Issue by kylejm** [marmelroy/PhoneNumberKit#15]
All you have to do is:

```
$ carthage build --no-skip-current
```
```
$ carthage archive PhoneNumberKit
```
Then just upload the .zip in the project root.

This will save a bunch of time on CI server and the like.

**Comment by marmelroy** [comment]
Thanks Kyle. 

Personally I don't think offering the pre-built framework is the best way to integrate third-party code. However, I can see how some people would appreciate the option (saving some CI time is appealing).

I'll keep it in mind for the next release.

**Comment by kylejm** [comment]
Awesome! Thanks you! :blush:

I agree, but purely for CI alone it's a massive benefit, especially when you have several dependancies. Building each one, then build and testing easily becomes a 10+ min process.

**Comment by marmelroy** [comment]
Hey Kyle! Doing a little clean up of open issues...  

Even though it will dramatically speed up CI, I still think it's best to avoid shipping prebuilt binaries of PhoneNumberKit, at least until Swift has a stable ABI. 

From Apple: 
> It would be dangerous to rely upon binary frameworks that use Swift — especially from third parties. As Swift changes, those frameworks will be incompatible with the rest of your app. 
https://developer.apple.com/swift/blog/?id=2

**Comment by kylejm** [comment]
Yeah that makes sense. I can fork and upload a prebuilt binary to my fork for the CI.

P.S. really good seeing you at NSLondon the other week! :)
