### ISSUE TITLE
[Question] Formatting

### ISSUE THREAD

**Issue by diogoAntunes** [marmelroy/PhoneNumberKit#150]
Hey, first of all thank you for all the hard work :)

I'm using the **PhoneNumberTextField** and its formatting wonderfully, for instance I get this number: (919) 694-8090

But if I set the text on the textfield programatically it does not trigger any specific format, my question is how can I format a phone number to appear like that? I've tried all the 3 options (.e164, .internationl, .national) but without any luck.

**Comment by Pro2005** [comment]
Hi, I call textField:shouldChangeCharactersInRange after assigning new value. That performs update of textField

`textField.text = "1231321321"
textField.textField(textField, shouldChangeCharactersIn: NSMakeRange(0, 0), replacementString: "")`

**Comment by marmelroy** [comment]
Yes, you can do your own update the way @Pro2005 showed. Might provide a built in solution for this in a future version.
