### ISSUE TITLE
[enhancement] Missing `isNumberMatch` method of `libphonenumber` library 

### ISSUE THREAD

**Issue by StarWars** [marmelroy/PhoneNumberKit#154]
There seems to be no way of comparing two phone numbers using `PhoneNumberKit` library.
I think a method matching `isNumberMatch` behaviour, would be a great addition.

**Comment by marmelroy** [comment]
Hi @StarWars, PhoneNumber objects implement equatable and can be compared simply with ==. Let me know if you have a case where this doesn't work.

**Comment by morisk** [comment]
Its different. `isNumberMatch` have from iziz's libPhoneNumber have multiple results:
```
typedef NS_ENUM(NSInteger, NBEMatchType) {
  NBEMatchTypeNOT_A_NUMBER = 0,
  NBEMatchTypeNO_MATCH = 1,
  NBEMatchTypeSHORT_NSN_MATCH = 2,
  NBEMatchTypeNSN_MATCH = 3,
  NBEMatchTypeEXACT_MATCH = 4
}; 
```
