### ISSUE TITLE
Feature Request: Get country from a given phone number

### ISSUE THREAD

**Issue by gligorkot** [marmelroy/PhoneNumberKit#156]
Would it be possible to get a country from a given phone number?

I have a partial solution, my main problem is when the phone number starts with +1 as this generally returns the US, but it might be Canada or any of the Island countries that start with +1xxx.

Any guidance would be helpful.

Thanks

**Comment by yousifa** [comment]
you can do this by looking at area codes

**Comment by gligorkot** [comment]
@yousifa thanks for your reply, so currently there's:
```
public struct PhoneNumber {
    public let numberString: String
    public let countryCode: UInt64
    public let leadingZero: Bool
    public let nationalNumber: UInt64
    public let numberExtension: String?
    public let type: PhoneNumberType
}
```
what you're suggesting is to look at the `nationalNumber`? Is that right? How is that going to give me the country?

**Comment by yousifa** [comment]
To make this easier, use an API like https://numverify.com/ and send them the phone number in e164 format (see a recent issue where I responded how to do that). The API includes the location in its response.


Another way is to build a local dictionary of all area codes and their locations (you can get it from https://www.areacodelocations.info/areacodelist.html), then parse the phone number for the 3 numbers after the +1 and search the dict for the area code.

**Comment by gligorkot** [comment]
Thanks for offering these solutions @yousifa. My understanding was that PhoneNumberKit already has a local dictionary of all area codes, well at least it does for phone number verification purposes, maybe not for getting the exact location. This is the reason for my "feature request" as it would be great to have a method like this:

`public func country(forPhoneNumber phoneNumber: PhoneNumber) -> String?`

Is this not an appropriate feature request?

**Comment by yousifa** [comment]
It isn't difficult to implement this and it sounds reasonable to me. I don't currently have time to do this though, hopefully someone else can pick it up? @marmelroy

**Comment by gligorkot** [comment]
Another option for this would be to add country to the `PhoneNumber` struct, perhaps?

```
public struct PhoneNumber {
    public let numberString: String
    public let countryCode: UInt64
    public let leadingZero: Bool
    public let nationalNumber: UInt64
    public let numberExtension: String?
    public let type: PhoneNumberType
    **public let country: String**
}
```

I am happy to try and implement this as send a PR if you let me know which solution you like better?

**Comment by OlivierLapraye** [comment]
@gligorkot Have you done a PR by this time ? Or found a simple way to do it by yourself ? I would like to be able to separate the 25 countries using the `+1` code

**Comment by gligorkot** [comment]
Hi @OlivierLapraye, no I have not worked on this one at all; would still be very handy to have it though so do let me know if you manage to work it out

**Comment by OlivierLapraye** [comment]
I am not familiar with the library and how it works, so I did an extraction for my project : 

If there are several countries for a country indicator (e.g. `+1` has 25 values: US, CA, US Islands, etc), I look in a list of structures which contains the rules for each country. If the indicator is `+1` and starts with `204, 226, ...` then I know it's Canada. My structure contains : 
- The country indicator: `+1`
- The nth first digits to take in consideration (3 for Canada)
- The list of possible digits: `204, 226, ...`
- The country abreviation: `CA`

I don't know if I am very clear, I can share code snippets if you'd like.

**Comment by gligorkot** [comment]
Thanks Olivier, code snippets would definitely help; potentially for whoever implements this feature too!

**Comment by kuyazee** [comment]
Hello @gligorkot I know this answer is late but you can find the country of a number by doing this

```
do {
    let phoneNumberKit = PhoneNumberKit()
    let phoneNumber = try phoneNumberKit.parse("+639065432109")
    let country = phoneNumberKit.regionCode(of: phoneNumber)
    print(country) // prints `ph` for Philippines
} catch {
    print("Generic parser error")
}
```
