### ISSUE TITLE
Issue with phone number "375336867646"  in v1.3.0, working fine in v1.2.3. Metadata issue ?

### ISSUE THREAD

**Issue by Pitsko** [marmelroy/PhoneNumberKit#161]
In v1.2.3 this code works fine
let phoneNumber = try phoneNumberKit.parse("375336867646", withRegion: "BY")

But in v1.3.0 it generates exception in next lines
        // Test number against general number description for correct metadata (8)
        if let generalNumberDesc = regionMetadata.generalDesc, (regexManager.hasValue(generalNumberDesc.nationalNumberPattern) == false || parser.isNumberMatchingDesc(nationalNumber, numberDesc: generalNumberDesc) == false) {
            throw PhoneNumberError.notANumber
        }

It is real Belarusian phone number, I am sure

Any ideas what can be reason ?

**Comment by MSavisko** [comment]
@Pitsko 
Add "+" at start of the phone number.
`let phoneNumber = try phoneNumberKit.parse("+375336867646", withRegion: "BY")`
