### ISSUE TITLE
Xcode 9 cannot compile

### ISSUE THREAD

**Issue by ibrahimchiha** [marmelroy/PhoneNumberKit#162]
I recently installed PhoneNumberKit, and for some reason I cannot compile using Xcode 9 beta.

I get an error saying:
`Cannot convert return expression of type [Character]? to return type [String]?`

in the PhoneNumberKit.swift file

Any ideas?

**Comment by dpopov** [comment]
The final .flatMap is actually extra since the .map is already returning a flat array of [String]?

**Comment by marmelroy** [comment]
Sorry for the delay with this -  this bug is fixed by version 2.0.0
