### ISSUE TITLE
do we have method to find numbers in text String which is there in google's libphonenumber

### ISSUE THREAD

**Issue by amtula** [marmelroy/PhoneNumberKit#165]
This library is inspired by google's libphonenumber for android but i couldn't find following method in this library which is there in google's libphonenumber.

findNumbers - finds numbers in text input.
public Iterable findNumbers(CharSequence text, String defaultRegion)
{

}

So if there is something like similar please let me know at earliest.

Thanks in advance , waiting for quick reply

**Comment by marmelroy** [comment]
Hi @amtula - we don't have a similar function in PhoneNumberKit and there are currently no plans to add it. Sorry about that.
