### ISSUE TITLE
Swift 4 - 'range(at:)' has been renamed to 'rangeAt(_:)'

### ISSUE THREAD

**Issue by Gerst20051** [marmelroy/PhoneNumberKit#168]
Pods/PhoneNumberKit/PhoneNumberKit/PhoneNumberParser.swift:286:45:

func `stripNationalPrefix`
line `let firstRange = firstMatch.range(at: numOfGroups)`

`'range(at:)' has been renamed to 'rangeAt(_:)'`
`'range(at:)' was introduced in Swift 4`

<img width="308" alt="screenshot 2017-09-22 10 32 25" src="https://user-images.githubusercontent.com/235372/30749531-ae8dd804-9f81-11e7-9293-2fe3af7e80e7.png">

**Comment by Gerst20051** [comment]
Nevermind I still haven't figured out how to get my app updated to Swift 4 it keeps failing.

**Comment by JRuedas** [comment]
Hi, 

I don't know why this issue is closed because actually it's an error.

Even if you are able to avoid the error in XCode (as I did) when you try to use fastlane to build the app it will fail.

I opened a new issue showing the error: #171

**Comment by Gerst20051** [comment]
You need up update your app to use Swift 4 that's why it's giving this error. My app was still configured to use Swift 3.

**Comment by williamtwilson** [comment]
My app is using Swift version 4, and I'm still seeing this error.

**Comment by JRuedas** [comment]
@williamtwilson check pod's configuration, I'm not really sure because I solved the issue long time ago, but I remember that was related to that, I'll check it asap :)

**Comment by mzm008** [comment]
still this error range(at:)' has been renamed to 'rangeAt(_:)

**Comment by shlomnissan** [comment]
I fixed it by changing the Swift Language Version in the settings to Swift 4. I also had to clean my build folder, updated my pods and restart Xcode before it would compile. Hope it helps
