### ISSUE TITLE
Amimono support

### ISSUE THREAD

**Issue by YuriiTrach** [marmelroy/PhoneNumberKit#169]
Currently, if I'm using cocoapod amimono plugin. The framework works incorrectly. Looks like it doesn't have an access to internal DB. Have you any idea how to fix it?
Framework version is 2.0.0

**Comment by marmelroy** [comment]
Hi @YuriiTrach, I'm not familiar with cocoapods-amimono and it sounds like an issue with the way the plugin supports the pod spec resources. 

Might be worth raising on the plugin project.

Closing for now.
