### ISSUE TITLE
Make PartialFormatter public

### ISSUE THREAD

**Issue by kylejm** [marmelroy/PhoneNumberKit#17]
Unless there's any reason not to?

My reason for using it would be for a AsYouType TextField I'm putting together until we get PhoneNumberKit's lovely version :smile:.

Alternatively, I'd be more than happy to help with implementation/testing with PhoneNumberKit's AsYouType TextField?

**Comment by marmelroy** [comment]
The official AsYouType text field is taking a little while (got distracted, back on it soon)... 

I'm afraid the PartialFormatter is actually the unfinished part :smile: will make it public when it's ready

**Comment by kylejm** [comment]
Oaky cool, let me know if you'd like any help with any of it. We're using this in [loot.io](http://loot.io)'s iOS app, so we'd love to contribute and support :)
