### ISSUE TITLE
Swift 4: Renamed function range(at: ) to rangeAt()

### ISSUE THREAD

**Issue by JRuedas** [marmelroy/PhoneNumberKit#171]
After I migrated my app to Swift 4 when Fastlane tries to build the app an error is shown saying that method range(at: ) has been renamed to rangeAt().

![captura de pantalla 2017-09-25 a las 10 28 43](https://user-images.githubusercontent.com/11670560/30800678-0e29c0c8-a1e1-11e7-8013-a9a93d267303.png)

**Comment by Gerst20051** [comment]
You need up update your app to use Swift 4 that's why it's giving this error.

**Comment by JRuedas** [comment]
That's true, it worked after upgrading Swift versión in App's Podfile.
