### ISSUE TITLE
Validate a phone number

### ISSUE THREAD

**Issue by nitishrana28** [marmelroy/PhoneNumberKit#172]
This is my code :  
  
```
let phoneNumber = String(format: "%@ %@", (self.button_country.titleLabel?.text?.components(separatedBy: " ")[1])!, self.textField_phone.text!)    //  +91 9898989898
let phoneNumberValid = try phoneNumberKit.parse(phoneNumber, withRegion: (self.button_country.titleLabel?.text?.components(separatedBy: " ")[0])!, ignoreType: true) 
``` 
  
Is this the correct way to validate phone number (including international code) ? This is what comes in phoneNumberValid (I don't think it is showing correct information):  
  
![screen shot 2017-09-26 at 6 07 14 pm](https://user-images.githubusercontent.com/1484780/30860722-beb553d0-a2e5-11e7-9ff8-73fa9b7c1874.png)
  
How to use this property further ?

**Comment by marmelroy** [comment]
Hi @nitishrana28, so phoneNumberKit.parse throws in case the number is invalid for the region. If you pass ignoreType: false it does a harder validation (a bit more costly performance wise).
