### ISSUE TITLE
Add function to get example number for country code

### ISSUE THREAD

**Issue by SchmidtyApps** [marmelroy/PhoneNumberKit#178]
The google lib version of this library has a handy way to get an example number to show. This is often used as a placeholder for input fields on major apps including Lyft and would be simple to add because the meta data already has this info available.

**Comment by SchmidtyApps** [comment]
I have opened a pull request to implement this behavior. Adding example phone number function to PartialFormatter #159

**Comment by marmelroy** [comment]
Thanks @SchmidtyApps, I now understand the need for this but many example numbers are currently being deprecated in the libPhoneNumber metadata and I worry about exposing them in this way. Let's keep this as a feature suggestion and think about the proper way to implement it.

**Comment by marmelroy** [comment]
Will close the PR for now.

**Comment by SchmidtyApps** [comment]
@marmelroy I didn't see where example numbers are being deprecated but that makes sense. They seem to still have example numbers listed in their readme so I don't think they are getting rid of them. The way I had added the example numbers they were optional though so if one didn't exist it would just return nil and the developer could gracefully handle it. I can just use my fork until you decide what you want to do. Thanks!

**Comment by klemenzagar91** [comment]
im also looking for having examples in our app. I hope this will soon be part of this library

**Comment by SchmidtyApps** [comment]
@marmelroy Have you given this anymore thought? I need the example numbers in the next month or so and would be happy to do the work. I still think a good temporary solution could be what I had proposed before where it returns an example number or nil if one doesn't exist. Please let me know your thoughts. Thanks!

**Comment by f3ell0w** [comment]
Any updates on this?

**Comment by kuyazee** [comment]
You can now do this by using the newly exposed methods. Ex.
```
let phoneNumberKit = PhoneNumberKit()
print(phoneNumberKit.metadata(for: "gb")?.emergency?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.fixedLine?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.generalDesc?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.mobile?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.pager?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.personalNumber?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.premiumRate?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.sharedCost?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.tollFree?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.voicemail?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.voip?.exampleNumber)
print(phoneNumberKit.metadata(for: "gb")?.uan?.exampleNumber)
```
