### ISSUE TITLE
PhoneNumberKit doesn't handle autocomplete numbers

### ISSUE THREAD

**Issue by darkzlave** [marmelroy/PhoneNumberKit#180]
If we have a field that is suppose to be a phone number, Apple will automatically show phone suggestions so that the user doesn't have to type the whole number, when using this suggestions `open func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool ` seems to behave in very strange ways and now allowing for the phone number to correctly get in the field.

**Comment by rpotze** [comment]
It seems this can be fixed by catching this case in a special condition at the very beginning of the: `open func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool
` method in PhoneNumberKit.

Details are explained in the code comments below.

I have not tested this extensively but it seems to be a harmless fix given that the condition has a pretty narrow scope.

The condition to be added at the beginning is:
```
// When an autocomplete phone number is selected by the user, the values passed
// in this call are curious:
// - range: an NSRange with location: 0, length: 0
// - replacementString: " "
// In this case, return true to allow the edit without any further processing.

// Note: No PhoneNumberKit formatting will be applied in this case but
// that seems acceptable as it is more intuitive for the user that the phone number
// selected in the keyboard is copied exactly into the field when tapped,
// without formatting changes.

// Note: This code can also be triggered in the Simulator (or a device?) by using a
// hardware keyboard and pressing the space bar. The effect is pretty harmless in any
// case, it just enters the space as the first character.

if range == NSRange(location: 0, length: 0) &&
    string == " " {
    // print("User tapped autocomplete phone number in keyboard.")
    return true
}
```

**Comment by marmelroy** [comment]
That was an interesting discussion, thanks to both. Resolved in: https://github.com/marmelroy/PhoneNumberKit/commit/e281ef66de726839f88487df1380f4e17e44dbcf

**Comment by CoolHandLuke88** [comment]
This still seems to be issue. Selecting the autofill in keyboard won't populate the field.

**Comment by ThibaultVlacich** [comment]
@CoolHandLuke88 It's because the maintainer of this project seems absent and haven't released a new version since this fix has been pushed. You can import the pod directly from the git repo to have the fix:

```pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit.git', :commit => 'e281ef6'```
