### ISSUE TITLE
Swift 4 changes

### ISSUE THREAD

**Issue by leifashley** [marmelroy/PhoneNumberKit#181]
PhoneNumberParser.stripNationalPrefix() has some deprecated items, like characters, but also have a build error:
let firstRange = firstMatch.range(at: numOfGroups)

... should be ... 

let firstRange = firstMatch.rangeAt(numOfGroups)

**Comment by Monserg** [comment]
Hi.
Today I add framework to my App & see this:
http://take.ms/ylvi3

**Comment by marmelroy** [comment]
This should be fixed in release 2.1.0. Apologies for the delay.
