### ISSUE TITLE
Carthage Error

### ISSUE THREAD

**Issue by m3rLin0WoRK** [marmelroy/PhoneNumberKit#183]
Hi, 

it's impossible for me, build with carthage for watchOS, tvOS and macOS. Only iOS works.

this is the error produced
** ARCHIVE FAILED **

The following build commands failed:
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by marmelroy** [comment]
This should be fixed in release 2.1.0. Apologies for the delay.
