### ISSUE TITLE
XCode 9.1 support

### ISSUE THREAD

**Issue by Mazorati** [marmelroy/PhoneNumberKit#185]
Hello!
There are several warnings on XCode 9.1
<img width="446" alt="2017-11-25 15 43 58" src="https://user-images.githubusercontent.com/3396425/33230596-7ce193ce-d1f7-11e7-82bb-290ed28da445.png">

**Comment by nikolay-kapustin** [comment]
https://github.com/marmelroy/PhoneNumberKit/pull/174

**Comment by marmelroy** [comment]
This should be fixed in release 2.1.0. Apologies for the delay.
