### ISSUE TITLE
How to get raw number from PhoneNumberTextField

### ISSUE THREAD

**Issue by derekbsnider** [marmelroy/PhoneNumberKit#186]
Is there an easy way to get the raw number (without formatting) from PhoneNumberTextField?

I want to use PhoneNumberTextField to make the number easier for the user to see, but I want to keep the number as an integer internally to the application.

**Comment by yousifa** [comment]
+1 here

**Comment by namannik** [comment]
Here's how I'm getting a raw number from a formatted number in my application.  (It's probably not the most efficient way to do this, but hey, it works.)

```swift
func rawPhoneNumber(_ number: String) -> String {
    var rawNumber = ""
    for index in number.indices {
        let nextDigit = String(number[index])
        if Int(nextDigit) != nil {
            rawNumber = rawNumber + nextDigit
        }
    }
    return rawNumber
}
```

**Comment by yousifa** [comment]
`
@IBOutlet var _phoneNumber: PhoneNumberTextField!

@IBAction func SomeButton(_ sender: Any){

let phoneRaw = phoneNumberKit.format(try phoneNumberKit.parse(_phoneNumber.text!), toType: .e164)

}
`

**Comment by NeelSarwal** [comment]
We ended up just doing something like this

```swift
func rawFormat(_ formattedNumber: String) -> String {
    return formattedNumber.filter { Int(String($0)) != nil }
}
```

**Comment by eliburke** [comment]
These workarounds are useful, but it'd be great if the raw input was kept available in PhoneNumberTextField, or if PartialFormatter provided a method, or even the internal PhoneNumberParser was public. I wanted to be able to clean up the formatting when the user backspaces a number, and went down a rabbit hole for an hour trying to use nationalNumber() (which strips off country codes) and parse() (which won't parse incomplete numbers).
