### ISSUE TITLE
New area code recognition

### ISSUE THREAD

**Issue by windtalkerlv** [marmelroy/PhoneNumberKit#189]
Hi all, there are several new area code for the US rolling out soon according to the [wikipedia](https://en.wikipedia.org/wiki/List_of_future_North_American_area_codes) article, I am wondering could there a option in the future to turn off the area code matching and only do format matching?

I have tried some potential new numbers with the future area code, and most of them cannot be parsed and formatted. I am sure new codes are being rolled out all over the world as well. 

Thanks guys

**Comment by namannik** [comment]
To disable area code matching, you might try setting the `ignoreType` parameter to `true` when calling `parse`.  For example:

```swift
try phoneNumberKit.parse("555-555-1234", withRegion: "US", ignoreType: true)
```

This will add the appropriate country code, but skip number type checking.

**Comment by kuyazee** [comment]
The `PhoneNumberMetaData.json` has also been updated for the recent releases. Closing this issue
