### ISSUE TITLE
Public `maxDigits`

### ISSUE THREAD

**Issue by borut-t** [marmelroy/PhoneNumberKit#191]
I would like to have property `maxDigits` public in `PartialFormatter` so i can use it when formatting textfields without `PhoneNumberTextField`.

**Comment by anilabsinc-ajay** [comment]
Yes also the withPrefix should be public so that we can subclass them

**Comment by natan** [comment]
+1, I would like to see this made public as well. @marmelroy I'm happy to implement this if you're open to that!

**Comment by marmelroy** [comment]
Hi @natan. Happy with this direction and a PR will be super appreciated.
