### ISSUE TITLE
Manual space ignored when formatting a number

### ISSUE THREAD

**Issue by Lupurus** [marmelroy/PhoneNumberKit#195]
I have the following german mobile number: 0151 40123456 (just a test number, but the 4 at the beginning is import...)
PhoneNumberKit is formatting this to +49 1514 0123456. But it should be +49 151 40123456.
Printing the parsed number shows:
```
PhoneNumber(numberString: "0151 40123456", countryCode: 49, leadingZero: false, nationalNumber: 15140123456, numberExtension: nil, type: PhoneNumberKit.PhoneNumberType.mobile)
```

**Comment by kuyazee** [comment]
Hello @Lupurus though it's a very late answer, PhoneNumberKit is only parsing based on the regex rules given by the metadata from [libphonenumber](https://github.com/google/libphonenumber), we have no control whatsoever how it parses the data. This is better to be filed at this [repository](https://github.com/google/libphonenumber)
