### ISSUE TITLE
Valid phone from Morocco do not parse  

### ISSUE THREAD

**Issue by papaz0rgl** [marmelroy/PhoneNumberKit#198]
Hello,  

Parsing "+212 767-491196" failed, but the number is a valid morocco mobile number. http://libphonenumber.appspot.com/phonenumberparser?number=%2B212+767-491196 

update :  the "7" prefix has been introduce recently : 

"In view of the current use of numbers allocated to mobile networks, it has been decided to open a new prefix, "+212 (07)", for use of mobile networks, as of 7 August 2016."

(https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000900002PDFE.pdf) 

Any idea why  ? Maybe the meta data need to be updated ?

**Comment by papaz0rgl** [comment]
Hello, 

I checked on libphonenumber. The change to take these Morocan mobile number has been made in the version 8.8.7 of the metadata. 

Is there any way to update the metadata used by the pod ?

**Comment by marmelroy** [comment]
Hi @papaz0rgl, sorry for the delay. Metadata has been updated.
