### ISSUE TITLE
Better formatting and a version of AsYouTypeFormatter

### ISSUE THREAD

**Issue by marmelroy** [marmelroy/PhoneNumberKit#2]
Formatting of parsed phone numbers for display is still very basic in 0.1 and should be improved in the next version. 

Also, an equivalent to libPhoneNumber's AsYouTypeFormatter would be useful and still within the scope of this framework.

**Comment by marmelroy** [comment]
Better formatter done. Matches Google's libPhoneNumber. 

AsYouTypeFormatter coming soon.

**Comment by andresgarza** [comment]
+1

**Comment by marmelroy** [comment]
Thanks @andresgarza! Got a little distracted away from the AsYouTypeFormatter. Expecting to have a working version during the week.

**Comment by andresgarza** [comment]
@marmelroy thanks!, will definitely try it out and send some feedback

**Comment by marmelroy** [comment]
Still unfinished I'm afraid but a lot of progress was made. There are some unexpected challenges in allowing a user to edit any part of the textfield and keeping the cursor at a logical place. Will figure out a solution soon.

**Comment by andresgarza** [comment]
@marmelroy not sure if it helps at all, but a trick i've seen for formatting credit cards numbers is to use letter spacing (kerning) to fake spaces (as opposed to actually adding spaces to text in textfield)

**Comment by irace** [comment]
Any update on when it's expected that the AsYouTypeFormatter might land?

**Comment by marmelroy** [comment]
Hi @irace, I've been very very busy but getting the AsYouTypeFormatter is my only open source goal for the coming week. Let's commit to it landing by 5th Feb.

**Comment by irace** [comment]
Sounds great. Thanks for the update!

**Comment by marmelroy** [comment]
Late but making progress :crying_cat_face:

**Comment by marmelroy** [comment]
Getting close. Check out progress on https://github.com/marmelroy/PhoneNumberKit/tree/feature_asyoutypeformatter

It works well now but there's one rare bug left on deletion from the middle. Also, the code needs a little clean up + documentation and tests.

**Comment by marmelroy** [comment]
Released in 0.6 (finally)
