### ISSUE TITLE
Some German mobile phone numbers not parsed correctly

### ISSUE THREAD

**Issue by greimers** [marmelroy/PhoneNumberKit#205]
I noticed that some German mobile phone numbers fail to parse with PhoneNumberKit.
Most numbers work fine but some are wrongly reported as "invalid".

I wrote the following test code:

```swift
let fails1: String  = "‭+49 172 1547608"
let fails2: String  = "‭+49 172 1237608‬"
let fails3: String  = "‭+49 172 1234508‬"
let fails4: String  = "‭0172 1234568‬"
let fails5: String  = "‭+49 176 45155875"
let fails6: String = "+49 157 74284590‬"
let fails7: String = "+49 160 99462990‬"
let fails8: String = "+49 177 5814332‬"
        
let works1: String  = "+49 172 1234567"
let works2: String  = "+49 172 3333338"
let works3: String  = "+49 176 12345678"
let works4: String  = "0176 34524036"

let numbers = [fails1, fails2, fails3, fails4, fails5, fails6, fails7, fails8,
                       works1, works2, works3, works4]

let phoneNumberKit = PhoneNumberKit()

for number in numbers {
    do {
            let phoneNumber = try phoneNumberKit.parse(number, withRegion: "DE", ignoreType: true)
            let formattedNumber = phoneNumberKit.format(phoneNumber, toType: .international)
            let type: PhoneNumberType = phoneNumber.type
            let typeName: String
            switch type {
            case .mobile, .fixedOrMobile:
                typeName = "Mobile"
            default:
                typeName = "Other"
            }
            Log.info?.message("\(formattedNumber) vaild. Type: \(typeName)")
        } catch let error {
                Log.error?.message("\(number) failed: \(error.localizedDescription)")
        }
}
```

And I get the following output:
```
❌ +49 172 1547608 failed: The number provided is invalid.
❌ +49 172 1237608 failed: The number provided is invalid.
❌ +49 172 1234508 failed: The number provided is invalid.
❌ 0172 1234568 failed: The number provided is invalid.
❌ +49 176 45155875 failed: The number provided is invalid.
❌ +49 157 74284590 failed: The number provided is invalid.
❌ +49 160 99462990 failed: The number provided is invalid.
❌ +49 177 5814332 failed: The number provided is invalid.
🔷 +49 172 1234567 vaild. Type: Other
🔷 +49 172 3333338 vaild. Type: Other
🔷 +49 176 12345678 vaild. Type: Other
🔷 +49 176 34524036 vaild. Type: Other
```

Also note that the type for the successfully parsed is `other` even though all numbers are mobile numbers.

The same numbers work correctly with the [google libPhoneNumber online tool](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and with [iziz libPhoneNumber-ios](https://github.com/iziz/libPhoneNumber-iOS)

**Comment by marmelroy** [comment]
Thanks for reporting @greimers and sorry for the delay, this was an interesting bug.

Turns out there is a secret extra character in the set of failing numbers (it's a line break unicode char).

When you remove it, everything works as expected:
        let fails1: String  = "+49 172 1547608"
        let fails2: String  = "+49 172 1237608"
        let fails3: String  = "+49 172 1234508"
        let fails4: String  = "0172 1234568"
        let fails5: String  = "+49 176 45155875"
        let fails6: String = "+49 157 74284590"
        let fails7: String = "+49 160 99462990"
        let fails8: String = "+49 177 5814332"

        let works1: String  = "+49 172 1234567"
        let works2: String  = "+49 172 3333338"
        let works3: String  = "+49 176 12345678"
        let works4: String  = "0176 34524036"
