### ISSUE TITLE
Couldn't Generate Swift Representation. (Carthage)

### ISSUE THREAD

**Issue by SergeyKovalenko** [marmelroy/PhoneNumberKit#207]
I'm using `Carthage` to manage dependencies and noticed that I can't review `PhoneNumberKit`s definitions. When clicking  `Cmd-Click -> Jump to definition` on an object from`PhoneNumberKit` this error is thrown: **"Couldn't Generate Swift Representation'**
![](https://user-images.githubusercontent.com/6182351/33729003-95254d36-db39-11e7-901f-bc5c817fc799.png)

Here is [`SourceKit` crash](https://gist.github.com/SergeyKovalenko/9de3ade372638da18591143753bbe2e0)

But after  removing `TextField.swift` from the `PhoneNumberKit` target definitions start working.  
Is it possible to move `TextField` to separate framework target to workaround this issue?

**Comment by wickwirew** [comment]
Out of curiosity I'm seeing the same issue on another library. How did you know that the `TextField.swift` was the source of the issue? I'm not seeing anything in the crash log.

**Comment by AlexanderBollbach** [comment]
having this problem think its a carthage issue.  anyone find the solution?
