### ISSUE TITLE
Trying to Create a Pull Request

### ISSUE THREAD

**Issue by codywinton** [marmelroy/PhoneNumberKit#21]
Trying to create a pull request on your project, but I don't have access. Are you open to pull requests?

**Comment by marmelroy** [comment]
Hi @codywinton. Yup, always open to pull requests. There shouldn't be any access issues...

If you are stuck: https://help.github.com/articles/creating-a-pull-request/

**Comment by codywinton** [comment]
@marmelroy - Ok, so in order to create a pull request, would I have to clone or fork your repo?

**Comment by codywinton** [comment]
I cloned your repo, branched off of master, made the changes, and committed my changes to that branch. Now, trying to push that branch to remote and getting this:

    Pushing to https://github.com/marmelroy/PhoneNumberKit.git
    remote: Permission to marmelroy/PhoneNumberKit.git denied to codywinton.
    fatal: unable to access 'https://github.com/marmelroy/PhoneNumberKit.git/': The requested URL returned error: 403

**Comment by marmelroy** [comment]
You can't just push to remote. You need to click the green Compare and Review button and create a pull request via GitHub's system.

Please follow the instructions on https://help.github.com/articles/creating-a-pull-request/

**Comment by codywinton** [comment]
@marmelroy - My confusion was in Cloning vs. Forking. Solved my issue and created the pull request. Thanks!
