### ISSUE TITLE
Phone number starting with 0 not detected.

### ISSUE THREAD

**Issue by sunny131984** [marmelroy/PhoneNumberKit#211]
HI ,

First of all thanks for great framework.
I am thinking to use this in my application but i face small issue as suggested below.
 1 ) Phone number added with prefix as 0 instead of + than that number is invalid.

Please suggest something for it.

**Comment by eman6576** [comment]
+1

**Comment by anhhtbk** [comment]
How do you do? I see it work normally. 
`          phoneStr = phoneNumberKit.format(phoneNumber, toType: .e164)
`
