### ISSUE TITLE
New China Area codes are not working

### ISSUE THREAD

**Issue by pinara747** [marmelroy/PhoneNumberKit#214]
Following new area codes for China are not working with phoneNumberKit as of 2.1.0

New number segments in China
+86 198 xxxxxxxx --> Using for China Mobile 
+86 165 xxxxxxxx --> Using for China Mobile

Please add support for these area codes. Thanks!

**Comment by dongpoRen** [comment]
> Following new area codes for China are not working with phoneNumberKit as of 2.1.0
> 
> New number segments in China
> +86 198 xxxxxxxx --> Using for China Mobile
> +86 165 xxxxxxxx --> Using for China Mobile
> 
> Please add support for these area codes. Thanks!

hello, do you solve this question? we also attacked by the `191`  question。
