### ISSUE TITLE
Linux and Swift PM support

### ISSUE THREAD

**Issue by florianreinhart** [marmelroy/PhoneNumberKit#216]
It would be great to use PhoneNumberKit on the server.

**Comment by nichdu** [comment]
I do this by using my own branch (DasScrumTeam/PhoneNumberKit@67d5ef6) where I require the PhoneNumberMetadata.json to be located at /tmp/PhoneNumberMetadata.json. This, of course, is not a great solution but it works for now. 
One could include the json data as string in any of the swift files or code it directly as swift types but that would be more work to do.

**Comment by janderit** [comment]
correction to @nichdu comment above:

PhoneNumberKit does **not** work on linux right now.
Apart from a number of compile time issues, which are fixed here [https://github.com/DasScrumTeam/PhoneNumberKit/commit/12573803784e2742182dabb5f9b89c2d063da789](https://github.com/DasScrumTeam/PhoneNumberKit/commit/12573803784e2742182dabb5f9b89c2d063da789), there are runtime issues related to converting metadata Dictionaries to NSDictionaries. Those are hidden by empty catch blocks, unfortunately.

A starting point can be found here [https://github.com/DasScrumTeam/PhoneNumberKit/commit/720435db77188696f7c458a950fa97096d3b2c15](https://github.com/DasScrumTeam/PhoneNumberKit/commit/720435db77188696f7c458a950fa97096d3b2c15), if anyone wants to pick this up.

Also, there are no working tests on linux right now.

**Comment by marmelroy** [comment]
this is very interesting @janderit and @nichdu - any PR that will help improve compatibility with Linux will be very much appreciated
