### ISSUE TITLE
jio numbers are not working. 

### ISSUE THREAD

**Issue by karthironald** [marmelroy/PhoneNumberKit#217]
In **India** we had a new and popular service called **jio**. It would be good if we have support for **jio numbers** as well.

**Comment by ashraf-patel** [comment]
The bug is reported in libphonenumber only.

Here is the link,

https://issuetracker.google.com/issues/115415787

**Comment by kuyazee** [comment]
Metadata has been updated, since libphonenumber's issue is fixed this should also work
