### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by jmrbcu** [marmelroy/PhoneNumberKit#223]

**Comment by sushant40** [comment]
why do you say this?

**Comment by ericwastaken** [comment]
@jmrbcu , I see commits from 7 months ago. Why would you think it's dead? Is there an issue you're trying to work through?

**Comment by pocketlim** [comment]
I've pinged @marmelroy about some updates since July 7, 2018, and no response. 

There are 10 PRs, none of which have responses from him either. 

You can draw your own conclusions, but it's looking like the maintainer hasn't looked back.

**Comment by marmelroy** [comment]
The project is not dead - it's just very difficult to find the time to actively maintain it right now. Volunteers and collaborators are welcome.

**Comment by ericwastaken** [comment]
@marmelroy - I'd be happy to help review PRs, answer questions, etc. Would that help you accept PRs, etc?
