### ISSUE TITLE
Partial formatter failing for region (US)

### ISSUE THREAD

**Issue by jmrbcu** [marmelroy/PhoneNumberKit#224]
This will fail: 
```swift
let s = PartialFormatter().formatPartial("(832) 5894420")
```

the output is: (832) 5894420 and it shoud be: (832) 589-4420

**Comment by bennnjamin** [comment]
I ran into this issue as well. You can use ```NBAsYouTypeFormatter``` from https://github.com/iziz/libPhoneNumber-iOS but you have to set a region like ```"US"```. Another workaround is to sanitize the input before running it through the partial formatter to remove unwanted characters. I have not completely tested this but it will work for partial formatting on US numbers and E.164 numbers:

```
let sanitized = partial
    .components(separatedBy:CharacterSet(charactersIn: "+0123456789").inverted)
    .joined(separator: "")
````

**Comment by kuyazee** [comment]
Does this issue still happen with the recent commits?
