### ISSUE TITLE
Space missing on USA/Canada phone number formatting

### ISSUE THREAD

**Issue by lureder** [marmelroy/PhoneNumberKit#231]
The phone number is missing a space between the 1 and the regional code.

Looks like this: 1(555) 555-5555.
Should be like this: 1 (555) 555-5555.

**Comment by hishma** [comment]
+1 

Using (2.6.0)

**Comment by kuyazee** [comment]
Does this still happen with the recent release?

**Comment by lureder** [comment]
Not sure, I’m not using it anymore.

**Comment by kuyazee** [comment]
Closing this issue, will reopen if we encountered again. Thank you @lureder
