### ISSUE TITLE
PhoneNumberType is always 'Fixed Line or Mobile'?

### ISSUE THREAD

**Issue by JosephPlondo** [marmelroy/PhoneNumberKit#233]
I have tested many numbers.  My cell phone which is a mobile return as Fixed Line or Mobile.  My home phone number returns the same.  My Google Voice number returns the same thing.  Am I missing something here?  I am looking for something that will detect accurately if it is a VOIP, a Mobile, etc...  Of course, unknown works if I set it to an invalid phone number - but this isn't what I need.

Any help would be much appreciated!

**Comment by Sam-Spencer** [comment]
Curious to hear if there's any additional documentation on this? From the source code it looks like this is just being checked using RegEx pattern matching, is that right?
