### ISSUE TITLE
PhoneNumberTextField format

### ISSUE THREAD

**Issue by ThuongVanBui** [marmelroy/PhoneNumberKit#236]
Currently, I want to format TextField, but I can not do it. Everyone can help me! Please!!!!

**Comment by guykogus** [comment]
Don't use a regular `UITextField`, use `PhoneNumberTextField`. If you're creating the text field in interface builder then you can set it in the editor on the right like this:
![screen shot 2018-11-19 at 12 17 01](https://user-images.githubusercontent.com/924764/48703765-0d73ae00-ebf5-11e8-99dc-503be0ba2c77.png)

**Comment by ThuongVanBui** [comment]
But I want to custom that PhoneNumberKit's format. How to do it? Can you help me? Thanks!

**Comment by guykogus** [comment]
What exactly are you trying to do? Can you give an example?

**Comment by ThuongVanBui** [comment]
Ex: I using PhoneNumberTextField default:  95 87 98 33 or 839 839 22
I want to custom to: 9687 7896
regionCode: SG

**Comment by ThuongVanBui** [comment]
Hi bro. I inited new PartialFormatter(phoneNumberKit: PhoneNumberKit(), defaultRegion: "SG", withPrefix: true), but PhoneNumberTextField not understand, not format by Region

**Comment by guykogus** [comment]
This prints out what you're looking for.
```Swift
let formatter = PartialFormatter(phoneNumberKit: PhoneNumberKit(), defaultRegion: "SG", withPrefix: true)
print(formatter.formatPartial("95 87 98 33"))
```

**Comment by ThuongVanBui** [comment]
yes, But in  PhoneNumberTextField not correct

**Comment by guykogus** [comment]
```Swift
let textField = PhoneNumberTextField()
textField.defaultRegion = "SG"
textField.text = "95 87 98 33"
print(textField.text ?? "") // "9587 9833"
```

**Comment by ThuongVanBui** [comment]
Yes, @guykogus. Thank you so much!
