### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by aaisataev** [marmelroy/PhoneNumberKit#24]
How to install it manually without cocoapods and etc?

**Comment by marmelroy** [comment]
Hey @aaisataev,

Basically: 
- Download the project and copy to your app's root directory.
- Open your app's xcodeproj
- Drag PhoneNumberKit's project file into your App's project file.
- Expand the products folder of PhoneNumberKit and you will see a PhoneNumberKit.framework file. 
- Look at your app's target and find "Embedded Binaries".
- Drag PhoneNumberKit.framework to embedded binaries. 

Hope this helps.
