### ISSUE TITLE
Failed to verify bitcode in PhoneNumberKit.framework/PhoneNumberKit:

### ISSUE THREAD

**Issue by BartMommens** [marmelroy/PhoneNumberKit#240]
Hey Guys,

Xcode updated itself to version 10 today ... and all of a sudden i can't compile my app anymore.

When archiving i get the following error:

Failed to verify bitcode in PhoneNumberKit.framework/PhoneNumberKit:
error: Cannot extract bundle from /var/folders/0p/sb0gk7b95hb370klftm09d1c0000gn/T/IDEDistributionOptionThinning.kr5/Payload/LMRA First.app/Frameworks/PhoneNumberKit.framework/PhoneNumberKit (i386)

I have no idea what's going on here :/ i've spend 3 hours looking for some kind of solution .. even disabled bitcode in build settings ... yet it still seems to do so ... does anyone have a solution ? i've updated the framework with carthage ... but still nothing :(

**Comment by kuyazee** [comment]
Xcode 10, and 11 are currently working fine, closing this issue
