### ISSUE TITLE
NetworkInfo error warning when parsing a phone number string

### ISSUE THREAD

**Issue by tealshift** [marmelroy/PhoneNumberKit#246]
`[NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x10f228680, domain=1, instance=1>`

I see this printed each and every time I use 
`phoneNumberKit.parse(phoneNumber)`

I don't know what else to say about this one. Googling it doesn't seem to return any relevant cases. Should I ignore this?

**Comment by tealshift** [comment]
Using the latest Xcode and swift 4.2

**Comment by roma6125** [comment]
Problem occurs in 
`public class func defaultRegionCode() -> String {
...
let networkInfo = CTTelephonyNetworkInfo()
...`

**Comment by bmonk** [comment]
`CoreTelephony` isn't supported in the iOS Simulator.

 I find that the line flagged above with `<--- GENERATES WARNING` logs

`NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated."`



Fix: change the `#if os(iOS)` to also exclude the simulator:

```
#if os(iOS) && !targetEnvironment(simulator)
```

**Comment by kuyazee** [comment]
Can you create a PR for it @bmonk?

**Comment by bmonk** [comment]
@kuyazee PR is up: #331.

**Comment by kuyazee** [comment]
> @kuyazee PR is up: #331.

Thank you
