### ISSUE TITLE
No PhoneNumberMetadata when using SPM

### ISSUE THREAD

**Issue by bennokress** [marmelroy/PhoneNumberKit#247]
SPM support was added in #179. When using it in my Vapor project, the contents of the UI and Resources folders are not included which leads to no available metadata. Sadly this makes the whole PhoneNumberKit useless right now.

I will look into it, but I'm fairly new to SPM, so someone else could possibly fix this faster (@Coledunsby by any chance?).

**Comment by bennokress** [comment]
Reading up on this I found [this story for SPM Evolution](https://bugs.swift.org/browse/SR-8260) where including a Resources folder is up for evaluation. It seems that using PhoneNumberKit with SPM is not possible then. I just wonder how @Coledunsby got it to work with his PR #179. Is there a workaround? I would love to use this in my Vapor project where no other Dependency Manager is available ...

**Comment by nichdu** [comment]
Are you using Vapor on macOS or Linux? In Linux there are quite some errors which make using PNK impossible at the moment (See #216). 
For the resources: One could include them in a Swift source file but this is a subpar solution. You could also try to save the Metadata at a hardcoded path (or maybe defined by an environment variable?).  I think we need to wait for Swift to provide a solution on this.

**Comment by bennokress** [comment]
I'm developing on macOS and using it on Linux (in Docker). I think you're right with the conclusion to wait for Swift … thanks for the suggestions, though.

**Comment by nichdu** [comment]
This is exactly our setup. Maybe if I have time in the next weeks I'll fix all the problems on Linux. This won't resolve the ressource problem though.

**Comment by travismmorgan** [comment]
For now I just copied the **PhoneNumberMetadata.json** to my app Bundle and override the initialization. 

`extension PhoneNumberKit {
    
    public override convenience init() {
        self.init(metadataCallback: PhoneNumberKit.bundleMetadataCallback)
    }
    
    public static func bundleMetadataCallback() throws -> Data? {
        guard let jsonPath = Bundle.main.path(forResource: "PhoneNumberMetadata", ofType: "json") else {
            throw PhoneNumberError.metadataNotFound
        }
        let data = try Data(contentsOf: URL(fileURLWithPath: jsonPath))
        return data
    }
    
}`

**Comment by mburumaxwell** [comment]
Still facing this issue. Is there a potential workaround other than changing back to using Pods?
