### ISSUE TITLE
Image not found error

### ISSUE THREAD

**Issue by aaisataev** [marmelroy/PhoneNumberKit#25]
Added source files manually, but see error log: 

dyld: Library not loaded: @rpath/PhoneNumberKit.framework/PhoneNumberKit
  Referenced from: /var/mobile/Containers/Bundle/Application/BB4879D5-ADAA-4B1A-9D2C-2318D7B78DCA/App.app/App
  Reason: image not found

**Comment by aaisataev** [comment]
forgot add to embedded binaries

**Comment by marmelroy** [comment]
:+1:
