### ISSUE TITLE
change country code color

### ISSUE THREAD

**Issue by menesh2** [marmelroy/PhoneNumberKit#250]
Do you have a built in way to change the country code color?

**Comment by joshuakcockrell** [comment]
@menesh2 What do you mean by country code color? Are you talking about the visual RGB color value? PhoneNumberKit doesn't handle rendering different parts of the number with different colors. Maybe you could use `phoneNumber.countryCode` to grab the country code yourself and then render it with whatever color you wanted. Would that solve this problem?
