### ISSUE TITLE
Extract country code and possible number.

### ISSUE THREAD

**Issue by ton252** [marmelroy/PhoneNumberKit#252]
Would you plan to add some function to extract country code from partitial filled phone number?

For example:
```
PhoneKit().extractCountryCode("+7999999")  // print +7
PhoneKit().extractCountryCode("+888999999")  // print +888
```

**Comment by mime29** [comment]
You can already do it through `PhoneNumber`
![image](https://user-images.githubusercontent.com/2211828/52830638-f1f54200-3114-11e9-9b80-b4838ca07a30.png)
