### ISSUE TITLE
Swift 5.0 (+ Swift 4.2) source compatibility. Xcode 10.2 beta 2 support

### ISSUE THREAD

**Issue by dmcgloin** [marmelroy/PhoneNumberKit#256]
There are a handful of warnings that could be fixed to support Swift 5 source compatibility while maintaining Swift 4.2 compatability.

One issue:

/PhoneNumber.swift:43:16: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'PhoneNumber' to 'Hashable' by implementing 'hash(into:)' instead

Useful Info on Hashable is here:

https://www.hackingwithswift.com/articles/115/swift-4-2-improves-hashable-with-a-new-hasher-struct

**Comment by florentmorin** [comment]
PR is here: https://github.com/marmelroy/PhoneNumberKit/pull/263

While PR is not validated, you can use for available [here](https://github.com/MAIF/PhoneNumberKit)

**Comment by kuyazee** [comment]
PR's merged, closing this issue now
