### ISSUE TITLE
Cannot modify PhoneNumberTextField delegate.

### ISSUE THREAD

**Issue by ciauri** [marmelroy/PhoneNumberKit#26]
I'm trying to capture UITextFieldDelegate events, and when I set the delegate in IB, the delegate methods are not called. Same thing happens when I set it in code.

It looks like your set method for the UITextFieldDelegate property continues to set the value to nil. When I performed this fix in my local repo, it solved my issue.

Replace
```
override public var delegate: UITextFieldDelegate? {
        get {
            return _delegate
        }
        set {
            self._delegate = delegate
        }
    }
```
with 
```
override public var delegate: UITextFieldDelegate? {
        get {
            return _delegate
        }
        set {
            self._delegate = newValue
        }
    }
```

Cheers!

**Comment by marmelroy** [comment]
Thanks @ciauri. Fixed with https://github.com/marmelroy/PhoneNumberKit/commit/c35409f5d46bb95a4178819a12d7713c7a5484c5

**Comment by nico75005** [comment]
My question might be a bit stupid but why when I install the later version with cocoapods, I don't get this commit?

**Comment by marmelroy** [comment]
Not stupid at all @nico75005 - it's not in the latest release yet. I was waiting to finish https://github.com/marmelroy/PhoneNumberKit/issues/32 but can actually do an intermediate release now.

**Comment by marmelroy** [comment]
Done.

**Comment by nico75005** [comment]
Thanks. Is it actually safe to do this? 
```
pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit'
```

**Comment by marmelroy** [comment]
It's living on the edge 😊 but in theory should be safe (every pull request has to pass the unit tests).

p.s. it will slow down your pod update times too.
