### ISSUE TITLE
is phoneNumber.toE164() method deprecated?

### ISSUE THREAD

**Issue by syvertsj** [marmelroy/PhoneNumberKit#262]
the documentation on cocoapods.org demonstrates the 'toE164() method call for the PhoneNumber type. 
This does not seem to be present in the latest release of PhoneNumberKit. 
Is there an alternative?

**Comment by nichdu** [comment]
Taken from the [Readme](https://github.com/marmelroy/PhoneNumberKit/blob/master/README.md):
`phoneNumberKit.format(phoneNumber, toType: .e164) // +61236618300`

**Comment by kuyazee** [comment]
Thank you @tjarksaul you are correct. Closing this issue now.
