### ISSUE TITLE
How can I add an inset to the text and placeholder in PhoneNumberTextField

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [marmelroy/PhoneNumberKit#264]
I'm using the `PhoneNumberTextField` but with a few additions such as a border, corner radius and a `UIButton` added to its `leftView`. The problem is the text is shown right up against the border.

<img width="355" alt="text" src="https://user-images.githubusercontent.com/2551877/53319345-4f00ad00-38f8-11e9-87e3-f44ce62580ee.png">

<img width="367" alt="no inset" src="https://user-images.githubusercontent.com/2551877/53319351-532cca80-38f8-11e9-86b4-77f59313b577.png">

So I want to add an inset to the text and the placeholder. I tried subclassing `PhoneNumberTextField` and adding the text inset capability like this.

```swift
@IBDesignable
class CNPhoneNumberTextField: PhoneNumberTextField {
    @IBInspectable var inset: CGFloat = 0
    
    override func textRect(forBounds bounds: CGRect) -> CGRect {
        return bounds.insetBy(dx: inset, dy: inset)
    }
    
    override func editingRect(forBounds bounds: CGRect) -> CGRect {
        return bounds.insetBy(dx: inset, dy: inset)
    }
    
    override func placeholderRect(forBounds bounds: CGRect) -> CGRect {
        return bounds.insetBy(dx: inset, dy: inset)
    }
}
```

The issue here is it doesn't take the `leftView` into account now.

<img width="357" alt="subclassed" src="https://user-images.githubusercontent.com/2551877/53319461-971fcf80-38f8-11e9-929e-f98b2433f096.png">

[Demo project](https://www.dropbox.com/s/mid7069shpl2iqw/PhoneText.zip?dl=0)

Is there any way to fix this?

**Comment by kuyazee** [comment]
What I can suggest is that you place your current leftView inside a containerView that has a margin on the right side. See illustration below for more details.

![Screen Shot 2019-10-09 at 10 18 19 PM](https://user-images.githubusercontent.com/17846698/66489908-ed85fb00-eae2-11e9-93a2-7c85973ead4d.png)

It's what I do on my projects
