### ISSUE TITLE
Getting com.apple.commcenter.coretelephony.xcp invalidated error

### ISSUE THREAD

**Issue by tlynchlaw** [marmelroy/PhoneNumberKit#266]
I'm a new swift developer.  I am using swift 4.2 and xcode 10.1.  I added PhoneNumberKit with cocoa pods.

I have a phoneNumberTextField set up and it is working well.  I can add numbers to the string to display in the textfield and it is formatting them properly.

But I see several errors when the viewcontroller that contains import PhoneNumberKit is first accessed.  Attached is the textfile with all the errors, but they all relate to "com.apple.commcenter.coretelephony.xpc was invalidated."

EDIT: I just noticed this happens only with the simulator.  On an actual device, I see a new error, that I haven't seen before and assume it is related to PhoneNumberKit: Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x281bdf360, domain=1, instance=1>

Is this a known error?  Should I be concerned about it?  I will be using telephony from the app to force an outbound call through the iphone's native phone app, and later using callKit for VoIP. 

Any help would be greatly appreciated.

[phoneNumberKit errors.txt](https://github.com/marmelroy/PhoneNumberKit/files/3012919/phoneNumberKit.errors.txt)

**Comment by basememara** [comment]
It's for the `CoreTelephony` stuff that's used to derive a device's current country code:

https://github.com/marmelroy/PhoneNumberKit/blob/8c3efc6f6169f805266f3db15c61e85697cdd576/PhoneNumberKit/PhoneNumberKit.swift#L156

That probably has a lot to do with the delays at start up. If you pass in your own country code, I don't think you'll see those console warnings.

**Comment by saroar** [comment]
dont get ur point how to fix it?

**Comment by basememara** [comment]
The prose function has an default parameter that uses the telephony framework to infer the locale. If you provide your own locale, it won’t have to call the telephony service:

https://github.com/marmelroy/PhoneNumberKit/blob/8c3efc6f6169f805266f3db15c61e85697cdd576/PhoneNumberKit/PhoneNumberKit.swift#L38

**Comment by saroar** [comment]
@basememara is it good idea to use `own region` how to get dynamically > own region thanks
