### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [marmelroy/PhoneNumberKit#272]
## Expected Results

No warning to convert PhoneNumberKit.framework to Swift 5

## Actual Results

Xcode created warnings to convert PhoneNumberKit.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by jlaws** [comment]
ping

**Comment by jlaws** [comment]
@marmelroy

**Comment by jlaws** [comment]
ping

**Comment by kuyazee** [comment]
#274

**Comment by vkolosovsky** [comment]
@marmelroy ping

**Comment by kuyazee** [comment]
PR's merged, closing this issue now
