### ISSUE TITLE
Issue with German numbers

### ISSUE THREAD

**Issue by sochalewski** [marmelroy/PhoneNumberKit#277]
I've noticed that there is some issue with German phone numbers.

Let's take `491709114421` as an example. This is valid mobile phone number with country code (`+49 170 9114421`), but it's also valid fixed line number without country code (then it would be `+49 491 709114421`).

Things go messy when trying to parse a number like this.

```swift
let number = "491709114421"
let phoneNumberKit = PhoneNumberKit()
let phoneNumber = try! phoneNumberKit.parse(number)
```

```
▿ PhoneNumber
  - numberString : "491709114421"
  - countryCode : 49
  - leadingZero : false
  - nationalNumber : 491709114421
  - numberExtension : nil
  - type : PhoneNumberKit.PhoneNumberType.fixedLine
  ▿ regionID : Optional<String>
    - some : "DE"
```

Then it's parsed as a fixed line number. Is there any way to enforce treating given phone numbers as a numbers with country code included?

PS This behavior occurs only when a device's region is set to Germany. When I change it to for example United Kingdom, the phone number is parsed as a mobile without double `49`.
```
▿ PhoneNumber
  - numberString : "+491709114479"
  - countryCode : 49
  - leadingZero : false
  - nationalNumber : 1709114479
  - numberExtension : nil
  - type : PhoneNumberKit.PhoneNumberType.mobile
  ▿ regionID : Optional<String>
    - some : "DE"
```

PPS Of course instead parsing `number` I can parse `"+\(number)"`, but not sure if that's the point.

**Comment by CristianoCastro** [comment]
I'm also having this issue: when using DE region, phone numbers without '+' sign are identified as DE fixedLine.

<img width="359" alt="Screenshot 2019-07-22 at 14 47 52" src="https://user-images.githubusercontent.com/6043612/61637661-ded03a80-ac8f-11e9-8476-f50c70897788.png">
<img width="338" alt="Screenshot 2019-07-22 at 14 48 09" src="https://user-images.githubusercontent.com/6043612/61637664-e1329480-ac8f-11e9-9de7-149acd2f437d.png">

**Comment by kuyazee** [comment]
The number metadata has been updated with the recent release.
