### ISSUE TITLE
Swift Compiler Warning: 'Hashable.hashValue' is deprecated as a protocol requirement.

### ISSUE THREAD

**Issue by DmytroYashchenko** [marmelroy/PhoneNumberKit#278]
Swift Compiler Warning : 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'PhoneNumber' to 'Hashable' by implementing 'hash(into:)' instead.

Warning in file "PhoneNumber.swift":
<img width="1421" alt="Снимок экрана 2019-05-24 в 11 42 41" src="https://user-images.githubusercontent.com/49062336/58314928-33cf0c00-7e19-11e9-8b19-b144cb5695ba.png">

I know that there is no swift 5 update. There were many complier warnings but i have fixed them. But i still cant deal with the last. 
Thanks for attention!

**Comment by kuyazee** [comment]
Fixed with #263
