### ISSUE TITLE
SPM on Xcode 11 support for UI

### ISSUE THREAD

**Issue by Rubenfer** [marmelroy/PhoneNumberKit#280]
Installing PhoneNumberKit via SPM on Xcode 11 (instead of Cocoapods) doesn't found PhoneNumberTextField because of Package.swift file excludes UI folder.

**Comment by ankitgogia** [comment]
Is SPM supported now?

**Comment by Rubenfer** [comment]
Yes, with Xcode 11 you can import dependencies from SPM.

**Comment by zocario** [comment]
I have the same issue, any news about this? @marmelroy Is it planned to merge https://github.com/marmelroy/PhoneNumberKit/pull/293 so we can use UI elements with SPM?

**Comment by kuyazee** [comment]
#239 has been merged.
