### ISSUE TITLE
The lib causes my app to stop archiving and returns over 100 errors about it not being updated to Swift 5.

### ISSUE THREAD

**Issue by mikeycoder123** [marmelroy/PhoneNumberKit#284]
I'm running the latest version of PhoneNumberKit and I'm running Xcode beta 4 (this could be an issue with the beta). My deployment target is iOS 12.0. When archiving it returns over 20 errors specifically at the PhoneNumberKit phase of archiving. This could be coincidental, but I suspect it is with PhoneNumberKit. I hope some investigation goes into this issue.

**Comment by travischapman** [comment]
You'll need to provide some more details. Which version of the framework are you using? Which xCode version are you running? What is your deployment target? etc.

**Comment by kuyazee** [comment]
This could also be a non issue now because we are now using Swift 5, see #263.

Please update us with more details, so we can check if this still needs to be fixed @mikeycoder123.
