### ISSUE TITLE
Arabic and Persian support

### ISSUE THREAD

**Issue by hamedaakhlaghi** [marmelroy/PhoneNumberKit#294]
Add Arabic and Persian support

**Comment by kuyazee** [comment]
I'm sorry, could you give us more details on what you mean by this? 

PhoneNumberKit only parses the metadata from google's [libphonenumber](https://github.com/google/libphonenumber) the only thing this library does is that it gives us an interface so we can use their metadata.

**Comment by karimhm** [comment]
> I'm sorry, could you give us more details on what you mean by this?
> 
> PhoneNumberKit only parses the metadata from google's [libphonenumber](https://github.com/google/libphonenumber) the only thing this library does is that it gives us an interface so we can use their metadata.

If you enter a number like: **٩٩٩١١١٩٩٩** which translate to: **999111999**, PhoneNumberKit won't accept it and wouldn't allow the user to type it.

There is different numeral system, [See Wikipedia](https://en.wikipedia.org/wiki/Hindu–Arabic_numeral_system). PhoneNumberKit should support them all.
