### ISSUE TITLE
Need support Swift 5.1

### ISSUE THREAD

**Issue by xxcombat** [marmelroy/PhoneNumberKit#297]
Hi!
Need support swift 5.1 (XCode 11,  Mac OS Catalina 10.15)
I added to Cartfile "github "marmelroy/PhoneNumberKit"
Version "3.0.0" installed.
I do not compile a project
`import PhoneNumberKit  - Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 `

**Comment by nidegen** [comment]
you just need to recompile it- not an issue of the repo:)

**Comment by kuyazee** [comment]
Thank you for the response @nidegen. @xxcombat he's correct you just need to recompile it, or just set the target's `Swift Language` version to 5.0.1 implicitly.

**Comment by xxcombat** [comment]
Thank you.
I deleted directory Carthage, after a run
`carthage update --platform iOS --no-use-binaries`
and it worked
