### ISSUE TITLE
PhoneNumberTextField with not clear plus sign

### ISSUE THREAD

**Issue by Banck** [marmelroy/PhoneNumberKit#298]
Hello!
Thanks for the great lib.
Is it possible to have a mandatory "+" symbol in textField? So for example .text == "", but when user type 1 .text will be == "+1".
Thanks

**Comment by kuyazee** [comment]
Sadly no, but you can add a custom implementation for that yourself. As for the reason why that is, Phone Numbers can start with numeric characters also.
