### ISSUE TITLE
Can't dissociate a possible phone number from a valid phone number

### ISSUE THREAD

**Issue by nrako** [marmelroy/PhoneNumberKit#30]
[libPhoneNumber](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) has a way to separate a possible phone `isPossibleNumber` number from a valid one `isValidNumber`:

<img width="612" alt="screen shot 2016-03-07 at 12 46 38" src="https://cloud.githubusercontent.com/assets/425397/13570294/e48dec76-e46d-11e5-8820-dac5517d9d60.png">

With PhoneNumberKit, this test fails:
```swift
    // Invalid brazilian number
    func testPossibleButInvalidNumber() {
        do {
            let phoneNumber = try PhoneNumber(rawNumber: "0765550055", region: "BR")
            phoneNumber.toE164()
            XCTFail()
        }
        catch {
            XCTAssert(true)
        }
    }
```

In PhoneNumberKit a parsed number is a "possible" number correct? Is it possible to dissociate a parsed (possible) number from a valid one? Since this use the same metadata than libPhoneNumber?

**Comment by marmelroy** [comment]
Hi @nrako,

In PhoneNumberKit, parsing and validating were merged into the same action. a PhoneNumber object is always a valid number.

What exactly are you trying to achieve though? If you want to format an invalid number, the PartialFormatter could help you...

**Comment by nrako** [comment]
Hi @marmelroy, okay but as per my screenshot from the test with [libPhoneNumber](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) I would expect the number `0765550055` with region `BR` to fail and not be parsed.

**Comment by marmelroy** [comment]
Ah okay. In that case there is indeed an issue here. What I suspect is that Google look at type UNKNOWN as invalid, whereas PhoneNumberKit doesn't.  Will investigate further tonight...

**Comment by nrako** [comment]
You are right it does:

https://github.com/iziz/libPhoneNumber-iOS/blob/f35561517fb4b199b561a24d33216dfe8f0df8c3/libPhoneNumber/NBPhoneNumberUtil.m#L2323

**Comment by nrako** [comment]
I was thinking of sending a PR, but I'm not sure that all `PhoneNumber` should be a valid number or valid number for a region.

I can see cases where I want the user to only be able to enter a valid phone number; e.g to receive a sms for validation, and optionally for a region specifically selected by the user. But there's cases where I just want to prevent dialling impossible/non-parsable number, but I'm fine to let the user try (and maybe fail) with an invalid number.

Moreover for performance reason it's probably best to just `parseMultiple` numbers without trying to validate them.

Maybe `PhoneNumber` should be considered as a "possible" number and have the `isValidNumber` and `isValidPhoneNumber:forRegion` methods? What do you think?

**Comment by marmelroy** [comment]
Hmm... in terms of validations, PhoneNumberKit's number parsing does everything libPhoneNumber does in isValidNumber except for checking whether type != .Unknown. The type test can be very expensive and we already validate against the main country format (for the type test, you basically regex match against every available number type). 

I'm leaning towards the ```Maybe PhoneNumber should be considered as a "possible" number and have the isValidNumber and isValidNumber:forRegion methods``` approach but want to think about this further.

**Comment by nrako** [comment]
@marmelroy :+1: let me know

**Comment by marmelroy** [comment]
I added an isValidNumber computer property on the PhoneNumber object. I'm still not 100% sure it is the right approach though...
