### ISSUE TITLE
SwiftUI view for PhoneNumberTextField

### ISSUE THREAD

**Issue by ankitgogia** [marmelroy/PhoneNumberKit#302]
I'm trying to use PhoneNumberKit with SwiftUI views so I can display the formatted number as the user types (using AsYouTypeFormatter). However, this doesn't work. Has anyone tried something with SwiftUI?

I have the following code that creates a SwiftUI view based on PhoneNumberTextField - 

```swift
struct PhoneNumberKitField: UIViewRepresentable {
    
    func makeCoordinator() -> PhoneNumberKitField.Coordinator {
        Coordinator(self)
    }
    
    func makeUIView(context: Context) -> PhoneNumberTextField {
        let phoneTextField = PhoneNumberTextField()
        phoneTextField.delegate = context.coordinator
        return phoneTextField
    }
    
    func updateUIView(_ uiView: PhoneNumberTextField, context: Context) {
        
    }
    
    class Coordinator: NSObject, UITextFieldDelegate {
        var delegate: PhoneNumberKitField
        
        init(_ delegate: PhoneNumberKitField) {
            self.delegate = delegate
        }
    }
}
```

**Comment by YanisAircall** [comment]
Hi @ankitgogia any news on this ?
Any help will be really appreciated :)

**Comment by jbnunn** [comment]
I got it working without a coordinator. First, add a `@Binding` var to your struct above,

    @Binding var phoneNumber: String

Then, in your `updateUIView` function,

    DispatchQueue.main.async {
        self.phoneNumber = uiView.text!
    }

In your SwiftUI view, add a @State var,

    @State private var phoneNumber = String()

and then when you build your view, pass that as an initializer,

    PhoneNumberTextFieldView(phoneNumber: $phoneNumber)

**Comment by nickm01** [comment]
@jbnunn can you share full code, couldn't get your solution to work

**Comment by jbnunn** [comment]
@nickm01 See if this helps. If you find a way to make it cleaner/better please let me know: https://gist.github.com/jbnunn/dab656b53f6e4ee2f53730f0b8daee64

**Comment by mroushdy** [comment]
This should be in your coordinator:

```
    final class Coordinator: NSObject, UITextFieldDelegate {
        
        let text: Binding<String>
        
        init(text: Binding<String>) {
            self.text = text
        }
        
        func phoneNumberField(_ phoneNumberField: PhoneNumberTextField, textDidChange searchText: String) {
            text.wrappedValue = searchText
        }
    }
```

**Comment by Insignite** [comment]
I was able to get it to work in SwiftUI with auto-update the binding variable. However, flag picker will not work but will still show proper flag.

https://github.com/Insignite/PhoneTextField/blob/master/README.md

**Comment by trothrock** [comment]
+1 to flag picker not working in SwiftUI. I have no issue when working in an iOS simulator and selecting it with my cursor, but on an actual device, I have to spam the button with taps 20-30 times before triggering the picker.

**Comment by nidegen** [comment]
Bugfix:

Change 
```
func updateUIView(_ view: PhoneNumberTextField, context: Context) {
    DispatchQueue.main.async {
        self.phoneNumber = view.text!
    }
}
```

to 
```
func updateUIView(_ view: PhoneNumberTextField, context: Context) {
    DispatchQueue.main.async {
      if self.phoneNumber != view.text {
        self.phoneNumber = view.text ?? ""
      }
    }
}
```

This will prevent a continuous update of the SwiftUI view and fix the unresponsive UI

**Comment by Insignite** [comment]
This method work for  SwiftUI that auto update binding variable when text change.

```swift
struct PhoneNumbeTextField: UIViewRepresentable {
    @Binding var phoneNumber: String
    private let textField = PhoneNumberTextField()
    
    func makeUIView(context: Context) -> PhoneNumberTextField {
        textField.addTarget(context.coordinator, action: #selector(Coordinator. onTextChange), for: .editingChanged)
        return textField
    }
    
    func updateUIView(_ uiView: PhoneNumberTextField, context: Context) {
    }
    
    func makeCoordinator() -> Coordinator {
        return Coordinator(self)
    }
    
    typealias UIViewType = PhoneNumberTextField
    
    class Coordinator:  NSObject, UITextFieldDelegate {
        var delegate: PhoneNumbeTextField
        
        init(_ delegate: PhoneNumbeTextField) {
            self.delegate = delegate
        }
        
        @objc func onTextChange(textField: UITextField) {
            self.delegate.phoneNumber = textField.text!
        }
    }
}
```

**Comment by AlexFine** [comment]
Hey all I was in a very similar situation – and worked w/ some friends to build an addition to PhoneNumberKit specifically for SwiftUI. 

You can use this package in SwiftUI as follows: 

```swift
struct ContentView: View {
    @State var text = ""

    var body: some View {
        iPhoneNumberField("Phone", text: $text)
    }
}
```

### [Github Here](https://github.com/MojtabaHs/iPhoneNumberField)

**Comment by theedov** [comment]
> I think this issue should be reopened and a plan should be set to add an official SwiftUI implementation for `PhoneNumberTextField` or at least an official `UIViewRepresentable` implementation that all consumers of this library can rely on.

@marmelroy thoughts ☝️?
