### ISSUE TITLE
There is an error validation the podspec file

### ISSUE THREAD

**Issue by hojideli** [marmelroy/PhoneNumberKit#304]
we want to use private podspec repository that we need to validate PhoneNumberKit.podspec file with the following command
`pod lib lint PhoneNumberKit.podspec --allow-warnings`

Unfortunately, it shows me the following errors

> - ERROR | [PhoneNumberKit/UIKit] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:13:32: error: use of undeclared type 'PhoneNumberKit'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:35:47: error: use of unresolved identifier 'PhoneNumberKit'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:71:52: error: use of undeclared type 'PartialFormatter'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:79:41: error: use of unresolved identifier 'PhoneNumberConstants'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:127:64: error: use of undeclared type 'PhoneNumberKit'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:137:48: error: use of undeclared type 'PhoneNumberKit'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:152:26: error: use of unresolved identifier 'PhoneNumberKit'
    - ERROR | [PhoneNumberKit/UIKit] xcodebuild:  PhoneNumberKit/PhoneNumberKit/UI/TextField.swift:165:26: error: use of unresolved identifier 'PhoneNumberKit'
[!] PhoneNumberKit did not pass validation, due to 9 errors.

**Comment by kuyazee** [comment]
Hello can you specify these details? It's not showing those error messages on the machines I'm working at.

- Your OS Version
- Your Xcode Version
- Your Cocoapods Version
- The version of PhoneNumberKit you are using

**Comment by hojatdelfan** [comment]
I cloned the latest version of the library and I'm validation that's no problem. There is a problem when I change the spec name.
> Pod::Spec.new do |s|
  s.name             = "PhoneNumberKit-Q"
  s.version          = "3.0.0"
  s.summary          = "Swift framework for working with phone numbers"

I've added some libraries to private podspec repository and I usually change their spec name and spec source and so far no problem.

- Your OS Version : macOSMojave version 10.14.6
- Your Xcode Version : Xcode 11
- Your Cocoapods Version : version 1.8.3

**Comment by kuyazee** [comment]
Sorry for the late response. PhoneNumberKit's podspec is using subspecs, you also need to change the name of your subspecs and your imports for it to work. I'm not sure if this will work but I've had problems also with subspecs before and this was how I fixed mine.
