### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by ZaurNNov** [marmelroy/PhoneNumberKit#306]
after update os and pods i catch error in PhoneNumber lib

```
MetadataParsing.swift -> 131-136 row
    func decodeBoolString(forKey key: KeyedDecodingContainer<K>.Key) -> Bool {
        guard let value: String = try? self.decode(String.self, forKey: key) else {
            return false
        }
        return Bool(value) ?? false
    }
+
MetadataParsing.swift -> 49
        mainCountryForCode = container.decodeBoolString(forKey: .mainCountryForCode)

+ other files
```

**Comment by kuyazee** [comment]
Please add more context to your question such as the ff:
- Operating System
- Xcode Version
- PhoneNumberKit Version
- Swift Version

As it is no one other than you is experiencing this.

**Comment by Goga-Barabadze** [comment]
I am experiencing a similar error. 

* iOS 13.1.3 on the iPhone Xs running in debug mode and optimisation for speed is on 
* Xcode: Version 11.2.1
* PhoneNumberKit Version: 3.0.0
* Swift 5.1

**Comment by Amarok666** [comment]
Hi
same error line 131
key	PhoneNumberKit.MetadataTerritory.CodingKeys	mainCountryForCode
- ios 13.4
- Xcode 11.4
- phonenumberkit 3.2.0
- swift 5.2
Installed with cocoapod

**Comment by vlondon** [comment]
The similar error here.
- Simulator: iPhone 11 Pro iOS 13.3
- macOS 10.14.6, Xcode 11.3.1
- PhoneNumberKit Version: 3.0
- Swift 5.1
