### ISSUE TITLE
Need to detect emergency number

### ISSUE THREAD

**Issue by nitinAtlogysiOS** [marmelroy/PhoneNumberKit#307]
need to find whether a given number is an emergency / local number for given country or something like equivalent to the android libPhoneNumber ? is this possible using PhoneNumberKit?

**Comment by kuyazee** [comment]
PhoneNumberKit only parses the data that is provided by Google's [libphonenumber](https://github.com/google/libphonenumber/). Currently we don't have a functionality that automatically checks this for you but the `MetadataTerritory` struct has a property called `emergency` that contains the emergency number format, and example number as properties which you could do a workaround for.

**Comment by NathaSuleSM** [comment]
Hi Is there any Update on This Issue.
I am facing the same Issue using pod PhoneNumberKit 3.3
