### ISSUE TITLE
Using with Country picker lib

### ISSUE THREAD

**Issue by zishanj** [marmelroy/PhoneNumberKit#308]
How can I use the `PhoneNumberTextField` with [CountryPickerView](https://github.com/kizitonwose/CountryPickerView) lib without typing country code in the text field for formatting and validation?

**Comment by kuyazee** [comment]
This is out of scope of this project.

**Comment by zishanj** [comment]
@kuyazee  Is it possible to use `PhoneNumberTextField` without typing country code in it? Like we can use some internal variable to set the country.

**Comment by kuyazee** [comment]
#309

**Comment by vdka** [comment]
I have actually built this functionality on top of #309 using PhoneNumberKit already, when #309 is merged I can make a PR for the Picker view if wanted?

![2019-10-29 11 33 29](https://user-images.githubusercontent.com/7651280/67730196-075e9200-fa40-11e9-9ec0-234565efe360.gif)

**Comment by zishanj** [comment]
Sure, that will be great. I am waiting for this from 1 week. :)

**Comment by zishanj** [comment]
Does this `DefaultPickerUI` have prefered country list section that will be displayed on top of the list? I can only see `current` which I think refer to the users location. `CountryPickerView` have this prefered country list feature.
![image](https://user-images.githubusercontent.com/1451292/67738919-4259c900-fa32-11e9-9b6a-fadee4680fcd.png)

**Comment by vdka** [comment]
@zishanj Yeah what I have written does have that, you can view the code I have written for it [here](https://github.com/vdka/PhoneNumberKit/blob/d9801cad1e01a4ead099dcdeca03411db9d235c2/PhoneNumberKit/UI/CountryCodePickerViewController.swift#L19) in the meantime.

**Comment by zishanj** [comment]
Thats great... `popularCountryCodes` will work I think and this built-in picker UI will be sufficient. I am waiting to test it after you merge this enhancement.

**Comment by zishanj** [comment]
@vdka is your master branch stable enough to use on production stage? I am on tight schedule to use it in my app.

**Comment by vdka** [comment]
That's for you to decide, it's where I am working to get the PR merged, so it is changing as requested, if you need the picker UI though that is on the `picker` branch, feel free to copy the code for it over though if that's easier for you

**Comment by zishanj** [comment]
@vdka when you are going to open another PR for this feature?
