### ISSUE TITLE
Region code for +44

### ISSUE THREAD

**Issue by andrey-lisovskiy** [marmelroy/PhoneNumberKit#315]
Hi, I am trying to detect country code from phone number.

```
do {
         let phoneNumber: PhoneNumber = try phoneNumberKit.parse(info.phone)
         if let country = phoneNumberKit.getRegionCode(of: phoneNumber) {
                  countryPickerView.setCountryByCode(country)
        }
}
catch {
         DebugLog("PhoneNumberKit parser error")
}
```

It works good, but the one problem I've detected that it returns **GG** (Guernsey) instead **GB** (United Kingdom).

Is it possible to detect **GB** for **+44** code?

**Comment by marmelroy** [comment]
Hi @andrey-lisovskiy - sure. Instead of using getRegionCode, you should sue:
```if let country = phoneNumberKit.mainCountry(forCode: phoneNumber.countryCode)```

**Comment by marmelroy** [comment]
getRegionCode returns the first country that matches, mainCountry returns the main country

**Comment by andrey-lisovskiy** [comment]
Hi @marmelroy, thanks, it works!
