### ISSUE TITLE
Allow to separate a PhoneNumber's country prefix from the rest

### ISSUE THREAD

**Issue by AliSoftware** [marmelroy/PhoneNumberKit#32]
It would be cool to be able to separate a PhoneNumber's intl prefix from the rest of the phone number, e.g. for a french phone number, `"0612345678"` would give the tuple `("+33", "612345678")`

This would have multiple applications and possibilities, one of them being to allow the user to select a country in one way, the UI then displaying the selected intl prefix, and let the user enter the rest of the phone number in a TextField then.

### Application for `PhoneNumberTextField`

One UI we want to implement is adding a `leftView` to the `PhoneNumberTextField` containing an `UIButton`. On tap, this will display a `UIPickerView` to select the country, and upon selecting one will display e.g. `🇫🇷 (+33)` in the button's title.
Then the `PhoneNumberTextField` should be able to format the reminder of the phone number taking that fixed country prefix into account

### Application for `UILabel`

In another place in our UI, we need to simply _display_ the phone number, but we may still need to split it  for display and layout purposes in two separate labels (e.g. one label in gray text containing the prefix "+33" and another label next to it in black containing the rest)

So this request of being able to split the PhoneNumber is not limited to `PhoneNumberTextField`, but should also be made accessible for other purposes and customization as well (maybe make `func adjustedNationalNumber()` public instead of private to solve that?)

**Comment by sentiasa** [comment]
Your approach (having `UIPickerView` on the left of `PhoneNumberTextField`). If you can achieve what you are trying, I'd be grateful to read a mini-walkthrough from you. That would be amazing if you can write it here, below..

**Comment by marmelroy** [comment]
@sentiasa, @AliSoftware's UI approach for phone number entry is quite common and something PhoneNumberKit should support out-of-the-box.

Some modifications to PhoneNumberTextField and the ParialFormatter are necessary to allow it to do partial formatting for international dialling with a locked country region. 

I'm hoping to push the modifications and an example app implementing this pattern next week.

**Comment by marmelroy** [comment]
Re the UILabel application -  I just pushed an update to the formatter that allows you to format parsed phone numbers while excluding the prefix: 
https://github.com/marmelroy/PhoneNumberKit/commit/0742c0d946a9c44903e679fcedc2ec2ed9c73659

So for example:
```
phoneNumber.toInternational(false) // "6 89 55 55 55"
phoneNumber.toE164(false) // "689555555"
```

**Comment by sentiasa** [comment]
@marmelroy That would be interesting to see an example app on using @AliSoftware 's UIPicker & flags approach

**Comment by marmelroy** [comment]
Resolved by https://github.com/marmelroy/PhoneNumberKit/commit/40ff2f4b1377f2d59497df53dca792841125d4ba

An example project will be added before this is packaged in a release... 

Basically, I added a withPrefix optional Bool on PhoneNumberTextField that works as expected.

**Comment by sentiasa** [comment]
@marmelroy Please drop here a message too when the demo get added. Seeing flags with PhoneNumberKit would be very interesting to see.. Thanks..
