### ISSUE TITLE
pod update issue

### ISSUE THREAD

**Issue by sebros80** [marmelroy/PhoneNumberKit#321]
I can'n update my Pods with following issue:

- `PhoneNumberKit-library` does not specify a Swift version and none of the targets (`Pods`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Chears

**Comment by kuyazee** [comment]
Hello it's actually specified in the `Podfile`

```
  s.pod_target_xcconfig = { 'SWIFT_VERSION' => '5.0' }
  s.swift_version = '5.0'
```

Please tell me if I'm missing something here so we can fix it.

**Comment by sebros80** [comment]
Hello,
it works for me now. Perfect.

Chears
