### ISSUE TITLE
Issues with region and `parse` method

### ISSUE THREAD

**Issue by isupremedyou** [marmelroy/PhoneNumberKit#323]
I am running into an issue and need some help understanding how the library works.

I have a user in Canada so `defaultRegionCode()` is returning "CA". The phone number I am trying to parse is `+19725551234`. However it is throwing an error that it is an invalid number.

The area code is a Texas phone number. I am primarily using this library to validate that a number is a valid phone number. Am I using the library incorrectly?

FWIW, you can go here with the number I have provided and set the `Default Country` to "CA" and it is able to successfully parse the number and identify that it does not match the specified region (so it can still validate the number, but it also knows it is not a Canadian number).
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by isupremedyou** [comment]
More info:
`+19725551234` parsing this number fails when the region is set to `UK` or `CA`, but it didn't fail when I tested `US`, `IE`, `AU`, `DE`. 

It is throwing an error because it fails this check `parser.isNumberMatchingDesc(nationalNumber, numberDesc: generalNumberDesc) == false)`:
https://github.com/marmelroy/PhoneNumberKit/blob/b2da36c06405a46c255cf2ce120ce69fa626e2e9/PhoneNumberKit/ParseManager.swift#L75

**Comment by kuyazee** [comment]
Hello, is the number you're using a new number format?

**Comment by isupremedyou** [comment]
@kuyazee I don't think it is, I finally tracked down this bug for a user and they had been complaining about it for months. I'll try updating the metadata in my project though and see if that fixes it.

**Comment by beckychristensen** [comment]
Hi, I also have a user reporting this issue in Canada, and I've verified it both with the number they provided (`+1979*******`) and my own Texas phone number (`+1972*******`). My Texas number is 20 years old, so it's not a new format. The numbers pass validation if the region is set to `US` or `FR` for example, but not `CA`. It fails at the same line in `ParseManager` mentioned above.

**Comment by omidgolparvar** [comment]
Hi, I also have this issue with region "CA" for Canada. 😕

**Comment by yousifa** [comment]
We're also having this issue and able to replicate with other area codes (970, 971, 972, 973, 974)

**Comment by yousifa** [comment]
The problem here is that any region that is non-US, but has a country code of '+1' will fail at looking up some US numbers that match for numbers in other countries. The workaround for this is to set the default region to US for all '+1' country code regions.

`var phoneNumber: PhoneNumber? {
		do {
			let tempTextField = PhoneNumberTextField()
			var currentRegion = tempTextField.defaultRegion
			if currentRegion == "CA" {
				currentRegion = "US"
			}
			let phone = try PhoneNumberKit().parse(self, withRegion: currentRegion, ignoreType: false)
			return phone
		} catch {
			print("Error", error.localizedDescription)
			return nil
		}
	}`
