### ISSUE TITLE
Textfield with custom inputView

### ISSUE THREAD

**Issue by kiiskristo** [marmelroy/PhoneNumberKit#336]
Hi,
I'm using PhoneNumberTextField with my custom inputView, i add and remove text from it with insertText() and removeBackwards() methods and formatting is not happening. According to apple documentation insertText and removeBackwards should call textfield delegate methods.
Is there any workaround or i'm missing something?

**Comment by xaphod** [comment]
I have this issue also, wondering how you fixed it.

**Comment by kiiskristo** [comment]
@xaphod i ended up creating my own implementation

**Comment by xaphod** [comment]
OK thanks. I was going to fork PhoneNumberKit but I ended up going down a path like this: where i'm going to call insertText() or removeBackwards(), I check if I can cast the object to UITextFieldDelegate. If so I rewrite the call to use shouldChangeCharacters, like this:

```
        if let textfield = self.target as? UITextField, let textFieldDelegate = self.target as? UITextFieldDelegate {
            var range = NSRange.init()
            range.location = textfield.text?.count ?? 0
            range.length = 0
            if textFieldDelegate.textField?(textfield, shouldChangeCharactersIn: range, replacementString: "\(sender.digit)") == true {
                UIDevice.current.playInputClick()
                target?.insertText("\(sender.digit)")
            }
        } else {
            UIDevice.current.playInputClick()
            target?.insertText("\(sender.digit)")
        }

```
