### ISSUE TITLE
Memory consumption is higher than it needs to be

### ISSUE THREAD

**Issue by bmwalters** [marmelroy/PhoneNumberKit#337]
## Overview
The file `PhoneNumberMetadata.json` is 333KB. I would thus consider this a reasonable amount of memory for `PhoneNumberKit` to consume when loaded into memory. Instead, instantiating a `PhoneNumberKit` object consumes 2MB of memory. This can be a problem in resource-constrained environments such as app extensions.

## How to reproduce
1. Run the PhoneBook sample app in a release build. Observe the memory usage the Xcode memory gauge shows at rest.
2. Comment out the line that instantiates `PhoneNumberKit` in `ViewController.swift`, fix errors, and run again.
3. Observe that the memory usage has decreased by ~2MB.

I tried using the [memory debugging command line tools](https://developer.apple.com/videos/play/wwdc2018/416/) to get better info without success.

## Possible cause
It could be that the `MetadataTerritory` structs within `MetadataManager` are copied more than is needed.

An experiment that supports this is [this experimental patch](https://github.com/bmwalters/PhoneNumberKit/commit/0f16ee238fa3b0f8eee39c6b6158d9c2fa178813), which changes `MetadataManager` to refer to territories within the main territories array by index instead of including the struct in the hash tables.

With this patch, following the above steps shows only a ~1MB increase in memory usage instead of ~2MB.

## Possible solutions
- Optimize MetadataManager as in the above patch.
- Code generation solution (e.g. [Swiftgen](https://github.com/SwiftGen/SwiftGen)) that processes `PhoneNumberMetadata.json` into a Swift source file that is compiled along with the project, replacing the runtime JSON loading code in `MetadataManager`. This would likely also help with start-up time.

**Comment by kuyazee** [comment]
> It could be that the MetadataTerritory structs within MetadataManager are copied more than is needed.

What if we changed the `MetadataTerritory` to a class so memory references will be used instead. Everything inside it is immutable anyway maybe that can also work

**Comment by deepesh-vasthimal-cko** [comment]
Hi All Is this issue fixed ?. Any update on this would really help.

**Comment by bguidolim** [comment]
Hi
