### ISSUE TITLE
Requesting a new GitHub Release

### ISSUE THREAD

**Issue by bmonk** [marmelroy/PhoneNumberKit#338]
Not sure what the release schedule is, but requesting a new dot-release as soon as it makes sense, because there've been some useful changes merged since v3.1.0 of Nov 16/19. 

This would be helpful here because we need several recent updates, but (because reasons) also need to point our Cartfile to a specific version.

Best regards.

**Comment by kuyazee** [comment]
Hello @bmonk I'm actually preparing one but I was busy last night, I will release one when I get home tonight

**Comment by kuyazee** [comment]
Sorry for the late revert, 3.2.0 is now released.
