### ISSUE TITLE
PhoneNumberTextField defaultRegion KZ issue

### ISSUE THREAD

**Issue by Banck** [marmelroy/PhoneNumberKit#342]
Hello!
For defaultRegion "KZ" "currentRegion" is not KZ, it's RU.
```
    func updateMetadataForDefaultRegion() {
        guard let metadataManager = metadataManager else { return }
        if let regionMetadata = metadataManager.territoriesByCountry[defaultRegion] {
            self.defaultMetadata = metadataManager.mainTerritory(forCode: regionMetadata.countryCode)
        } else {
            self.defaultMetadata = nil
        }
        self.currentMetadata = self.defaultMetadata
    }
```
_regionMetadata.countryCode_ is KZ
In this func `metadataManager.mainTerritory(forCode: regionMetadata.countryCode)` returns metadata for RU, because KZ and RU has the same countryCode - 7.

Please check it.

**Comment by MaxZheleznyy** [comment]
Hi @kuyazee 👋 

Can you check attached PR, please?

**Comment by MaxZheleznyy** [comment]
Hi @kuyazee 👋 

It looks like a travis check has failed because of my changes. I do not see a good way how to get round this without changing the check itself. Can you help, please?

**Comment by amarunko** [comment]
Any updates?

**Comment by ARGAMX** [comment]
I have the same problem with KZ region. Any updates?

**Comment by segrey-profi** [comment]
UP
