### ISSUE TITLE
Is there a way to change the navigationBar’s color and navigationItem title?

### ISSUE THREAD

**Issue by eddy93** [marmelroy/PhoneNumberKit#346]
The whole app has a unique theme, the countryCodeViewController looks out of theme I need to be able to customize its navigationBar and navigationItem.

**Comment by igibadullin** [comment]
Hello Eddy. If you're using navigationController, then in viewWillDisappear you can get countryCodeViewController and change it like this:

```
if let countryPickerVC = self.navigationController?.viewControllers.last as? CountryCodePickerViewController {
            countryPickerVC.navigationController?.navigationBar.barTintColor = .white
            countryPickerVC.navigationItem.title = "Some text"
}
```
