### ISSUE TITLE
Localisation of "Choose your country" and "CURRENT" ?

### ISSUE THREAD

**Issue by IVANKRUPSKI** [marmelroy/PhoneNumberKit#348]
Hello!

Good package.

All the country names are natively localised by iOS, though I am struggling to find how can I localise the title "Choose your country" in the navigationBar and sectionHeade "CURRENT" in the table.

![image](https://user-images.githubusercontent.com/16180201/75091255-905b8500-556b-11ea-92d7-63657b1ec879.png)

Could you please advise how can I do this?

Many thanks in advance.

**Comment by antonselyanin** [comment]
Hello Ivan. There is this PR #344
You can wait until it is merged, or make a fork and apply the patch.

**Comment by IVANKRUPSKI** [comment]
Unfortunately, we can not make via fork.
Thus, looking forward to the merger.

**Comment by kuyazee** [comment]
#344 merged will make a new release soon
