### ISSUE TITLE
Manitoba (Canada) area code overlay (431) conflict with +43 Austria

### ISSUE THREAD

**Issue by jessewu14** [marmelroy/PhoneNumberKit#349]
Hi,

When entering a 431 area code number with US/CA +1 country code selected, it will be incorrectly detected as an Austrian number with +43 country code.

Relevant code:
PhoneNumberKit.swift:

```
public func parse(_ numberString: String, withRegion region: String = PhoneNumberKit.defaultRegionCode(), ignoreType: Bool = false) throws -> PhoneNumber {
        var numberStringWithPlus = numberString

        do {
            return try self.parseManager.parse(numberString, withRegion: region, ignoreType: ignoreType)
        } catch {
            if numberStringWithPlus.first != "+" {
                numberStringWithPlus = "+" + numberStringWithPlus
            }
        }

        return try self.parseManager.parse(numberStringWithPlus, withRegion: region, ignoreType: ignoreType)
    }
```

**Comment by MaxZheleznyy** [comment]
Sorry, can't reproduce (check my screencast - https://www.dropbox.com/transfer/AAAAANKSxy2hwAksUEXjAWsPTutGD-mBKL9YHNvnLYJkz8AHka5QcDw )

Can you provide a video with the problem?

**Comment by jessewu14** [comment]
Hi,

Thank you for the response, attached is a video showing the problem.

Seems like the issue is not with phone number recognition, but with partial phone number parsing as the user enters their phone number. Despite selecting the appropriate country prefix, the number is detected as a valid foreign phone number, and is reformatted to display as such (in this case, the reformatted phone number has an implicit country code of 43 - Austria)

[Screen Recording 2020-03-23 at 9.12.14 AM.mov.zip](https://github.com/marmelroy/PhoneNumberKit/files/4370555/Screen.Recording.2020-03-23.at.9.12.14.AM.mov.zip)

**Comment by MaxZheleznyy** [comment]
Can you check your implementation and share it here, please? It looks like a tricky field customization could cause that. 

For example, in the example project (this one - https://github.com/marmelroy/PhoneNumberKit/tree/master/examples/AsYouType ) I do not have this problem (see attached screencast below)

[1.mov.zip](https://github.com/marmelroy/PhoneNumberKit/files/4378033/1.mov.zip)

**Comment by jessewu14** [comment]
Here is the implementation of my text field validation:
`let rawPhoneNumber = self.phoneField!.text!.stringByIncludingOnlyCharacters("0123456789")
                
                do
                {
                    let phoneNumberKit = PhoneNumberKit()
                    
                    let phoneNumber = try phoneNumberKit.parse(rawPhoneNumber, withRegion: self.selectedCountryForPhone.countryCode)
                    return true
                }
                catch
                {
                    return false
                }`

Breakpoint Debugging information:
**When user types in 431210**
(lldb) po rawPhoneNumber
"431210"
(lldb) po self.selectedCountryForPhone
▿ Optional<Country>
  ▿ some : Canada (+1)
--> catch block entered

**When user types in 4312105**
(lldb) po rawPhoneNumber
"4312105"
--> successful parse, phoneNumber returned
(lldb) po phoneNumber
▿ PhoneNumber
  - numberString : "+4312105"
  - countryCode : 43
  - leadingZero : false
  - nationalNumber : 12105
  - numberExtension : nil
  - type : [].PhoneNumberType.fixedLine
  ▿ regionID : Optional<String>
    - some : "AT"

Witness that a '+' is prepended due to the code in my original post, which causes the phone number to be detected as a foreign number.
