### ISSUE TITLE
Partial Formatter not parsing correctly numbers from Mexico Region

### ISSUE THREAD

**Issue by ecristerna** [marmelroy/PhoneNumberKit#35]
When device is set to Mexico Region, Partial Formatter is not placing parenthesis to the phone number.

This is how is doing it:

<img width="314" alt="screen shot 2016-03-17 at 7 12 24 pm" src="https://cloud.githubusercontent.com/assets/3680271/13865749/51d54ba4-ec74-11e5-944f-4ae8e964db43.png">

This is how iOS Contacts App does it:

<img width="308" alt="screen shot 2016-03-17 at 7 12 40 pm" src="https://cloud.githubusercontent.com/assets/3680271/13865765/7d411958-ec74-11e5-8e9c-4a8278f1ecfd.png">

**Comment by marmelroy** [comment]
Thanks @ecristerna! Great find. 

Unfortunately, there's not a lot we can do about it. 

PhoneNumberKit uses the metadata from Google's libPhoneNumber project for the web and Android (considered the best in the industry) and it's Google's metadata that misses the parenthesis.
 
I've attached a screenshot of the way Google formats your number. To test the metadata with other numbers, you can try Google's service on the web directly on
https://libphonenumber.appspot.com

<img width="443" alt="screen shot 2016-03-18 at 06 52 20" src="https://cloud.githubusercontent.com/assets/889949/13870718/11ee6d06-ecd6-11e5-80d3-828aba889759.png">
