### ISSUE TITLE
Cannot compile the project

### ISSUE THREAD

**Issue by castor55** [marmelroy/PhoneNumberKit#350]
I see "Header 'PhoneNumberKit-Swift.h' not found" issue while building the project after integrating this library.

![Screen Shot 2020-02-28 at 10 05 51 AM](https://user-images.githubusercontent.com/15838658/75526500-326ae980-5a12-11ea-900e-07438f5da3b8.png)
![Screen Shot 2020-02-28 at 10 07 17 AM](https://user-images.githubusercontent.com/15838658/75526507-3565da00-5a12-11ea-9f41-94e0f37a7ed1.png)

Xcode version is 10.2.1 and the installed library version is 3.2.0.

I need your help!

**Comment by castor55** [comment]
@marmelroy Could you check this issue?

**Comment by kuyazee** [comment]
@castor55 can you add more details.
- How are you installing the library?
- Have you tried using an updated version of Xcode?
- Have you tried using an older version of the library since you're using an older version of Xcode?

**Comment by castor55** [comment]
- How are you installing the library?
I used CocoaPod.

- Have you tried using an updated version of Xcode?
Nope. Because of the issue on my side, I have to use the current Xcode version.

- Have you tried using an older version of the library since you're using an older version of Xcode?
No. I just added`pod 'PhoneNumberKit', '~> 3.1'` in my project pod file. Which version is suitable do you think?
