### ISSUE TITLE
Get phone number with country prefix

### ISSUE THREAD

**Issue by bmetitiri** [marmelroy/PhoneNumberKit#351]
Is there a way to get the phone number string from the PhoneNumberTextField in such a way that it always has the prefix for the country in the string? Or is there a way to get the assumed prefix if the user did not put one? I kind of expected the `withPrefix` option to make the field always have a prefix, but that does not seem to be the behavior.

**Comment by kuyazee** [comment]
You could access the `phoneNumber` property of `PhoneNumberTextField` and from there  you may get the string format you need.

```
phoneNumberKit.format(phoneNumber, toType: .e164) // +61236618300
phoneNumberKit.format(phoneNumber, toType: .international) // +61 2 3661 8300
phoneNumberKit.format(phoneNumber, toType: .national) // (02) 3661 8300
```
