### ISSUE TITLE
How to set the current Region dynamically?

### ISSUE THREAD

**Issue by voyager163** [marmelroy/PhoneNumberKit#367]
Hi,

How can I set the region for the user based on the picker he choose?

*I am using my own picker selection.

Thanks for the help

**Comment by JoeFerrucci** [comment]
How do you update the currentRegion dynamically?

**Comment by voyager163** [comment]
Hi Joe,

I managed to do it. Below is my codes. Please let me know if you need additional codes. I can share my file.

    func fetchCurrentRegion()
    {
        let tempRegion = phoneTB.currentRegion
        
        let filteredResult = searchCountryIndex(countryISOCode: tempRegion, countriesArray: countries)

        picker.selectRow(filteredResult!, inComponent: 0, animated: true)
        
    }

**Comment by JoeFerrucci** [comment]
Thanks for that, but I needed to update the `PhoneNumberTextField`'s region, which was difficult because `phoneTextField.currentRegion` is read-only. However, it looks like its easy to do via the `phoneTextField.partialFormatter`

**Comment by samdogg7** [comment]
@JoeFerrucci thank you, saved me a lot of time pointing me to partialFormatter 👍 

It would be nice if currentRegion settable for the use of custom pickers. In my case I am looking to limit the number of countries the user can select. I am using the PhoneNumberTextField, without prefix so the user does not have ability to switch country code via keyboard. Guess I will update using partialFormatter.
