### ISSUE TITLE
Phone number kit crashes

### ISSUE THREAD

**Issue by nbnitin** [marmelroy/PhoneNumberKit#369]
PhoneNumberKit was compiled with optimization - stepping may behave oddly; variables may not be available.

Give bad access in below function in Regex Manager
// MARK: Regular expression

    func regexWithPattern(_ pattern: String) throws -> NSRegularExpression {
        if let regex = regularExpresionPool[pattern] {

**Comment by WyattMufson** [comment]
I have also run into this issue

**Comment by WyattMufson** [comment]
@marmelroy any idea how to fix this. It consistently crashes here.

**Comment by nbnitin** [comment]
@WyattMufson did you find any solution for the issue ?

@marmelroy please suggest how to fix this issue ?

**Comment by nbnitin** [comment]
https://github.com/marmelroy/PhoneNumberKit/pull/194/files.

Update the pod issue seems to be fixed, closing for now.

**Comment by WyattMufson** [comment]
@nbnitin it looks like you're correct and that is the fix
