### ISSUE TITLE
0.6.4 is not compiling anymore

### ISSUE THREAD

**Issue by benyboariu** [marmelroy/PhoneNumberKit#37]
In ParseOperations.swift line 199 now I see "associatedtype" instead of "typealias" which was before, and now it's not compiling anymore. If I do "pod install", project won't run unless I manually change back to typealias.

**Comment by marmelroy** [comment]
Hi @benyboariu,

This is a deliberate change. "typealias" is deprecated in Swift 2.2 and should be replaced by "associatedtype". See: https://github.com/apple/swift-evolution/blob/master/proposals/0011-replace-typealias-associated.md

Are you using Xcode 7.3 (the newest version released this week)?

**Comment by marmelroy** [comment]
Closing for now...
