### ISSUE TITLE
Show country picker in Swift UI

### ISSUE THREAD

**Issue by mroushdy** [marmelroy/PhoneNumberKit#371]
Does anyone have guidance on how to show the country picker in Swift UI?

**Comment by peteryin21** [comment]
@mroushdy When you create the PhoneNumberTextField in your UIViewRepresentable wrapper, simply set the `withDefaultPickerUI` attribute to `true`
```swift
struct PhoneNumberTextFieldView: UIViewRepresentable {
    public let textField = PhoneNumberTextField()
    
    func makeUIView(context: Context) -> PhoneNumberTextField {
        textField.withDefaultPickerUI = true
        // other stuff
        return textField
    }
    
    func updateUIView(_ view: PhoneNumberTextField, context: Context) {\

    }
}
```

**Comment by dustfire** [comment]
This is problematic by the way, when you Select Canada, flag stays still USA.. Something is up.

**Comment by AlexFine** [comment]
Another approach is to use the SwiftUI package wrapper, [iPhoneNumberField](https://github.com/MojtabaHs/iPhoneNumberField). [Disclosure I helped to develop this package]. 

You could then display flags, and make the country picker selectable with:

```swift
import SwiftUI
import iPhoneNumberField

struct ContentView: View {
    @State var text = ""

    var body: some View {
        iPhoneNumberField(text: $text)
            .flagHidden(false)
            .flagSelectable(true)
    }
}
```

Hope this helps!
