### ISSUE TITLE
autofill phone number

### ISSUE THREAD

**Issue by AnHoncharenko** [marmelroy/PhoneNumberKit#376]
How can I give the user the opportunity to choose their phone number?

there is no such offer as standard
![IMG_3032](https://user-images.githubusercontent.com/45729211/83623199-b1376b80-a599-11ea-9a3a-f681cc2ed2b6.PNG)

if I do:
**phoneNumberTextField.textContentType = .telephoneNumber**
**phoneNumberTextField.keyboardType = .numbersAndPunctuation**
![IMG_3033](https://user-images.githubusercontent.com/45729211/83623355-e5129100-a599-11ea-96d6-6155884b72bf.PNG)

**Comment by AlessandroMulloni** [comment]
Probably related to https://github.com/marmelroy/PhoneNumberKit/pull/513
