### ISSUE TITLE
Some Country Codes are wrong

### ISSUE THREAD

**Issue by panncherry** [marmelroy/PhoneNumberKit#377]
I installed the framework via Carthage.

Some country codes are not showing correctly. For example, I choose the British Virgin Islands, it shows the country code +1 and it should be +1284 according to Google.

And also some of the flags are not updating in my project(use Carthage) while the sample project (use pod) is working fine for the flags. For example, I choose the Bahamas and it shows USA flag.

**Comment by BenderNK** [comment]
The same goes for Canada. You choose Canadian country code (which is also +1 like US) but the text field still shows US flag.

**Comment by hiteshinfostride** [comment]
There are a lot of countries with these exceptions. The PartialFormatter also does not work correctly for all these country codes - "AS","AI","AG","BS","BB","BM","KY","DM","GD","GU","MS","MP","KN","LC","VC","SX","TT","VG","VI".
One thing common in all these countries is that its country code starts with +1.

**Comment by 4taras4** [comment]
fixed here https://github.com/marmelroy/PhoneNumberKit/pull/600 I have the same issue
