### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mcrakhman** [marmelroy/PhoneNumberKit#38]
Hi!

I used you library to format phone numbers entered by user. And though I liked PhoneNumberKit a lot, I discovered certain memory leaks. 

Please note that I updated the library to version 0.6.4 via cocoapods, just so you know that I am using the up-to-date version.  

It seems both of the following lines cause memory leaks (thus if I delete both of them the leaks go away). Also `PhoneNumber (rawNumber:)` was tested in different apps with the same leaks. 

```Swift
do {
       _ = try PhoneNumber (rawNumber: phone!)
}
catch {
      isValidNumber = false
}
```
And this one:

```Swift
let formattedString = PartialFormatter ().formatPartial (cutString)
```
`cutString` is a string starting with `+` and ending with numbers.

Below see instruments' screenshots.

<img width="1280" alt="instruments - 1" src="https://cloud.githubusercontent.com/assets/16068868/13996941/3a1ce434-f149-11e5-9947-20b916ef5e29.png">
<img width="1280" alt="instruments - 2" src="https://cloud.githubusercontent.com/assets/16068868/13996949/43c221ac-f149-11e5-932a-bf922a89ff88.png">

**Comment by marmelroy** [comment]
Thanks @mcrakhman. Looks suspicious. I will investigate further this evening.

**Comment by marmelroy** [comment]
After some investigation - PhoneNumberKit keeps the parsed metadata in memory and a memory leak can, under certain circumstances, happen. 

I've begun work on a significant change to PhoneNumberKit that will be a lot more explicit about ownership and will resolve these issues. It will also introduce some breaking changes to the API. 

That work is on the https://github.com/marmelroy/PhoneNumberKit/tree/dev branch.

**Comment by marmelroy** [comment]
Good news!

I was able to resolve the memory leak issues without an API change. Bundling all the changes in release 0.7. 

Thanks again for reporting these @mcrakhman.

**Comment by mcrakhman** [comment]
Thank you very much! Will update and try.
