### ISSUE TITLE
Canadian Area Code not valid

### ISSUE THREAD

**Issue by bfallon** [marmelroy/PhoneNumberKit#385]
The new area code for British Columbia (672) is not valid via parse:

**_New 672 area code for British Columbia. VANCOUVER, Jan. 22, 2019 /CNW Telbec/ - Starting May 4, 2019, the new area code 672 will be added to the current 604, 250, 778 and 236 area codes already in use in British Columbia._**

I've looked at editing the PhoneMetadata.json to add this area code, but could use a little direction as to where to add this information.

**Comment by IgorChernyshov** [comment]
Hi Brian
As far as I see it's already there.
PhoneMetadata.json contains an object with "id": "CA". There is a regular expression to filter out CA numbers:
(?:2(?:04|[23]6|[48]9|50)|3(?:06|43|6[57])|4(?:03|1[68]|3[178]|50)|5(?:06|1[49]|48|79|8[17])|6(?:04|13|39|47|72)|7(?:0[59]|78|8[02])|8(?:[06]7|19|25|73)|90[25])[2-9]\\d{6}
Basically we are interested in this part:
|6(?:04|13|39|47|72)
Which means OR the number starts with 6 followed by one of the numbers in the list: 04 or 13 or 39 or 47 or 72.
So 672 is already there, no worries :)
