### ISSUE TITLE
How do I remove auto-focus?

### ISSUE THREAD

**Issue by CodyBontecou** [marmelroy/PhoneNumberKit#387]
I'm working with `PhoneNumberTextField` and so far, really am enjoying the functionality of this plugin. The problem is that whenever the view loads, this field is automatically set to focus. I'd prefer the first form within this view to get focus, not this field which is later on in the view.

Is there a reason this field is always focussed? How can I disable that from happening?

**Comment by ekucet** [comment]
if you don't use the becomeFirstResponder() method, you can do it.
