### ISSUE TITLE
ParseOperationValueProvider - expected declaration error

### ISSUE THREAD

**Issue by HaiLe** [marmelroy/PhoneNumberKit#39]
I recently upgrade to PhoneNumberKit 0.6.4 and xcode gave me this error "Expected Declaration" in ParseOperation.swift 

```
/**
Value provider protocol.
*/
public protocol ParseOperationValueProvider {
    associatedtype ProvidedInputValueType
}
```

Please help.

**Comment by marmelroy** [comment]
Hi @HaiLe,

PhoneNumberKit 0.6.4 was upgraded to use Swift 2.2. Are you using the newest version of XCode (7.3, released on Monday)?

**Comment by marmelroy** [comment]
Closing.

**Comment by HaiLe** [comment]
Hi @marmelroy - thanks for the help! upgrade to xcode 7.3 and swift 2.2 fixed the issue!

**Comment by salomoko** [comment]
@marmelroy so `0.6.3` should be good with xcode 7.2 etc?
