### ISSUE TITLE
Fails to build project in Xcode12: module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by zulfishah** [marmelroy/PhoneNumberKit#391]
I've been using Carthage to build PhoneNumberKit in my project for a while. When I run the project in Xcode12, it fails with an error:
`<unknown>:0: error: module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/zs/Documents/CJ/branches/CJ-400/SimpleList/Carthage/Build/iOS/PhoneNumberKit.framework/Modules/PhoneNumberKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
`

I've tried cleaning the Carthage directory, then in Xcode Preferences, switching the "Command Line Tools" to Xcode12, and then building again using: carthage update PhoneNumberKit --platform iOS

But it fails to build as well. The build logs show this error:

`
** ARCHIVE FAILED **
The following build commands failed:
Ld /Users/zs/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A6163b/PhoneNumberKit/3.2.0/Build/Intermediates.noindex/ArchiveIntermediates/PhoneNumberKit/IntermediateBuildFilesPath/PhoneNumberKit.build/Release-iphoneos/PhoneNumberKit.build/Objects-normal/armv7/Binary/PhoneNumberKit normal armv7 (1 failure)
`

Any idea what might be going on, and how I can fix it?

**Comment by StanDimitroff** [comment]
@zulfishah I suppose the framework should be updated to Swift 5.3

**Comment by StanDimitroff** [comment]
[Workaround](https://github.com/Carthage/Carthage/issues/3019)

**Comment by zulfishah** [comment]
That workaround seems to refer to a different problem. Still, I tried setting "Set Build Library for Distribution" to Yes, but that gives me a different error: "error: using bridging headers with module interfaces is unsupported".

**Comment by zulfishah** [comment]
With Xcode12 Beta6, when I run "carthage update PhoneNumberKit --platform iOS", it shows me some other error:

> *** Building scheme "PhoneNumberKit" in PhoneNumberKit.xcodeproj
> Build Failed
> 	Task failed with exit code 1:
> 	/usr/bin/xcrun lipo -create /Users/zulfishah/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/PhoneNumberKit/3.2.0/Build/Intermediates.noindex/ArchiveIntermediates/PhoneNumberKit/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/PhoneNumberKit.framework/PhoneNumberKit /Users/zulfishah/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/PhoneNumberKit/3.2.0/Build/Products/Release-iphonesimulator/PhoneNumberKit.framework/PhoneNumberKit -output /Users/zulfishah/Documents/ContactsJournalGit/branches/ContactsJournal-400/SimpleList/Carthage/Build/iOS/PhoneNumberKit.framework/PhoneNumberKit
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/kw/s2d4y7hs0lqgx20jhfj6v2000000gn/T/carthage-xcodebuild.oyTkBY.log


But when I look inside the .log file, it shows that the Build Succeeded, and doesn't show any errors anywhere. 

Really confused by all of this. Any help would be appreciated.

**Comment by StanDimitroff** [comment]
I actually tried [this](https://github.com/Carthage/Carthage/issues/3019#issuecomment-664099506) and the build was successful. Don't forget to set command line tools to refer Xcode 12 beforehand.

**Comment by zulfishah** [comment]
Thanks. I was looking at the wrong work-around. You're right, the workaround in the thread (specifically, creating the carthage.sh file and running that) does work for me as well.
