### ISSUE TITLE
Fails to build in Xcode 12 - Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by isaquedev** [marmelroy/PhoneNumberKit#394]
On try to build in Xcode 12 beta i'm facing this error:

```Undefined symbols for architecture i386:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in CountryCodePickerViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by mazhigbee-pb** [comment]
I'm also seeing this issue.

**Comment by RobinDaugherty** [comment]
Upgrading to 3.2.0 seems to fix it. (Using Cocoapods and Xcode 12 beta 3.)

**Comment by florianbuerger** [comment]
As a temporary solution, you can bump the iOS deployment target to at least 11.0 (if possible for your project), e.g. https://github.com/florianbuerger/PhoneNumberKit/commit/553e8f1c27d73208a05b809b4973132311e46ecb.

**Comment by tramert** [comment]
@florianbuerger I apologize in advance due to the trivial nature of this question, but where can I find the file you modified (PhoneNumberKit.xcodeproj/project.pbxproj) to fix this?

Additional context:
I am using Cocoapods to pull in PhoneNumberKit
I have only been writing iOS apps for a few days 😬

**Comment by isaquedev** [comment]
I add this code in my podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
```

It's a work around, but works to run or archive in Xcode 12.
