### ISSUE TITLE
Cannot input cell phone number beginning with 195

### ISSUE THREAD

**Issue by cycy999** [marmelroy/PhoneNumberKit#399]
Now China has opened the mobile phone number beginning with 195, but this SDK has not opened such mobile phone number yet, may I ask when can it be solved？Thanks.

**Comment by marmelroy** [comment]
@cycy999 - is this fixed with the new release and metadata update?

**Comment by cycy999** [comment]
@marmelroy Thanks for your support. I have test this issue at 3.3.0, it can input the number starts with 19xxx normally. It's a exciting news.

**Comment by marmelroy** [comment]
Great to hear @cycy999

**Comment by hshaoGitHub** [comment]
@marmelroy 

Thanks for the fix. I also need the fix, would you please help to merge the fix to master branch? Many thanks!
