### ISSUE TITLE
Carthage update failing

### ISSUE THREAD

**Issue by leewhelan4** [marmelroy/PhoneNumberKit#424]
Hello,

I'm having an issue updating to versions 3.3.0 and 3.3.1 respectively with Carthage. Both versions produce the following error:

`A shell task (/usr/bin/xcrun xcodebuild -project /Users/leewhelantemp/Documents/Repos/iOS/common-ios/Carthage/Checkouts/PhoneNumberKit/examples/AsYouType/Sample.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:xcodebuild: error: Could not resolve package dependencies. The repository could not be found. Make sure a valid repository exists at the specified location and try again.`

Any help would be great. Thanks!

**Comment by ketan-shinde-mav** [comment]
> Hello,
> 
> I'm having an issue updating to versions 3.3.0 and 3.3.1 respectively with Carthage. Both versions produce the following error:
> 
> `A shell task (/usr/bin/xcrun xcodebuild -project /Users/leewhelantemp/Documents/Repos/iOS/common-ios/Carthage/Checkouts/PhoneNumberKit/examples/AsYouType/Sample.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:xcodebuild: error: Could not resolve package dependencies. The repository could not be found. Make sure a valid repository exists at the specified location and try again.`
> 
> Any help would be great. Thanks!

i'm facing same issue

**Comment by eliburke** [comment]
@leewhelan4 @ketan-shinde-mav Did either of you resolve this compile problem with PhoneNumberKit? I'm running into it as well (XCode 11.7, Carthage 0.36). 

My error is a little more detailed, but is still occurring on the same Sample project. 

> A shell task (/usr/bin/xcrun xcodebuild -project [...]/Carthage/Checkouts/PhoneNumberKit/examples/AsYouType/Sample.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
> xcodebuild: error: Could not resolve package dependencies:
>   because PhoneNumberKit >=3.3.0 contains incompatible tools version and root depends on PhoneNumberKit 3.3.0..<4.0.0, version solving failed.

**Comment by julestburt** [comment]
Seeing the same issue.
