### ISSUE TITLE
autocomplete doesn't work

### ISSUE THREAD

**Issue by DKalachniuk** [marmelroy/PhoneNumberKit#426]
when i click on phone suggestion - nothing happens

the fix would be 

// This allows for the case when a user autocompletes a phone number:
        if range == NSRange(location: 0, length: 0), string == " " {
            return true
        }

change to string = " " to string = ""

thank you

**Comment by jeremyschoenherr** [comment]
found the same to be true. i had to subclass `PhoneNumberTextField` in 3.3.2 and override `textField(:shouldChange.....)` this as well. it used to pass an empty string ("") but it seems ios 14 can pass a space as well (" ")

**Comment by marmelroy** [comment]
Thanks @jeremyschoenherr. I will change it to check for both.

**Comment by marmelroy** [comment]
This should now be fixed in release 3.3.3
