### ISSUE TITLE
Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler on Xcode 12.2

### ISSUE THREAD

**Issue by SergeyDevUA** [marmelroy/PhoneNumberKit#428]
**Description**

Previously I was using Xcode 11.7 to build these frameworks using Carthage. Now I upgraded Xcode to 12.2 and after building these frameworks when I integrate into my project and tried to run, it shows an error like:

Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler

**Steps to Reproduce**

update your Xcode version to 12.2
Build framework using Carthage carthage update --platform iOS
Add PhoneNumberKit.framework into any project
Run the project

**Actual Error:**

Module compiled with Swift 5.3 cannot be imported by the Swift 5.3.1 compiler: /Users/sergey/Desktop/ios/Carthage/Build/iOS/PhoneNumberKit.framework/Modules/PhoneNumberKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by marmelroy** [comment]
Hi @SergeyDevUA - is it a case of having the wrong command line tools selected? See https://github.com/Alamofire/Alamofire/issues/3280 ?
