### ISSUE TITLE
AsYouType

### ISSUE THREAD

**Issue by Treverr** [marmelroy/PhoneNumberKit#43]
It's most likely something I'm missing or not understanding, but I replaced the UITextField with PhoneNumberTextField in both my code at my IBOutlet and in the Storyboard but it does not seem to actually formate as I type, is there something that I might be missing?

**Comment by Treverr** [comment]
It also crashes on .delegate = self

Should that be removed? I saw that PhoneNumberTextField was a subclass of UITextFieldDelegate

**Comment by chow-land** [comment]
Im having the same issue (the first one). I set PhoneNumberTextField as my custom UITextField class, re-wired the outlet, but it doesn't format when I type.

**Comment by marmelroy** [comment]
Hey @Treverr and @chow-land, I'm unable to replicate this issue. Would it be possible for either of you to share some code?

**Comment by piyushkantm** [comment]
this is in the VC file..

`let phoneNumberKit = PhoneNumberKit()
@IBOutlet weak var phoneNoField: PhoneNumberTextField!`

and in storyboard, i have set the custom class of 'phoneNoField' as `PhoneNumberTextField`
still it doesn't format the number as i type!!

**Comment by piyushkantm** [comment]
just got it working..
turns out there is no requirement to even change ViewController class..
when you set the class in storyboard as `PhoneNumberTextField`, then select the `PhoneNumberKit` module from dropdown.. it worked for me.

**Comment by marmelroy** [comment]
Mystery solved. Thanks @piyushkantm. I updated the README to be a little clearer about the module selection https://github.com/marmelroy/PhoneNumberKit/commit/107d11aec1b3ebef3a9b599edd62650d7b0153fb

**Comment by chow-land** [comment]
Thanks @piyushkantm , I just set the module and it works for me now as well. 

Thanks for the README update @marmelroy ! Library is looking great so far.

**Comment by piyushkantm** [comment]
thanks @marmelroy for updating README
Welcome @chow-land  ;)
