### ISSUE TITLE
SwiftUI Renderer crash

### ISSUE THREAD

**Issue by DeveloperBeau** [marmelroy/PhoneNumberKit#433]
Description

Since importing into the project, all SwiftUI Xcode canvas renderers crash when trying to load a preview.

Steps to Reproduce

update Xcode to 12.3
Add PhoneNumberKit via SPM to your project
click resume to preview view using a swiftui canvas

Actual Error:

Error Domain=NSCocoaErrorDomain Code=516 "“resource_bundle_accessor.swift” couldn’t be linked to “Intermediates” because an item with the same name already exists." UserInfo={NSSourceFilePathErrorKey=/Users/[user]/Library/Developer/Xcode/DerivedData/[APP NAME]-cxcyhpnbpyovrmgvayzxidqknuvf/Build/Intermediates.noindex/PhoneNumberKit.build/Debug-iphoneos/PhoneNumberKit.build/DerivedSources/resource_bundle_accessor.swift, NSUserStringVariant=(
    Link
), NSDestinationFilePath=/var/folders/hp/x4bpmr_n32dc8wrkyp5lqvpc0000gn/T/previews-diagnostics-20201229-094502/Intermediates/resource_bundle_accessor.swift, NSFilePath=/Users/[user]/Library/Developer/Xcode/DerivedData/[APP NAME]-cxcyhpnbpyovrmgvayzxidqknuvf/Build/Intermediates.noindex/PhoneNumberKit.build/Debug-iphoneos/PhoneNumberKit.build/DerivedSources/resource_bundle_accessor.swift, NSUnderlyingError=0x7ff9cc1bcb90 {Error Domain=NSPOSIXErrorDomain Code=17 "File exists"}}

**Comment by danpalmer** [comment]
@DeveloperBeau did you ever get anywhere investigating this? We have a similar issue on our project, although with the Stripe library, not PhoneNumberKit.

**Comment by chizhavko** [comment]
Still can reproduce on xcode 14
