### ISSUE TITLE
countryCodePickerViewControllerDidPickCountry couldn't be overridden to change the input behavior on region change

### ISSUE THREAD

**Issue by illabo** [marmelroy/PhoneNumberKit#434]
@marmelroy Thank you for considering making this method `public`, however it isn't usable as it may look at first. Public method of a library may be accessed from an outside module but can't be overridden. But even if you'd make it `open` it still won't be overridable in Swift because it is declared in extension: `Overriding declarations in extensions is not supported`. Lastly even if this method would be lifted from extension to the class declaration and made open it still won't be usable because e.g. `_defaultRegion` is private and `containingViewController` is internal and because of that are inaccessible from outside modules.
What I may see as an alternative is allowing to set the number retention policy in the class' constructor (or the class variables) defaulting to `.clearOnRegionChange`. Then checking it in `countryCodePickerViewControllerDidPickCountry`:
```swift
switch numberRetentionStrategy {
    case .clearOnRegionChange:
        text = isEditing ? "+" + country.prefix : ""
    case .trySwitchToNewRegion:
        text = ...
    ...
}
```
I understand that the interest in such a behavior is quite low, maybe I'm an only one to need it. Please let me know if I may alternate #375 to introduce the changes described above or should better close the PR.

**Comment by ahmedelmoughazy** [comment]
have you figured it out?
