### ISSUE TITLE
Parsing phone numbers floods terminal with "Updating selectors after delegate removal failed" errors

### ISSUE THREAD

**Issue by AttilaTheFun** [marmelroy/PhoneNumberKit#444]
I'm using PhoneNumberKit through SPM and when I'm debugging on a device, every single call to parse / format on my phone number kit instance causes the following to be logged:

```
2021-02-23 20:39:32.900666-0800 Hang[16567:4063886] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 92 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 92 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
2021-02-23 20:39:32.916084-0800 Hang[16567:4063884] [Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 92 named
...
```

For hundreds of phone numbers this can be thousands of logs in a second. Is this a bug with the framework? If not, is there a way I can fix it or at least suppress the logs?

This is how it's being called:

```
private let kPhoneNumberKit = PhoneNumberKit()

...

        let phoneNumbers = content.contact.phoneNumbers
            .compactMap { try? kPhoneNumberKit.parse($0) }
            .map { kPhoneNumberKit.format($0, toType: .national) }
```

All of the calls to parse and format are happening on the main thread (to format phone numbers for display in tableview cells).

**Comment by mithilesh-parmar** [comment]
I'm facing the same issue, any solution?

**Comment by nathanielnorth** [comment]
Same here, PhoneNumberKit through SPM.

This won't produce the log messages:
` let phoneNumber = try phoneNumberKit.parse(number, withRegion: "AU")`

This will:
` let phoneNumber = try phoneNumberKit.parse(number)`

**Comment by AttilaTheFun** [comment]
Hmm @nathanielnorth is the region flag a suggestion? Or does it limit parsing to only Australian phone numbers?
I.e. if I put "US" would that prevent me from parsing international numbers?

**Comment by nathanielnorth** [comment]
I'm not sure @AttilaTheFun 🤔

I'm using PhoneNumberKit to format numbers found with NSDataDetector. But if I don't set the region flag I get the same flood of log messages.

I haven't put much time into figuring out what's going on as my focus is elsewhere in the app at the moment, just noticed you had a similar problem and thought I'd add my case to the issue.

**Comment by yspreen** [comment]
man, this took a while to debug. doesn't help that PNK does not show up when searching the error.

I ended up trying carthage instead of SPM and the issue persists. Some feedback would be great

**Comment by yspreen** [comment]
Workaround: Set 

```
let defaultRegionCode = PhoneNumberKit.defaultRegionCode()
```

somewhere. Now you only need to call the messy function once. Everytime you would normally do

```
kit.parse(text)
```

you can now call

```
kit.parse(text, withRegion: defaultRegionCode)
```

instead and the issue is kinda fixed. Behaves exactly the same.

**Comment by nathanielnorth** [comment]
Good workaround, seems to work nicely. Thanks very much yspreen 👏

**Comment by yspreen** [comment]
still very much open

**Comment by bguidolim** [comment]
Hey folks!
Could you check my PR #521 regarding this issue?
