### ISSUE TITLE
PhoneNumberTextField breaks after entering some digits

### ISSUE THREAD

**Issue by Banck** [marmelroy/PhoneNumberKit#447]
Hello!
Just noticed, if enter +8088 textfield will break and you won't be able to enter correct number:

https://user-images.githubusercontent.com/6259254/110071383-825f5780-7dae-11eb-8851-6aec83948acf.mov

**Comment by mukhammadjonAskarov** [comment]
I am facing the same issue with numbers: +808, +888

**Comment by lutes1** [comment]
Same issue but on some builds it's broken from the beginning, after entering "+" any digit added afterwards removes the "+" character
