### ISSUE TITLE
cant use on watchOS

### ISSUE THREAD

**Issue by bukira** [marmelroy/PhoneNumberKit#448]
The library won't complie for watchOS 7.2, is this a known issue? any plans to support watchOS

**Comment by bukira** [comment]
I am getting build errors in :
CountryCodePickerViewController
PhoneNumberTextField
(101 error)
for watchOS and i386

even nthough is as and if can import

**Comment by bukira** [comment]
ive manually made the change locally and works fine, can this be changed in the code?

**Comment by bukira** [comment]
I see there's a merge waiting with this exact fix, can this be done please

**Comment by bguidolim** [comment]
Fixed with #435
