### ISSUE TITLE
Do not submit apps with GCC-style coverage

### ISSUE THREAD

**Issue by maninderssoor** [marmelroy/PhoneNumberKit#45]
I'm using PhoneNumberKit with carthage and get an iTunes Connect processing error:
"Do not submit apps with GCC-style coverage" for archive submissions.

Is there any way of disabling this warning without manually changing the build "Instrument Program Flow" settings whenever I carthage update or disabling Bitcode in my project?

**Comment by marmelroy** [comment]
Hi @maninderssoor, good issue! Yes, there is a way to solve this in the build settings. Pushing a fix now.

**Comment by maninderssoor** [comment]
Thanks so much @marmelroy !!!

**Comment by marmelroy** [comment]
New version release (0.8.3). Try it and let me know if it works. Closing for now.
