### ISSUE TITLE
Couldn't listen when new country is selected from Country Picker 

### ISSUE THREAD

**Issue by EsraaGK** [marmelroy/PhoneNumberKit#452]
I am using RxSwift to listen on text changes in PhoneNumberTextField but I faced a problem 
when a phone is written and then a user clicks flag button to pick a country, the text is no longer written in the text field but the delegate isn't triggered also the textfield.rx.text didn't feel the change 
so I couldn't observe the change in the textfield.text 
I need a way to know when the user select a country like this delegate 
"public func countryCodePickerViewControllerDidPickCountry(_ country: CountryCodePickerViewController.Country) "
but I couldn't find a way

**Comment by magnusfernandes** [comment]
+1
