### ISSUE TITLE
Cannot enter a valid phone number if the 1st digit of national number matches national prefix

### ISSUE THREAD

**Issue by VasilievMB** [marmelroy/PhoneNumberKit#453]
For example **8 812 234-56-78** is a valid phone number in St. Petersburg, but if you set `withPrefix = false` and start typing **8** in `PhoneNumberTextField` it is removed as `extractNationalPrefix(_: String)` function wrongly assumes it to be national prefix.

### Steps to reproduce

1. Build and run _examples/AsYouType/Sample.xcodeproj_ project
2. Deselect withPrefix
3. Select withFlag and withDefaultPickerUI
4. Select **Russia** in countries picker
5. Type **8**

### Expected Behavior

Text changes to **8**

### Current Behavior

Text remains empty

Any ideas for a workaround until it's fixed?

**Comment by ay1920** [comment]
Picked this Issues
