### ISSUE TITLE
KZ Number is showing as RU number 

### ISSUE THREAD

**Issue by mukhammadjonAskarov** [marmelroy/PhoneNumberKit#459]
+7 7272 50 76 12

Here is the screenshot. I have inserted KZ number. it might sound similar to the solution [#431](https://github.com/marmelroy/PhoneNumberKit/pull/431) However solution is not proper for this case

<img width="364" alt="Screen Shot 2021-05-25 at 17 52 10" src="https://user-images.githubusercontent.com/45823708/119501059-ef690480-bd81-11eb-8df9-1be544b2d72e.png">

**Comment by mehulparmar4ever** [comment]
I find same issue 😒
