### ISSUE TITLE
Expected Declaration error

### ISSUE THREAD

**Issue by salomoko** [marmelroy/PhoneNumberKit#46]
**version:** 0.8.3
@marmelroy 
App won't compile with an error here 

```/**
Value provider protocol.
*/
public protocol ParseOperationValueProvider {
    associatedtype ProvidedInputValueType
}```

halp!!

**Comment by salomoko** [comment]
Im still on Xcode 7.2. think this commit broke it for backwards compatibility...
https://github.com/marmelroy/PhoneNumberKit/commit/c5ea038f98d9abf4b4ee001b9791643c96f5f74c#diff-e5a05125374826bda329e1120ed969fc

is `associatedtype` a swift 2.2/3 thing?

**Comment by marmelroy** [comment]
Hi @salomoko. Yes, sorry. Swift is moving fast and PhoneNumberKit needs to support the latest public version. I'm afraid Xcode 7.3 is needed to compile. Sorry again.
