### ISSUE TITLE
Detection of UK Numbers doesn't work in 99% of real world use cases

### ISSUE THREAD

**Issue by TheOriginalTrubador** [marmelroy/PhoneNumberKit#47]
When you enter a UK/GB number using the standard way UK citizen will enter the number (with a preceding 0) it is not being parsed correctly as a UK number. Remove the preceding zero and it parses some area codes (mobiles fine), but not others.

Think the issue is that the phone mask for the UK is (0xxxx) 123456 sometimes and (0xxxx) 1234567 at others not (xxxx) 123456 which is never dialled. For international format that would be +44 (xxxx) 123456 or (xxxx) 1234567. 

For example:

(0118) 9 345678 (Reading Area Code)
(020) 7 123456 (London Area Code)
(07792) 123456
(01634) 123456 (Kent Area Code)

Entering any of the above fail- in fact, I cannot get a single UK landline number to work. If I exclude the 0 on 7792 123456 that works.

Importance is that 1) Users will definitely enter the number this way and 2) Dialling without the zero will always fail internally to the UK unless the international code replaces it in the position- so you could dial 00441189345678 or 01189345678 and succeed, but dial 1189345678 and it will fail.

**Comment by marmelroy** [comment]
Hi @TheOriginalTrubador, 

Sorry for the delay. After some consideration, I'm not sure there's an issue here. 

To handle local phone numbers, PhoneNumberKit requires the user's current region. This is usually determined automatically by default using the country of the iPhone's SIM.

However, you can also override it. 

When running: 
```
            let phoneNumber = try PhoneNumber(rawNumber:"(0118) 9 345678", region: "GB")
            (phoneNumber.isValidNumber == true) ? XCTAssert(true) : XCTFail()
```

All of your examples except for "(020) 7 123456" pass. "(020) 7 123456" is actually an invalid number and fails on Google's libPhoneNumber as well (you can try it here - https://libphonenumber.appspot.com).  

My guess is that you are either using the simulator (defaults to US region) or an iPhone with an international SIM.
