### ISSUE TITLE
What version of Google's libPhoneNumber implementation are you relying on? 

### ISSUE THREAD

**Issue by DubonYaar** [marmelroy/PhoneNumberKit#470]
What version of Google's libPhoneNumber implementation are you relying on?

**Comment by AndrewSB** [comment]
you can see the current version of the metadata being depending on in this folder https://github.com/marmelroy/PhoneNumberKit/tree/master/PhoneNumberKit/Resources

as of writing this, it seems to be version [8.12.43](https://github.com/marmelroy/PhoneNumberKit/commit/3acbcdea1bcce506a82c0f3ed5aa5894f43dc43e)
