### ISSUE TITLE
Multi phone for all countries

### ISSUE THREAD

**Issue by balkarov** [marmelroy/PhoneNumberKit#474]
Hello.

Thank you for your library!

I need multiple format phones:
+7 999 999 99 99
+49 176 1111111111
+1 111-111-1111
And etc. For all countries. How to implement it?

**Comment by AndrewSB** [comment]
yeah, i need this too. the documentation for `parse(phoneNumbers: [String])` doesn't mention that it only works for phone numbers from one region, i too assumed i could pass in phone numbers from many regions and have them parse. but doesn't look to be the case

@balkarov you're going to have to parse each number individually. like

```
[+7 999 999 99 99, +49 176 1111111111, +1 111-111-1111].tryMap {
  try phoneNumberKitInstance.parse(phoneNumber: $0)
}
```
