### ISSUE TITLE
Côte d'Ivoire("CI") parser works wrong.

### ISSUE THREAD

**Issue by sargismkhitaryan** [marmelroy/PhoneNumberKit#476]
Côte d'Ivoire has expanded its national numbering plan from 8 to 10 digits. In case of "CI" parser function works wrong.

**Comment by DimDL** [comment]
https://github.com/marmelroy/PhoneNumberKit/pull/481/files

**Comment by bguidolim** [comment]
@sargismkhitaryan I guess it is fixed already. Can I close it?
