### ISSUE TITLE
Support for Accessibility for CountryCodePickerViewController cell

### ISSUE THREAD

**Issue by janakirampalepu** [marmelroy/PhoneNumberKit#483]
Hi,

I am using PhoneNumberTextField in my application. we are trying to automate my app testing so we require accesibilityIdentifier to perform actions.

We could automate the tap for  PhoneNumberTextField and its country flag button . However , we could not select the row inside the  CountryCodePickerViewController list. We need to add accesibilityIdentifier for table cell. I tried to subclass the CountryCodePickerViewController with below code. However , compiler thrown an exception saying  CountryCodePickerViewController cannot be subclassed.

public class MyCountryCodePickerViewController: CountryCodePickerViewController {
    
    override public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {

        let cell = super.tableView(tableView, cellForRowAt: indexPath)

        // from super implementation
        // cell.textLabel?.text = country.prefix + " " + country.flag

        // below code to set the accessibility Identifier for the table cell
        let countryPrefix = cell.textLabel?.text?.components(separatedBy: " ").first ?? ""
        cell.accessibilityIdentifier = countryPrefix

        return cell
    }

}

<img width="1763" alt="Screenshot 2021-10-14 at 1 25 18 PM" src="https://user-images.githubusercontent.com/85152102/137275475-fbe4932e-e55a-44cc-b0fe-63fc239c498c.png">

Please look into this and help me to solve the problem with accesibilityIdentifier for country list row.

If required I would love to contribute my changes via Pull request to this framework.

**Comment by janakirampalepu** [comment]
Hello Authors / Contributors,

Can you at least provide reply on this issue.

-Janakiram

**Comment by bguidolim** [comment]
Hey @janakirampalepu 

I've just arrived as a maintainer of the project, and looking at this class, seems that this was never meant to allow subclassing. 

However, we can definitely add accessibility identifiers to it. Would you mind creating a PR with the changes you need? I'll make sure that you get this merged soon.

Thank you,
Bruno
