### ISSUE TITLE
Incompatible with pod "BlocksKit"

### ISSUE THREAD

**Issue by jeryRazakarison** [marmelroy/PhoneNumberKit#49]
Hi!
It seems that PhoneNumberKit and BlocksKit are incompatible.
I have set in interface builder a PhoneNumberTextField. It works ok. But I soon as I reactivate my BlocksKit pod, there is a loop with `keyboardInputChangedSelection`
`__invoking___`
`[A2DynamicDelegate fowrwardInvocation]`

And it ultimatly crash with a `__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__`

Does anyone have this problem?

Thank you

**Comment by marmelroy** [comment]
Thanks @jeryRazakarison. Seems to me like an Objc/Swift compatibility BlocksKit issue...
