### ISSUE TITLE
New North Carolina area code (472) is considered an unknown type by PNK (doesn't match a national number pattern)

### ISSUE THREAD

**Issue by karim-elgendy** [marmelroy/PhoneNumberKit#491]
I think the national number pattern regex in the metadata.json needs to be updated to support a new US area code 472. Numbers are being returned as invalid as the type is unknown.

I'd do this myself but my regex sucks - or maybe these are open source algorithms pulled from somewhere else that have been updated?

**Comment by mmdock** [comment]
this isn't necessary until 10/07/2022 though, which is when that area code comes into use.

**Comment by karim-elgendy** [comment]
@mmdock Not so sure about that -  we have customers currently using these phone numbers who are suffering failing validation in our app. We have to patch this to bypass PNK returning an invalid national number pattern.

**Comment by mmdock** [comment]
<img width="660" alt="Screen Shot 2022-03-22 at 3 16 07 PM" src="https://user-images.githubusercontent.com/2423465/159585366-84d63a9e-465f-455f-acfd-b03c3ef4cfc1.png">

if it is a 472 area code, they will not be getting assigned until October 7th of this year.

sounds more like you have a user from mexico who isn't using the mexican country code.

**Comment by mmdock** [comment]
@karim-elgendy
