### ISSUE TITLE
If you type +888(or any other illegal prefix) in keyboard, with turned on flag, it permanently turns regionCode to "001." 

### ISSUE THREAD

**Issue by ShynggysSaparbek** [marmelroy/PhoneNumberKit#493]
If you enter +888 in keyboard, with turned on flag, it turns regionCode to "001. It can not be resolved by deleting old text.
![IMAGE 2021-12-02 23:07:52](https://user-images.githubusercontent.com/34959131/144469426-8795df87-a8f5-4a2f-9b27-0c284b675d45.jpg)

**Comment by bguidolim** [comment]
The latest relase had the metadata updated. Could please you check with this version?
