### ISSUE TITLE
the flag isn't updated after "var text: String?" is changed

### ISSUE THREAD

**Issue by dyf8464** [marmelroy/PhoneNumberKit#496]
the flag isn't updated after "var text: String?" is changed 

for example: 
phoneNumberTextField.text = "+33 04 08 08 08".  the flag isn't updated to France,  it's a bug ?

**Comment by AlessandroMulloni** [comment]
https://github.com/marmelroy/PhoneNumberKit/pull/512

**Comment by bguidolim** [comment]
Closed with #512
