### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mitchellporter** [marmelroy/PhoneNumberKit#5]
Looks like a great library. Installed with Cocoapods and it's throwing the following error when running the example code from the README: `fatal error: unexpectedly found nil while unwrapping an Optional value`

```Swift
do {
    let phoneNumber = try PhoneNumber(rawNumber:"+33 6 89 017383")
}
catch {
    print("Generic parser error")
}
```

Installed with cocoapods 0.39 and Xcode 7.1

**Comment by marmelroy** [comment]
Thanks Mitchell. I'll check and fix first thing tomorrow morning.

**Comment by mitchellporter** [comment]
@marmelroy Thanks for such a fast response. I just ran it in release mode and it's throwing the exception on line 36 in `Metadata.swift`

**Comment by mitchellporter** [comment]
@marmelroy Quick update for you. I just uninstalled the cocoapod and imported the library manually. It no longer throws the error and is working fine. Looks like something's wrong with the pod.

**Comment by marmelroy** [comment]
Ah... okay, I suspect Cocoapods is not installing the json metadata file. Good find. Fix soon.

**Comment by marmelroy** [comment]
Yup, so that was the issue. Fixed by updating the podspec and released a new version (check out the release note - https://github.com/marmelroy/PhoneNumberKit/releases/tag/0.1.3).

Thanks again for highlighting this problem. Closing now.

**Comment by mitchellporter** [comment]
@marmelroy No problem thanks for the fast fix cheers!
