### ISSUE TITLE
PhoneNumber name collisions

### ISSUE THREAD

**Issue by jersonperpetua** [marmelroy/PhoneNumberKit#50]
We're using PhoneNumberKit internally to check if strings provided by either the user or our APIs are valid phone numbers. We also use it to extract phone number information or to simply format the numbers for display. We think it's awesome, and very much appreciate your work! :)

However, we are having problems defining our very own `PhoneNumber` atom; `PhoneNumberKit` (the class) causes the Swift compiler to get confused whenever we try to qualify types using the `PhoneNumberKit` namespace:

e.g.,
```swift
// Note: This code is for illustration purposes only

import PhoneNumberKit

struct PhoneNumber {
    let value: String
    // ...
    var regionCode: String? {
        let phoneNumber = try? PhoneNumberKit.PhoneNumber(rawNumber: value)
        // ^ Error: Type 'PhoneNumberKit' has no member 'PhoneNumber'
        return phoneNumber.flatMap {
            PhoneNumberKit.PhoneNumberKit().regionCodeForNumber($0)
            // ^ Error: Type 'PhoneNumberKit' has no member 'PhoneNumberKit'
        }
    }
}
```

We did some tests where we replaced the PhoneNumberKit import with an `import struct PhoneNumberKit.PhoneNumber` on the file in question, and typealiased the `PhoneNumberKit` class to a different name (e.g., `PhoneNumberManager`) on another file, and it seems like this really is the root of the problem.

We have a few suggestions (all of which, unfortunately, requires some level of API breakage with the current version):

* **Rename the `PhoneNumberKit` class:** This requires very little changes to both the codebase, and existing users of the library.
* **Turn all methods in `PhoneNumberKit` into free functions:** This aligns with other libraries like Alamofire that exposes free functions, which are then called with their module names, by convention (e.g., `Alamofire.request`, etc.).

What do you think? We can provide you with a PR if and when you arrive into a conclusion. Thanks!

**Comment by marmelroy** [comment]
Hi @jersonperpetua, 

Sorry for the delay on this one. 

PhoneNumberKit reserves the use of PhoneNumber objects and I see it as the client's responsibility to avoid naming collisions.
