### ISSUE TITLE
Force region/flag from text

### ISSUE THREAD

**Issue by andrii-lisovskiy** [marmelroy/PhoneNumberKit#504]
When I am setting text to textField it takes current region, and shows its flag.
It changes only when I am editing text.
So, how to force region and flag changing when setting text for PhoneNumberTextField?

**Comment by AlessandroMulloni** [comment]
Duplicate of https://github.com/marmelroy/PhoneNumberKit/issues/496

**Comment by bguidolim** [comment]
Closed with #512
