### ISSUE TITLE
New South Carolina area code (839) is being validated as an unknown type by PNK (doesn't match a national number pattern)

### ISSUE THREAD

**Issue by iOSNinja** [marmelroy/PhoneNumberKit#508]
Hello,
The library is not able to validate the new South Carolina area code 839. Looks like the national number pattern regex in the metadata.json needs to be updated to support this new area code 839. Numbers are being returned as invalid with type as unknown.

It would be great to know if you are planning to include this new area code anytime soon. Appreciate it.

Thanks

**Comment by bguidolim** [comment]
The latest relase had the metadata updated. Could please you check with this version?
