### ISSUE TITLE
When decoding with a default region, numbers that start with + are parsed successfully, even if they contain no country code

### ISSUE THREAD

**Issue by ryanbooker** [marmelroy/PhoneNumberKit#515]
e.g. This will successfully parse the number, but is not actually valid according to: libphonenumber.appspot.com. Other versions of libPhonenumber fail to parse this number.

```
let number = try phoneNumberKit.parse("+0400000000", withRegion: "AU", ignoreType: false)
```

This will be parsed as +61 400 000 000, instead of being rejected as an invalid country code.

https://libphonenumber.appspot.com/phonenumberparser?number=%2B0400000000&country=AU

**Comment by AndrewSB** [comment]
yeah what's up with the inconsistencies between using libPhoneNumber directly and going through this package? documenting those differences in the layer would be really useful
