### ISSUE TITLE
Wrong parsing with numbers starting with 00

### ISSUE THREAD

**Issue by revoltMoon** [marmelroy/PhoneNumberKit#525]
For example +992007123456 number from Tajikistan(+992 country code).
We lose the second zero in these lines in ParseManager when we call PhoneNumberKit parse function
<img width="566" alt="screen1" src="https://user-images.githubusercontent.com/27777585/166679471-6baacd96-d55a-46b2-bd91-05c21e76f7eb.png">

<img width="245" alt="screen2" src="https://user-images.githubusercontent.com/27777585/166679842-7027c244-770a-44c5-b76b-0296182e3c6e.png">
And Formatter knows about one zero
<img width="853" alt="screen3" src="https://user-images.githubusercontent.com/27777585/166680426-f92b70b5-be28-4519-ac59-24314137643d.png">

**Comment by bguidolim** [comment]
Which version is it happening?

**Comment by mmdock** [comment]
So, this function just later converts that Int phone number back into a string:
https://github.com/marmelroy/PhoneNumberKit/blob/1ef0431b971f69c48ca5eb4cdba07f2c5da54c35/PhoneNumberKit/ParseManager.swift#L141

https://github.com/marmelroy/PhoneNumberKit/blob/1ef0431b971f69c48ca5eb4cdba07f2c5da54c35/PhoneNumberKit/ParseManager.swift#L187

is there any practical reason for the code to be casting it as a UInt64? I was quickly scanning the code and didn't really see any true purpose for this.

**Comment by alexey1312** [comment]
> Which version is it happening?

Last - 3.4.1

**Comment by alexey1312** [comment]
Another example
![Simulator Screen Recording - iPhone 13 mini - 2022-05-24 at 13 14 52](https://user-images.githubusercontent.com/36570774/169971354-8778bd77-c7b0-4be7-8d00-ab7b6bf0e65e.gif)

**Comment by bguidolim** [comment]
Hey @revoltMoon, can you confirm if these formatted values are right?

<img width="630" alt="Screenshot 2022-05-24 at 12 49 02" src="https://user-images.githubusercontent.com/987360/170017880-7d138153-62f8-4115-b090-305097b17161.png">

For the others in this issue, could you send me phone number examples and the region code, please?

**Comment by revoltMoon** [comment]
@bguidolim looks like right

**Comment by bguidolim** [comment]
I've removed `UInt64` and used the national number as `String`, however, I think it can be a breaking change and seems to be a possible issue with phone numbers from Italy. I don't know how to proceed :(

**Comment by andreykozlov** [comment]
The issue described by [revoltMoon](https://github.com/revoltMoon) is not fixed yet :(
