### ISSUE TITLE
Is it possible to use this awesome lib in Objective-C project?

### ISSUE THREAD

**Issue by RockyLin** [marmelroy/PhoneNumberKit#536]
Xcode 13
OS: BigSur

In ViewController.m
@import PhoneNumberKit;

However, methods or fields of PhoneNumberKit cannot be accessed.

Is it possible to use this awesome lib in Objective-C project?

I'm new to swift, Please help!

**Comment by petermolnar-dev** [comment]
Hey @RockyLin ,
Unfortunately I don't have the exact guide, but I think you need to use some bridging headers. Maybe that guide helps: https://developer.apple.com/documentation/swift/importing-swift-into-objective-c

**Comment by keremerkan** [comment]
It is easier to use [https://github.com/iziz/libPhoneNumber-iOS](libPhoneNumber-iOS) on Objective-C. That also uses metadata from Google.
