### ISSUE TITLE
New number format in Brazil 0303 (telemarketing)

### ISSUE THREAD

**Issue by miliante** [marmelroy/PhoneNumberKit#539]
I am a user of _Simple Call Blocker_ on iOS. This app uses the PhoneNumberKit within its code to parse and display the phone numbers to be blocked by the phone.
Recently in Brazil a new law makes compulsory for telemarketing to use a dedicated phone number prefix, 0303, which is not in-line with the current numbering format used by PhoneNumberKit. This new number has the format +55 0303 123-4567, where 0303 is fixed and 123-4567 changes.
I checked the files in this repository and understood that it is just a matter of updating the PhoneNumberMetadata.json file with this new format (later I would request the programmer for _Simple Call Blocker_ to recompile it and upload to the apple store). Unfortunately I am no Swift programmer and cannot make the alterations myself, test it and propose a PR, but I'd be very happy if someone could. Hopefully it is just that simple.

Thank you, TM

**Comment by petermolnar-dev** [comment]
Hey @miliante ,
That particular file is not maintained by the PhoneNumberKit itself, but time-to-time it is updated from the Google libphonenumber repository: https://github.com/google/libphonenumber. I would suggest to open an issue with them. When it is done from their side (and released) I would be happily update the implementation in PhoneNumberKit.

**Comment by miliante** [comment]
Hello,

Thank you for your reply. I guess I did not go deep enough into the rabbit hole. I’ll contact them.

Have a great day.
