### ISSUE TITLE
Detecting wrong country code from phone number

### ISSUE THREAD

**Issue by redcirclegame** [marmelroy/PhoneNumberKit#54]
Code example:

```swift
let numberPhone = try PhoneNumber(rawNumber: "(636) 275-4512")
            
let countryCodeNumber = numberPhone.countryCode
            
let phoneNumberKit = PhoneNumberKit()
var countryCode = phoneNumberKit.countriesForCode(countryCodeNumber)?.first
```

log:
countryCodeNumber = 1

countryCode = "AG" // Should be US

**Comment by marmelroy** [comment]
Hi @redcirclegame! 

Thanks for this. The issue here is that you don't get the main country for a dealing code by asking for the first country in the array. 

There is a specific function for this:
```
let countryCode = PhoneNumberKit().mainCountryForCode(countryCodeNumber)
```

returns US

**Comment by redcirclegame** [comment]
Oh, i see, thanks for such quick response @marmelroy !
