### ISSUE TITLE
The flag on the textfield does not change after selecting the current country

### ISSUE THREAD

**Issue by Mykolareclip** [marmelroy/PhoneNumberKit#540]
## What did you do?
1. Open CountryCodePicker
2. Select current country

## What did you expect to happen?
The flag on the texifield has changed to the correct one

## What happened instead?
Flag on texifield hasn't changed

## Environment
**Phone number kit version 3.4.3

**Comment by AndrewSB** [comment]
+1

this worked in 3.4.2, seems to be broken in 3.4.3

**Comment by bguidolim** [comment]
Hey @petermolnar-dev !

If you don't mind and have some time, could you look at this issue? It seems to be related to the metadata update.

I think this issue is also related to this comment:
https://github.com/marmelroy/PhoneNumberKit/issues/447#issuecomment-1187598818

**Comment by petermolnar-dev** [comment]
Sure, I will try to take a look on it today.

**Comment by bguidolim** [comment]
https://github.com/marmelroy/PhoneNumberKit/pull/541 might fix this issue

**Comment by petermolnar-dev** [comment]
> #541 might fix this issue

Indeed, based on my tests that branch has the right solution. Good job @bguidolim !
