### ISSUE TITLE
Build error when using PhoneNumberKit in macOS, starting from commit acf9292

### ISSUE THREAD

**Issue by olleraab** [marmelroy/PhoneNumberKit#549]
CNContactsUserDefaults is only available in macOS 10.11 or newer. However the PhoneNumberKit Swift Package supports macOS 10.10 and up. Hence I get a compilation error. CNContactsUserDefaults was introduced 15 july 2022 in commit acf9292.

**Comment by rmdan90** [comment]
Facing the same issue.
