### ISSUE TITLE
Saint Martin (SX) country code is wrong

### ISSUE THREAD

**Issue by alexsteed** [marmelroy/PhoneNumberKit#558]
I double checked the country code for Saint Martin [on google](https://www.google.com/search?client=safari&rls=en&q=saint+martin+country+code&ie=UTF-8&oe=UTF-8) and it seems to be `590` and not `1` as it appears in the library.

**Comment by petermolnar-dev** [comment]
Hey @alexsteed ,
Can you give us a bit more context, how we can reproduce/test it, please? 
As I can see there are 2 parts of Saint Martin, the French and the Dutch part. I assume that the SX is the Dutch part, and seems that it has the 1 for the prefix. For the French part (MF) the country code is 590. 

I have a feeling that it goes back to the same issue with the metadata from Google, but would be great if you can provide some help to identify where it is getting wrong.

**Comment by alexsteed** [comment]
Hello @petermolnar-dev,
My apologies I didn't know there was two part in Saint-Martin, the metadata is actually valid. I was using the wrong country id.

Thank you guys for this library and have a nice day !
