### ISSUE TITLE
Please add a validation for phone number for Nepal 

### ISSUE THREAD

**Issue by sthahemant** [marmelroy/PhoneNumberKit#559]
Please add +977 97******** as valid phone number. Currently it shows invalid number but this number is valid

**Comment by petermolnar-dev** [comment]
Hi @sthahemant,
Unfortunately with this project we are relying on the Google metadata. Could you make it sure that your number is validated OK with Google's test site on https://libphonenumber.appspot.com, please? If you can provide us a valid looking, but not used number that would be great as well. 

If the Google test page is not validating your number, please open a request on their repository: https://github.com/google/libphonenumber, and when they update their metadata, this repo will update as well.
