### ISSUE TITLE
Number phone template from region 

### ISSUE THREAD

**Issue by HamzaGhazouani** [marmelroy/PhoneNumberKit#57]
Hey Roy,

Firstly thank you for this nice library.
I look for the phone number template from region to show it in the placeholder of the text field 
Do you know how we can do that ? 

Example from Google PhoneNumber API  : 
```
// Produces "011 41 44 668 1800", the number when it is dialed in the United States.
System.out.println(phoneUtil.formatOutOfCountryCallingNumber(swissNumberProto, "US"));
```
Thank you for your help 

Hamza

**Comment by marmelroy** [comment]
Hi @HamzaGhazouani, I would recommend formatting the phone number with a PhoneNumber object (providing the US as the region) and using the formatted number as the placeholder. 

```
PhoneNumber(rawNumber: "1234567890", region: "US")
```
