### ISSUE TITLE
Restricted Countries 

### ISSUE THREAD

**Issue by AdieOlami** [marmelroy/PhoneNumberKit#570]
Hi, is it possible to restrict countries to just desired ones more like countries where the app is available.

**Comment by Amnell** [comment]
Just stumbled across PhoneNumberKit and started exploring the features. It's a pity no one has given you a clear answer, but from what I can see you have two feasible options that does not involve any forking or too heavy modification:

# Set `commonCountryCodes`
You can set the commonCountry codes to add a new section at the top of the picker. This section will only contain the countries for the country codes you supply. It will not however hide any countries.

Example: 
[examples/AsYouType/Sample/ViewController.swift#L26](https://github.com/marmelroy/PhoneNumberKit/blob/1ef0431b971f69c48ca5eb4cdba07f2c5da54c35/examples/AsYouType/Sample/ViewController.swift#L26)

# Supply a different `MetadataCallback` to `PhoneNumberKit.init(metadataCallback:)`
PhoneNumberKit can be initialized with a `MetadataCallback`. This is just a type alias for `(() throws -> Data?)` and you can supply whatever function that returns valid data.

The default implementation uses [`PhoneNumberKit.defaultMetadataCallback`](https://github.com/marmelroy/PhoneNumberKit/blob/227a7122c662bbd9a56a567948dc7f812b8cb0b6/PhoneNumberKit/PhoneNumberKit.swift#L323) which just loads all metadata from a big JSON file:

``` swift
public static func defaultMetadataCallback() throws -> Data? {
    let frameworkBundle = Bundle.phoneNumberKit
    guard let jsonPath = frameworkBundle.path(forResource: "PhoneNumberMetadata", ofType: "json") else {
        throw PhoneNumberError.metadataNotFound
    }
    let data = try Data(contentsOf: URL(fileURLWithPath: jsonPath))
    return data
}
```

Now, what you can do is either:

- Create your own metadata file and write your own function that reads that file and returns it as Data? This is the most performant way. Although might be somewhat of a pain to edit the json and also maintain it as you'll need to keep it up to date.
- Load the existing `PhoneNumberMetadata.json` file. Filter the data to only contain whatever territories you want, and then map back to Data?. Less performant, a bit ugly, but quite easy.

Example:

``` swift
public static func myFilteredMetadataCallback() throws -> Data? {
    // Get the default data
    guard let data = try PhoneNumberKit.defaultMetadataCallback() else {
        throw PhoneNumberError.metadataNotFound
    }

    // Map to dictionary and filter
    var filteredTerritories: [[String: Any]] = []
    if
        let dictionary = try JSONSerialization.jsonObject(with: data, options: []) as? [String: Any],
        let phoneNumberMetadata = dictionary["phoneNumberMetadata"] as? [String: Any],
        let territories = phoneNumberMetadata["territories"] as? [String: Any],
        let territory = territories["territory"] as? [[String: Any]]
    {
        filteredTerritories = territory.filter({
            guard let id = $0["id"] as? String else { return false }
            // Here's the ID's
            return ["SE", "GB", "DK", "FI", "NO", "DE"].contains(id)
        })
    }

    // Recreate dictionary structure
    let dictionary = [
        "phoneNumberMetadata": [
            "territories": [
                "territory": filteredTerritories
            ]
        ]
    ]

    // Convert to data
    return try JSONSerialization.data(withJSONObject: dictionary, options: [])
}
```

And then just using it like:

``` swift
PhoneNumberTextField(withPhoneNumberKit: PhoneNumberKit(metadataCallback: Additions.myFilteredMetadataCallback))
```

Now, that works, BUT depending on how many Countries you include the UI may look quite bad:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/104110/210181753-bbfcd74a-5692-49f8-9a9f-7675c58cf3cd.png">

I believe fixing that would be more challenging.

Related issue: #443
