### ISSUE TITLE
Phone number parsing issue

### ISSUE THREAD

**Issue by PrzemekCackowski** [marmelroy/PhoneNumberKit#584]
I encountered phone number parsing issue when trying to parse the phone number which is invalid but prefix of this number is valid country code and rest of the number is valid phone number. See an example:

Angola phone numbers are valid if they start with 2 or 9 and have nine digits, so the number 376365828 is invalid for country code AO (+244), but +376 is the Andora country code. 

I noticed that PhoneNumberKit `isValidPhoneNumber` and `parse`, returns that 376365828 is valid number for country code `AO` but it should not. I think this part of `parse` method:
```
            if numberStringWithPlus.first != "+" {
                numberStringWithPlus = "+" + numberStringWithPlus
            }
```

changes the logic because it adds "+" sign at the begining of phone number and then is parsing "+376365828" number which occurs to be valid Andora number. I think `isValidPhoneNumber` and `parse` should not behave like this. As a workaround I used `parseMultiple` method which does not have a additional logic and it seems to be working correctly. But not sure if that was an intension. Please check and advise.

**Comment by PrzemekCackowski** [comment]
Is there a chance for fixing this bug?

**Comment by bguidolim** [comment]
It might be already fixed in the latest version.

**Comment by PrzemekCackowski** [comment]
@bguidolim it seems it is still the issue, parsing the Angolan wrong number `+244376365828` leads finally to parsing +376365828 which is Andorran correct number. and finally, it does not throw an error that provides misleading results. Method `parseMultiple` seems to be working correctly on this example.
