### ISSUE TITLE
Upgrade libphonenumber

### ISSUE THREAD

**Issue by DelphineGarcia** [marmelroy/PhoneNumberKit#587]
We have a lot of Australian number that are marked as not valid (and they shouldn't). 
It seems that it was a bug on libphonenumber and they fixed it (https://issuetracker.google.com/issues/259292923)

Is there any plan to upgrade libphonenumber soon?

Thanks a lot

**Comment by bguidolim** [comment]
Hey @DelphineGarcia 

The lib is already using the latest version.

**Comment by DelphineGarcia** [comment]
Great, thanks you so much !

**Comment by DelphineGarcia** [comment]
Actually this issue is marked as fixed but is not included in the 8.13.1. Let's wait the next metadata version 😭
