### ISSUE TITLE
Can we programatically set country code in the textfield?

### ISSUE THREAD

**Issue by arjun-ps** [marmelroy/PhoneNumberKit#588]
I need to programmatically set the country code of the text field. Is that possible?

**Comment by VijayRadake-Credenceid** [comment]
Try to use 
 
phoneTextField.partialFormatter.defaultRegion = "IN"

You can pass region programatically

**Comment by limitMe** [comment]
> Try to use
> 
> phoneTextField.partialFormatter.defaultRegion = "IN"
> 
> You can pass region programatically

Seems this only affects `defaultRegion`, while `currentRegion` will still override `defaultRegion`.
