### ISSUE TITLE
Not working in Simulator

### ISSUE THREAD

**Issue by tecexpert** [marmelroy/PhoneNumberKit#59]
When I type "+" followed by "9", the "+" sign disappears.
So instead of "+9" , it only shows "9".

It is working fine on my iPhone 5s, iOS 9.3.3 though.

Xcode Version: 7.3

**Comment by marmelroy** [comment]
Hi @tecexpert, I'm afraid I can't replicate. Can you please share more details?

**Comment by marmelroy** [comment]
Closing due to lack of reproducible steps.
