### ISSUE TITLE
Cocoapods Integration - 3.5.7 not avilable

### ISSUE THREAD

**Issue by Benny-iPhone** [marmelroy/PhoneNumberKit#607]
Latest version I was able to integrate using `cocoapods` is `3.3.4`

**Podfile**
`pod 'PhoneNumberKit', '~> 3.0'`

**Terminal Output**
_$pod install --repo-update_
```
...
Installing PhoneNumberKit (3.3.4)
...
```

**Comment by KobbySkywalker** [comment]
If you want the latest version, you can ditch the version approximation '~> 3.0'
`pod 'PhoneNumberKit'` and try again

**Comment by bguidolim** [comment]
Actually, you should use:

`pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit'`

This way you can use directly from the repo since I'm not able to publish on Cocoapods CDN.
