### ISSUE TITLE
US phone number format with parenthesis

### ISSUE THREAD

**Issue by eliasalzaghrini** [marmelroy/PhoneNumberKit#609]
Hello, I am parsing a phone number and formatting it to US format, I want to get +1(857)887-8837, but instead, I am getting +1 857-887-8837.

```
let phoneNumberKit = PhoneNumberKit()

        do {
            let phoneNumber = try phoneNumberKit.parse(self, withRegion: "US", ignoreType: true)
            return phoneNumberKit.format(phoneNumber, toType: .international)
        } catch {
            print("Generic parser error")
            return self
        }
```

**Comment by KobbySkywalker** [comment]
PhoneNumberKit doesn't make provision for the option you are looking for (at least for now). It's either the .international type provides you the +1 alternative & .national provides you the brackets option.

I'll suggest you lean towards string manipulation in conjunction with PhoneNumberKit to help you achieve what you want. 
Eg. Retrieve the international format of the number you want using `let phoneNumber = phoneNumberKit.format(phoneNumber, toType: .international)` and then retrieve the country code for the phone number using `let countryCode = phoneNumberKit.countryCode(for: "US")` Then you can append the countryCode to the phoneNumber to give you what you prefer.
