### ISSUE TITLE
Missing country

### ISSUE THREAD

**Issue by marouenetekaya** [marmelroy/PhoneNumberKit#61]
These country are missing:
PN : Pitcairn Islands
TF : French Southern Territories
UM : U.S. Outlying Islands
AQ : Antarctica
BV : Bouvet Island
HM : Heard & McDonald Islands
GS : So. Georgia & So. Sandwich Isl.

**Comment by marmelroy** [comment]
Countries are based on Google's libPhoneNumber metadata (used on Android and on the web). There's not a huge amount we can do.
