### ISSUE TITLE
3.5.7 injecting numbers

### ISSUE THREAD

**Issue by mmdock** [marmelroy/PhoneNumberKit#611]
setup: pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit', :tag => "3.5.7"

finally was revisiting [this merged issue that was resolved](https://github.com/marmelroy/PhoneNumberKit/issues/445) that I had initiated the original discussion for like, idk 2 years ago?

Basically, numbers are being injected randomly as I type.

I saw that it was fixed and was finally going to update (from version 3.3.1 to 3.5.7)

However, when trying out the UK cases I originally knew about, at least one of them is still causing issues: **_with UK country code selected, try typing all 1’s and it will eventually insert 1534 (or maybe injecting 534 an the proceeding 1 is something i am typing)_** 

All the other cases i had known about, and the other cases in the original thread all seem to be successfully resolved in 3.5.7

https://user-images.githubusercontent.com/2423465/225492368-c7dc81b7-d2bb-4ccf-be23-80da3305469f.mov

**Comment by mmdock** [comment]
@bguidolim  i use the following setup:

initializing the textField:
        phoneTextField = PhoneNumberTextField()
        phoneTextField.withPrefix = true
        phoneTextField.font = UIFont.font(forStyle: .body)
        phoneTextField.defaultRegion = regionCode //passed in
        phoneTextField.delegate
        phoneTextField.becomeFirstResponder()


extension PhoneNumberViewController: UITextFieldDelegate {
    func textFieldDidChangeSelection(_ textField: UITextField) {
        if let text = textField.text {
            do {
                let number = try phoneNumberKit.parse(text, withRegion: self.mainView.getRegion(), ignoreType: false)

                textField.text = phoneNumberKit.format(number, toType: .international, withPrefix: true)

                self.mainView.set(state: true)
            } catch {
                // Cannot format for that country? Invalid!
                self.mainView.setButton(state: false)
                self.mainView.setText(state: true)
            }
        }
    }

    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        // Disable deletions that involve the country's dialing code.
        if let text = textField.text, (!text.isEmpty && text.count <= self.mainView.getPrefixNumber().count), string.isEmpty {
            self.mainView.setButton(state: false)
            self.mainView.setText(state: true)
            return false
        } else if let text = textField.text, string.isEmpty, range.length == text.count {// deleting everything
            self.mainView.setButton(state: false)
            self.mainView.setText(state: true)
            return false
        } else if range.location <= self.mainView.getPrefixNumber().count, string.isEmpty {
            self.mainView.setButton(state: false)
            self.mainView.setText(state: true)
            return false
        }

        self.mainView.setButton(state: false)
        self.mainView.setText(state: true)
        return true
    }
}

**Comment by mmdock** [comment]
it looks like this piece of code is the issue:
`textField.text = phoneNumberKit.format(text, toType: .international, withPrefix: true)`

**Comment by aleksandraspirovska** [comment]
I also reproduce this issue with "3.7" with region Jersey "JE", I get injection of "1534". 
Also with region Guernsey "GG" I get injection of "1481".
