### ISSUE TITLE
Phone code provided separately? 

### ISSUE THREAD

**Issue by EmmaVvv** [marmelroy/PhoneNumberKit#615]
Is there any way to get a phone code apart from the number itself? 
I'd like to present flag and phone code in a separate view and then have textField for phone number only (with `withPrefix` disabled).

**Comment by tarastomchuk** [comment]
+1,

`phoneNumberKit.parse(number, ignoreType: false)` works only if full phone number is almost entered and is not detecting country codes from the start.

is it possible to make at all?
