### ISSUE TITLE
parseMultiple returns before SynchronizedArray has finished appending phone numbers

### ISSUE THREAD

**Issue by hartbit** [marmelroy/PhoneNumberKit#62]
Was getting an empty array back. I used breakpoints to see that the `SynchronizedArray.append` async call happens after `parseMultiple` returns. I there's a wait missing to wait until `SynchronizedArray`'s `accessQueue` is empty.

**Comment by marmelroy** [comment]
Hi @hartbit, sorry for the delay - was busy with the release of 1.0 and the Swift 3.0 transition. 

I do believe there is indeed an issue here - will continue to investigate.

**Comment by marmelroy** [comment]
Hey @hartbit, there were a lot of changes to parseMultiple in the last release and I believe this should be fixed by now. Let me know if you are still facing issues after updating.
