### ISSUE TITLE
iOS 16.4 breaks number parsing

### ISSUE THREAD

**Issue by jpierceMLD** [marmelroy/PhoneNumberKit#623]
According to the release notes for 16.4 :
[CTCarrier, a deprecated API, returns static values for apps that are built with the iOS 16.4 SDK or later. (76283818)](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-16_4-release-notes#Deprecations)
This apparently breaks several PhoneNumberKit functionalities. The problem area appears to be in `defaultRegionCode()`:
```swift
if #available(iOS 12.0, *) {
    carrier = networkInfo.serviceSubscriberCellularProviders?.values.compactMap({ $0 }).first
} else {
    carrier = networkInfo.subscriberCellularProvider
}

if let isoCountryCode = carrier?.isoCountryCode {
    return isoCountryCode.uppercased()
}
```
Where in prior versions `carrier` would either be a valid carrier or nil, in 16.4 the default "empty" carrier is returned with isoCountryCode = "--"

This causes cascading problems which seem to be related to the population of `defaultMetadata` and `currentMetadata`, which are now always nil.

This code no longer works:

```swift
let phoneNumberKit = PhoneNumberKit()
phoneNumberField.withPrefix = true
phoneNumberField.withExamplePlaceholder = true
phoneNumberField.text = phoneNumberKit.format(phoneNumber, toType: .international)
phoneNumberField.withFlag = true
```

where phoneNumber is a valid Italian PhoneNumber, on 16.3 the Italian flag shows correctly, on 16.4 we get an American flag with an improper format.

After entering in a new valid Italian phone number and trying to parse it:

```swift
let phoneNumber = try phoneNumberKit.parse(phoneText)
```

we get "invalidCountryCode" error

**Comment by anashkevichp** [comment]
I expercience the same issue. Basically formatting doesn't work as expected now. Pretty normal phone numbers failures to be parsed now

**Comment by anashkevichp** [comment]
@jpierceMLD, do you have a workaround to make it all work as expected?

**Comment by jpierceMLD** [comment]
@anashkevichp 

I couldn't find any way to use the framework as-is to fit my use case. I tried several workarounds like extracting the country code from the phone number and then forcing it with `phoneNumberField.partialFormatter.defaultRegion`, plus a few other things. I was able to make it functional but in the end the flag would no longer change.

So for now I am just swizzling in a method to return nil for `CTCarrier.isoCountryCode`:

```swift
import CoreTelephony

extension CTCarrier {
    
    static let classInit: Void = {
        
        guard let originalMethod = class_getInstanceMethod(CTCarrier.self, #selector(getter: isoCountryCode)),
                let swizzledMethod = class_getInstanceMethod(CTCarrier.self, #selector(swizzled_isoCountryCode))
        else { return }
        
        method_exchangeImplementations(originalMethod, swizzledMethod)
    }()
    
    @objc func swizzled_isoCountryCode() -> String? {
        nil
    }
}
```

and then call `CTCarrier.classInit` in the `AppDelegate.application(_:didFinishLaunchingWithOptions:)`

**Comment by anashkevichp** [comment]
yeah, that doesn't look very pretty... It looks like we'll need to away from `CTCarrier` as it got deprecated. thanks for sharing that!

**Comment by bguidolim** [comment]
@jpierceMLD @anashkevichp Hey folks!

You're not using the latest version of PhoneNumberKit. Since July last year, we've removed this code, which now relies on the `Contacts` framework.

Please ensure you're using the latest version and be aware that I cannot publish new versions on Cocoapods repo, so you should follow what is described in README.

**Comment by anashkevichp** [comment]
hey @bguidolim! thanks for your quick reply!
well, you're right. Thanks!

btw, why it is like that that you cannot update it on Cocoapods as well? That's really weird. You should probabbly add a warning msg to the README so it'll be absolutely obvious that with Cocoapods you won't get the latest available version.

Thanks again!

**Comment by jpierceMLD** [comment]
Yes @bguidolim thanks for the quick reply. Migrating to SwiftPM has fixed it. 

Not quite sure I understand your comments about Cocoapods though. Cocoapods is listed as a valid installation method on the README. So I concur it should be removed from the README and maybe a note that says Cocapods users should migrate because to update my libs I use `pod outdated` to get a report of what needs to be updated, very convenient but in this case a time-consuming mistake! :-)

**Comment by bguidolim** [comment]
I've rights as maintainer only with no rights to upload to Cocoapods, and @marmelroy (author) is not answering anymore.

On README, you can see that the parameter `git` is there to force Cocoapods to use the `Podspec` directly from the repo.

However, you both are right, I will add a warning explaining this. Or feel free to do so and I will merge it right away.

**Comment by bguidolim** [comment]
FYI: I've now contact the Cocoapods team to check if they can help with to get access to publish.
