### ISSUE TITLE
Phone number parse not working in iOS 16.4.1

### ISSUE THREAD

**Issue by Elamuruga** [marmelroy/PhoneNumberKit#626]
@marmelroy  Phone number parsing returns false in all given mobile numbers with country codes.

Could anyone help me to resolve this issue Asap? Thanks in advance.

**Comment by bguidolim** [comment]
Please make sure you're using the latest version. If you're using Cocoapods, add in your Podfile as described on README.

**Comment by Elamuruga** [comment]
> Please make sure you're using the latest version. If you're using Cocoapods, add in your Podfile as described on README.

@bguidolim Thank you for your right help at right time. I am using an older version by using  **pod 'PhoneNumberKit'**  After your guide only I noted and updated to new **pod 'PhoneNumberKit',: git => 'https://github.com/marmelroy/PhoneNumberKit'** Now my issue is solved. Once again thank you.
