### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=4099

### ISSUE THREAD

**Issue by AleksandrShevachenko** [marmelroy/PhoneNumberKit#630]
When I try parse ("(try? phoneNumberKit.parse(numberTextField.text!)) != nil") get error: [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service with pid 94 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service with pid 94 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}

**Comment by bguidolim** [comment]
https://github.com/marmelroy/PhoneNumberKit/issues/626#issuecomment-1502853566
