### ISSUE TITLE
Crash in populateTerritories() with a release build using Xcode 14.3

### ISSUE THREAD

**Issue by mungbeans2** [marmelroy/PhoneNumberKit#632]
After updating from Xcode 14.2 to 14.3 I've started getting a crash in release builds. 
Dubug builds are ok, as are release builds with 14.2, the crash only occurs if uploading a build to Testflight, or setting the run scheme to release.

The crash occurs calling parse() as below (the actual phone number used is irrelevant)

```
      do {
        let phoneNumberKit = PhoneNumberKit()
        let phoneNumber = try phoneNumberKit.parse("263537874", withRegion: "us", ignoreType: true)
      } catch {
      }
```

The try metadataCallback() line below crashes with  EXC_BAD_ACCESS (code=2, address=0x16f23fff0)

```
    private func populateTerritories(metadataCallback: MetadataCallback) -> [MetadataTerritory] {
        var territoryArray = [MetadataTerritory]()
        do {
            let jsonData: Data? = try metadataCallback()
            let jsonDecoder = JSONDecoder()
            if let jsonData = jsonData, let metadata: PhoneNumberMetadata = try? jsonDecoder.decode(PhoneNumberMetadata.self, from: jsonData) {
                territoryArray = metadata.territories
            }
        } catch {
            debugPrint("ERROR: Unable to load PhoneNumberMetadata.json resource: \(error.localizedDescription)")
        }
        return territoryArray
    }
```

**Comment by bguidolim** [comment]
Please, try to use the `master` branch and let me know if it fixes the issue. PR #620 might fix this.

**Comment by mungbeans2** [comment]
Seems good now, thanks

**Comment by bojanstef** [comment]
@bguidolim @mungbeans2 still crashing for me in a Release build with v3.5.9
