### ISSUE TITLE
Fails to parse numbers from Thailand (+66)

### ISSUE THREAD

**Issue by alexnivanov** [marmelroy/PhoneNumberKit#635]
Throws an exception on `parse` function. Example number: `+66999999999` (works fine with PhoneNumberUtil from Google).

**Comment by itd-vladislav-k** [comment]
Looks like this issue is not only with Thai phone numbers, bit with any of the. It throws `PhoneNumberKit.PhoneNumberError.invalidCountryCode`

**Comment by alexnivanov** [comment]
True that :O I think some of the updates broke it...

**Comment by itd-vladislav-k** [comment]
Fixed with version 3.5.9
