### ISSUE TITLE
Is there a way to identify numbers from text 

### ISSUE THREAD

**Issue by GOKUXGOD** [marmelroy/PhoneNumberKit#637]
Is there a way to extract number from text For ex: 
Input string 
`My number is +916462910456 and you can call me on +919832434565,  so i can get  `

`+916462910456 919832434565`

I can find a similar implementation on the android version of the same library 
https://github.com/google/libphonenumber

It has a function 
`PhoneNumberUtil.findNumbers(str: String, region: Region)`

it returns a list of numbers in the input string 

Can anyone help with a way to attain a similar functionality in swift

**Comment by bguidolim** [comment]
@GOKUXGOD PNK doesn't support this, but you can use [`NSDataDetector`](https://developer.apple.com/documentation/foundation/nsdatadetector) for this.
