### ISSUE TITLE
How to consume latest versions in a podspec file?

### ISSUE THREAD

**Issue by acoutts-nydig** [marmelroy/PhoneNumberKit#638]
Hi - I'm the maintainer of https://github.com/bottlepay/flutter_libphonenumber which wraps this package on iOS to expose phone number parsing in iOS for Flutter apps.

To make it convenient and consistent, the podspec file defines what eversion of PhoneNumberKit is used. But now that it's required to use git, i need to require users to add it to their pod file which is not ideal.

https://github.com/bottlepay/flutter_libphonenumber/blob/main/packages/flutter_libphonenumber_ios/ios/flutter_libphonenumber_ios.podspec

is there any way to lock the version in the podspec? The last version I see uploaded to cocoapods is 3.3.4.

**Comment by bguidolim** [comment]
Unfortunately, I am not able to update the version on official Cocoapods repo. I don't have access to this.

I've contacted the author and the Cocoapods team, with no success.

I don't know what else I can do to fix it.

**Comment by acoutts-nydig** [comment]
Got it!

I resolved it by
* setting the version in my package's podspec:

```
s.dependency "PhoneNumberKit/PhoneNumberKitCore", "3.5.9"
```

and then consumers of the plugin just have to add the pod to their Podfile:

```
pod "PhoneNumberKit", :git => "https://github.com/marmelroy/PhoneNumberKit"
```

and the versioning works like expected.

**Comment by acoutts** [comment]
I see it was updated - does this mean you have access to cocoapods again? I found my above approach doesn't work because as soon as you push a new git tag and the latest master commit doesn't match the version i'm requesting, cocoapods says it can't find the pod.

https://github.com/acoutts/flutter_libphonenumber/pull/51

**Comment by bguidolim** [comment]
@acoutts Yes, I finally got access to the Cocoapods trunk for PhoneNumberKit. Any new updates will be accordingly pushed to Cocoapods.
