### ISSUE TITLE
Invalid US phone number incorrectly parsed as valid international number

### ISSUE THREAD

**Issue by lyoshenka** [marmelroy/PhoneNumberKit#640]
phoneNumberKit.parse sometimes treats an invalid US number as a valid international number when the first part of the number matches a country code.

Here's a test that reproduces the issue. Both should pass, but only first assert passes while the second fails. This happens because 212 is not a country code while 352 is the country code of Luxembourg.

```
func testRegionCountryCodeConflict() {
    XCTAssertThrowsError(try phoneNumberKit.parse("212-2344", withRegion: "US")) { error in
        XCTAssertEqual(error as? PhoneNumberError, PhoneNumberError.notANumber)
    }
    XCTAssertThrowsError(try phoneNumberKit.parse("352-2344", withRegion: "US")) { error in
        XCTAssertEqual(error as? PhoneNumberError, PhoneNumberError.notANumber)
    }
}
```

**Comment by bguidolim** [comment]
Maybe duplicate #623

**Comment by lyoshenka** [comment]
@bguidolim i don't think so. #623 is marked as closed but this test still fails on master

**Comment by bguidolim** [comment]
@lyoshenka I've fixed the issue on PR #652. Do you want to take a look?

**Comment by lyoshenka** [comment]
@xezero this fixes an annoying bug we had. consider bumping phonenumberkit to v3.6

**Comment by lyoshenka** [comment]
thanks for the fix @bguidolim
