### ISSUE TITLE
PartialFormatter doesn't work on iOS 16.4.1

### ISSUE THREAD

**Issue by sargismkhitaryan** [marmelroy/PhoneNumberKit#641]
On iOS 16.4.1 on real device PartialFormatter().formatPartial("+33689017383") returns "33689017383" but it supposed to return "+33 6 89 01 73 83".

**Comment by workhitesh** [comment]
I can confirm that the same is happening for me for iOS 16.4.1

**Comment by sargismkhitaryan** [comment]
@Vaberer I found a solution. I suppose you used PhoneNumberKit as me (pod 'PhoneNumberKit') which install  version (3.3.4).

**Comment by EugeneEl** [comment]
You can use CocoaPods specifying exact commit to `3.5.9` 

`   pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit.git', :commit => '6edd6e38a30aec087cb97f7377edf876c29a427e'`

**Comment by Vaberer** [comment]
Got it, that would be nice to update pod repo with the latest PhoneNumberKit version. The workaround for the exact commit will solve the problem for now. Thanks

**Comment by Vaberer** [comment]
Can you guys push the newest pod version to by using pod trunk push command? If you just bump the version number, cocoa pods won't use the newest version

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by bguidolim** [comment]
Already tried. I don't have access and neither @marmelroy or the Cocoapods team answered me.

**Comment by bguidolim** [comment]
I've received an answer from the Cocoapods team. Seems they will give me access to push new versions soon.

**Comment by bguidolim** [comment]
I'm finally able to push versions to Cocoapods.
