### ISSUE TITLE
Can't pod install on version 3.5.10

### ISSUE THREAD

**Issue by haitacnj** [marmelroy/PhoneNumberKit#643]
I set up the deployment target of both the App and Pod to 14.0. I tried to change the deployment target but it still didn't work!
![Screenshot 2023-05-17 at 11 30 25](https://github.com/marmelroy/PhoneNumberKit/assets/3365969/ab33b603-4245-4720-8a61-cfc018b37b13)

**Comment by acoutts-nydig** [comment]
I'm having that error when i try to depend on 3.5.9, but 3.5.10 works. Not sure why we can't depend on 3.5.9 anymore but seems to work if I just depend on the new version now.
