### ISSUE TITLE
Argentina numbers validation

### ISSUE THREAD

**Issue by EmmaVvv** [marmelroy/PhoneNumberKit#649]
Hi,
We're unable to parse Argentina mobile numbers based on the regex of the library. 

Here are the couple of examples which are not valid based on regex check: 

(380) 15 123-4567 La Rioja.
(2966) 15 12-3456 Río Gallegos.

As far as I understood only 9 11 - XXXX - XXXX pattern is valid, but is it enough to cover all possible Argentina mobile numbers?

**Comment by bguidolim** [comment]
Which version?
If you're using Cocoapods, make sure that you're using the example described on README, with the `git` configuration.

**Comment by EmmaVvv** [comment]
version 3.5.8

We've also updated to 3.5.10 thinking that might be a bug, but still nothing. Majority of Argentina numbers are considered as not valid. 
`try phoneNumberKit.parse(string)` returns nil for all Argentina numbers except the ones that match placeholder pattern

**Comment by bguidolim** [comment]
The numbers you've mentioned are not valid for libPhoneNumber.
You can check it here: https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html

The results are supposed to be the same with PNK.

**Comment by EmmaVvv** [comment]
Thanks for you reply
We're facing another issue with Argentina phone numbers, mask is not matching the actual number formatting 
Let me attach screeshots
Below is the mask from framework (9 11 2345-6789)

![1](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/ec44aee5-d3fd-469a-9004-6c87b49d54cd)

Here is how phone number formatting looks based on the mask 
![2](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/f6cb8779-158e-40d1-951e-38e5eaef4a9b)

And here is how formatting work (properly) without 9 at the beginning 

![3](https://github.com/marmelroy/PhoneNumberKit/assets/53192422/e3f28bde-13df-4d86-bd5a-61a8b18370c7)

Why is it like that?

**Comment by DimDL** [comment]
FAQ Article about Argentina: https://github.com/google/libphonenumber/blob/master/FAQ.md#why-is-this-number-from-argentina-ar-or-mexico-mx-not-identified-as-the-right-number-type
