### ISSUE TITLE
Input Mask Incorrect for Area Codes Starting with 3

### ISSUE THREAD

**Issue by Appswage** [marmelroy/PhoneNumberKit#651]
Version 3.5.10 installed with SPM.  iOS 16.5. 

When entering any number that has a 3xx area code, the on-screen formatting is off. For example, it will look like (3105551212.  Any other number looks like (210) 555-1212. The components of the phone appear correct behind the scenes, but the on-screen formatting when typing is incorrect. Seems to only be with area codes beginning with 3. If I specifically start with +1 and then go to an area code starting with 3, it will work correctly. Again not required for any other area code.

**Comment by bguidolim** [comment]
Can you check what is the default region when you first try to format the number without the country code?

**Comment by bguidolim** [comment]
I'll investigate it as well.

**Comment by hypermobileshop99** [comment]
@bguidolim Any updates on this issue? Can you please let me know when you think this issue will be resolved?

**Comment by bguidolim** [comment]
I'm not able to reproduce this issue.
On version 3.6.1, there is a fix related to the `PartialFormatter`, used for the `PhoneNumberTextField`. Could you please take a look at this version?

**Comment by Appswage** [comment]
I can confirm that the issue is still present in 3.6.1. However, I found then if I changed the phone's Region (via the iPhone's setting's Language & Region) to say Germany, then it worked fine. So the issue is present when setting region to United States. Of course other countries may also have that issue but clearly some, like Germany, do not.

**Comment by bguidolim** [comment]
@Appswage is it reproducible on the simulator or only on a physical device? Which iOS version are you seeing this?
Unfortunately, I'm still not able to reproduce this issue. Tried on simulator (16.4) and physical device (16.5)

**Comment by bguidolim** [comment]
I hope it doesn't get embarrassing, but I'm still unable to reproduce the issue.
I've used the code above, with and without the delegate. I've set the region and language. None of these made me reproduce the issue.

I kindly ask you to provide a small running project with the issue, preferably reproducible using the simulator, with the following information:
- Xcode version
- iOS version
- Exact steps to reproduce

**Comment by Appswage** [comment]
Xcode 14.3.1 (14E300c)
iOS 16.5 (actual devices) / 16.4 simulator / SwiftUI canvas (you can see the issue directly on the canvas as well)
PhoneNumberKit 3.6.1 (happened with an earlier version as well)

Type a number starting with 3. For example, the number 310-555-1212 will show in the `PhoneNumberTextField `as "(3105551212". If you type 210-555-1212 it will show in the `PhoneNumberTextField `as "(210) 555-1212" which is the expected result. Looking at the print statement as I indicated earlier will show the added "(" for numbers starting with 3. Fine for all other numbers. Also will work fine if you manually type +13105551212. Issue occurs when using region United States in the phone's settings. Works fine if region is set to "Germany". Didn't check other regions. 

Repro code is below:

```
import SwiftUI
import PhoneNumberKit

struct ContentView: View {
    @State private var phoneNumber = ""
    
    var body: some View {
        VStack {
            PhoneField(phoneNumber: $phoneNumber)
        }
        .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

struct PhoneField: UIViewRepresentable {
    @Binding var phoneNumber:String
    
    func makeUIView(context: Context) -> PhoneNumberTextField {
        let phoneKit = PhoneNumberKit()
        let phoneView = PhoneNumberTextField(withPhoneNumberKit: phoneKit)
        phoneView.delegate = context.coordinator
        phoneView.withFlag = true
        return phoneView
    }
    
    func updateUIView(_ uiView: PhoneNumberTextField, context: Context) {
        uiView.text = phoneNumber
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, UITextFieldDelegate {
        var parent:PhoneField
        
        init(_ parent: PhoneField) {
            self.parent = parent
        }
        
        func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
            let currentText = textField.text ?? ""
            print(currentText)
            parent.phoneNumber = (currentText as NSString).replacingCharacters(in: range, with: string)
            return true
        }
        
        func textFieldDidEndEditing(_ textField: UITextField) {
            parent.phoneNumber = textField.text ?? ""
        }
    }
}
```

**Comment by bguidolim** [comment]
@Appswage with the code provided, I can see the issue now. However, it's not an issue of PNK but a problem with implementing the SwiftUI wrapper. Here is a working example:

```swift
struct PhoneField: UIViewRepresentable {
    @Binding var phoneNumber: String

    func makeUIView(context: Context) -> PhoneNumberTextField {
        let phoneView = PhoneNumberTextField()
        phoneView.delegate = context.coordinator
        phoneView.withFlag = true
        phoneView.addTarget(context.coordinator, action: #selector(Coordinator.textFieldDidChange), for: .editingChanged)
        
        return phoneView
    }

    func updateUIView(_ uiView: PhoneNumberTextField, context _: Context) {
        uiView.text = phoneNumber
    }

    func makeCoordinator() -> Coordinator {
        Coordinator($phoneNumber)
    }

    class Coordinator: NSObject, UITextFieldDelegate {
        var phoneNumber: Binding<String>

        init(_ phoneNumber: Binding<String>) {
            self.phoneNumber = phoneNumber
        }

        @objc func textFieldDidChange(_ textField: UITextField) {
            phoneNumber.wrappedValue = textField.text ?? ""
        }
    }
}
```

**Comment by Appswage** [comment]
@bguidolim  - This is interesting. I played with your changes and found the only one's needed for this, versus my original code are:

`phoneView.addTarget(context.coordinator, action: #selector(Coordinator.textFieldDidChange), for: .editingChanged)`

```
@objc func textFieldDidChange(_ textField: UITextField) {
   parent.phoneNumber = textField.text ?? ""
}
```

So this issue comes down to the usage of `textFieldDidChange`

It's perplexing because it originally worked for every number other than 3 and it worked for everything when using the German locale versus the United States. There is obviously nothing in the above wrapper code dealing with either situation. I would have expected, for these changes, that the issue would be present with all phone numbers and not just the US locale. Do you have a sense, from the underlying code, why only these very specific situations (3 and US) caused this?

Thanks.

**Comment by bguidolim** [comment]
I didn't investigate further, but my region is set to Germany, and I was able to reproduce the issue.

The thing is, with the SwiftUI wrapper, you have a cyclical set using `shouldChangeCharactersInRange:`, which does not match the SwiftUI View lifecycle. So it's definitely not a good place to set a binding property.

**Comment by Appswage** [comment]
Interesting you could repro with Germany set. I had no issues with Germany set. I think if the `shouldChangeCharactersInRange` was the issue it would not only happen with numbers starting with 3. I wonder if there is some post processing going on in the SDK related to 3 (possibly due to some country code item?) that resolves the issue for the later delegate `textFieldDidChange` but not the earlier `shouldChangeCharactersInRange`. Otherwise odd given how specific this is.

Thank you for the help and your work! Danke.

**Comment by hypermobileshop99** [comment]
@bguidolim Is this solved? My project is in Swift, and I still see the issue.

**Comment by bguidolim** [comment]
@hypermobileshop99 it's not an issue with PNK.
