### ISSUE TITLE
Bad flag with "international" numbers

### ISSUE THREAD

**Issue by PaloSatala** [marmelroy/PhoneNumberKit#653]
### New Issue Checklist

- [ x] Updated PhoneNumberKit to the latest version / Specified the podspec directly from the repo
- [x ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [ x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce

1) click into the field
2) start writing a number, starting with one of the prefixes: +800, +808, +870, +878, +881, +882, +883, +888, +979

##### Expected result

No flag is visible, but field stays well layouted

##### Actual result

Layout of the field breaks - It tries to insert an unicode, which consists of three characters, what breaks the layout

**Comment by UtkuDalmaz** [comment]
Same here, messed after the last update

**Comment by PaloSatala** [comment]
Yeh, both are sollutions, however, removing that prefixed may limit functionality - I am not sure, how often are they used. 
Locally I used this simple:
var flag = self.currentRegion
            .uppercased()
            .unicodeScalars
            .compactMap { UnicodeScalar(flagBase + $0.value)?.description }
            .joined()
        if flag.count > 1 {
            flag = ""
        }
        
        on l. 291 - PhoneNumberTextField
