### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by rastaman111** [marmelroy/PhoneNumberKit#667]
Hello
I noticed that several default phones on the simulator cannot be formatted and fall into the сatch

I'm using the latest version, but it was before

Maybe these numbers are wrong.

<img width="653" alt="Снимок экрана 2023-06-26 в 11 06 47" src="https://github.com/marmelroy/PhoneNumberKit/assets/15727518/d69f0964-1885-4c20-8996-fa0e643e5808">

**Comment by rastaman111** [comment]
Although I noticed that the same numbers on the iPhone in the iPad are parsed differently
<img width="1145" alt="Снимок экрана 2023-06-26 в 16 02 06" src="https://github.com/marmelroy/PhoneNumberKit/assets/15727518/5fb1ad09-49c6-458a-adc2-8b53b22e1de1">

**Comment by bguidolim** [comment]
I will need more info to help with this, but following the example you've shared if you don't specify a region and the country code, the library will try to guess it using the region set for the simulator.

Looking at the screenshots, looks like your simulator for the iPhone has the region set to Russia and on the iPad set to US. If the phone numbers have no country code, it's possible that you get some wrong numbers there.
