### ISSUE TITLE
Impossible to handle naming collisions

### ISSUE THREAD

**Issue by jorgenfar** [marmelroy/PhoneNumberKit#668]
Hello, and thanks for your work on this project!

We are facing an issue, which is that there is a name collision between another `PhoneNumber` type in our project, and the `PhoneNumber` provided by PhoneNumberKit. For reasons that are not very interesting to go into here, it is not a possible solution to typealias the other `PhoneNumber` type.

I would like to fix this issue by typealiasing PhoneNumberKit's `PhoneNumber`, doing something like this:
```swift
import PhoneNumberKit

typealias PhoneNumberKitNumber = PhoneNumberKit.PhoneNumber
```

The reason this is not possible, is that PhoneNumberKit exports a _type_ called `PhoneNumberKit`, which means that we cannot namespace any imports from PhoneNumberKit; the compiler thinks we are referring to the type, and not the module. 

To fix this, I would like to open a PR that renames the `PhoneNumberKit` type exported --- suggestions for a new name are welcome.

**Comment by bguidolim** [comment]
Hey @jorgenfar 

Thanks for raising awareness about it.

Because of the lack of a proper name and it would be a breaking change, I still need to think I little bit more about it.
However you can fix it by creating a new file, let's call it `PhoneNumberKit+Alias.swift`, and adding the following code:

```swift
import struct PhoneNumberKit.PhoneNumber
typealias MyPhoneNumber = PhoneNumberKit.PhoneNumber
```

Or depending on your code, you can import the struct directly into the file you will use.

I hope it helps.

**Comment by jorgenfar** [comment]
> Hey @jorgenfar
> 
> Thanks for raising awareness about it.
> 
> Because of the lack of a proper name and it would be a breaking change, I still need to think I little bit more about it. However you can fix it by creating a new file, let's call it `PhoneNumberKit+Alias.swift`, and adding the following code:
> 
> ```swift
> import struct PhoneNumberKit.PhoneNumber
> typealias MyPhoneNumber = PhoneNumberKit.PhoneNumber
> ```
> 
> Or depending on your code, you can import the struct directly into the file you will use.
> 
> I hope it helps.

Thank you very much @bguidolim! I wasn't aware it was possible to selectively import like that. That indeed does solve my problem! 😄
