### ISSUE TITLE
Infinite loop on clearButtonRect

### ISSUE THREAD

**Issue by damien-nd** [marmelroy/PhoneNumberKit#670]
### New Issue Checklist

- [X] Updated PhoneNumberKit to the latest version
- [X] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [X] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

##### Expected result

Working fine in 3.6.3

##### Actual result

Infinite loop if self.insets is nil
```
    open override func clearButtonRect(forBounds bounds: CGRect) -> CGRect {
        if let insets = self.insets,
           let clearButtonPadding = self.clearButtonPadding {
            return super.clearButtonRect(forBounds: bounds.insetBy(dx: insets.left - clearButtonPadding, dy: 0))
        } else {
            return clearButtonRect(forBounds: bounds)
        }
    }
```

### Environment

Using SPM inside a Package, on Xcode 14.3 and MacOS 13.4.1

**Comment by bguidolim** [comment]
Thanks for reporting this.
