### ISSUE TITLE
Search country text field is hidden by default

### ISSUE THREAD

**Issue by rish15** [marmelroy/PhoneNumberKit#672]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
1. Click on the flag icon which opens a list of countries to choose from 
2. By default the search option is not shown at the top 
3. Pull down the screen a little bit from the top, now the search bar will be visible

##### Expected result
1. When clicking on the flag icon to select the country, by default the search bar should be visible 

##### Actual result
1. When clicking on the flag icon to select the country, by default the search bar is not visible 

### Environment
tested on iPhone 7 software version 15

**Comment by bguidolim** [comment]
Hey @rish15 

This is not a bug, but the expected behavior. Actually, this is the default behavior of iOS.
However, I've opened a PR adding a configuration option to make it always visible.

**Comment by rish15** [comment]
thanks, truly appreciate the prompt response and release. @bguidolim
