### ISSUE TITLE
Add more instructions for SPM (Dynamic vs. Static)

### ISSUE THREAD

**Issue by moubry** [marmelroy/PhoneNumberKit#679]
Idea: Add additional guidance to the SPM instructions to clarify which checkboxes they should check with adding PhoneNumberKit.

When you follow the instructions for adding PhoneNumberKit via Swift Package Manager, there’s a step you’re presented with in practice that the documentation does not mention: you’re confronted with the option of adding three Package Products:

1. PhoneNumberKit
2. PhoneNumberKit-Dynamic
3. PhoneNumberKit-Static

I’m not sure what the difference is between these, or why I might want to pick just one, or all three of these for including in my project.

**Comment by bguidolim** [comment]
Hey @moubry 
Thanks for your suggestion. Feel free to open a PR with this information.

However, it's not the responsibility of the library to explain/show the linking options available. The developer is responsible to know which is the best approach for each project.

A quick explanation:
- Using the first option, you simply let SPM automatically decide the appropriate linking strategy for the project.
- Dynamic: You explicitly tell the compiler to link it dynamically (reduce bundle size, takes more time to load in runtime)
- Static: You explicitly tell the compiler to link it statically (increase bundle size, faster)

You can get more information on the links below:
- https://bpoplauschi.github.io/2021/10/24/Intro-to-static-and-dynamic-libraries-frameworks.html
- https://bpoplauschi.github.io/2021/10/25/Advanced-static-vs-dynamic-libraries-and-frameworks.html
- https://stackoverflow.com/questions/15331056/library-static-dynamic-or-framework-project-inside-another-project
- 
I hope it helps you.
