### ISSUE TITLE
iOS 17 beta CTCarrier deprecation causes isoCountryCode to return "--" and cannot parse numbers

### ISSUE THREAD

**Issue by manta1900** [marmelroy/PhoneNumberKit#681]
### New Issue Checklist

- [ x] Updated PhoneNumberKit to the latest version
- [ x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [ x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce

            do {
                  let number = "+40 777 666 444"
                  let phone = try PhoneNumberKit().parse(number)
                  print("valid")
            } catch {
                  print("invalid")
            }

##### Expected result

Should print "valid"

##### Actual result

Prints "invalid"

### Environment

iOS 17 beta

**Comment by bguidolim** [comment]
Hey @manta1900 

Even though you have marked that you're using the latest version, it seems you're using an old version of PNK.

**Comment by manta1900** [comment]
> Hey @manta1900
> 
> Even though you have marked that you're using the latest version, it seems you're using an old version of PNK.

You are right
