### ISSUE TITLE
Wrong GB number?

### ISSUE THREAD

**Issue by mmdock** [marmelroy/PhoneNumberKit#682]
### New Issue Checklist
- [x] Updated PhoneNumberKit to the latest version
- [?] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce

phoneNumberKit.parse("+44111111", withRegion: "GB", ignoreType: false)

##### Expected result

invalid number 
##### Actual result

valid number

Note:
running this through both [here](https://libphonenumber.appspot.com/phonenumberparser) and [here](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)

as far as I can tell, "+44111111" is only a valid number for IM (Isle of Man), and only then as a short number.  Confused as to why this is parsing correctly for "GB"?
### Environment

tested this in the AsYouType sample,

added 

```
extension ViewController: UITextFieldDelegate {
    func textFieldDidChangeSelection(_ textField: UITextField) {
        if let text = textField.text {
            do {
                let number = try phoneNumberKit.parse("+44111111", withRegion: "GB", ignoreType: false)                
                print("ENABLE")
            } catch {
                print("disable")
            }
        }
    }
}
```
and set the delegate on the textfield.

**Comment by akilajwasala** [comment]
I need to validate phone numbers with the correct country codes. But I also have an issue `try phoneNumberKit.parse("+0424466934", ignoreType: true)` returns `The number provided is invalid` but in [here](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html) returns `Error: Invalid country calling code`. What could be the reason?
