### ISSUE TITLE
Exposing a public constructor for PhoneNumber?

### ISSUE THREAD

**Issue by nashfive** [marmelroy/PhoneNumberKit#683]
Hi,
I am following PointFree's recommandations for controlling your dependencies and this is quite cool! I am in the process of creating a controller dependency on PhoneNumberKit, but for this to work, I'd need to have a way to construct a `PhoneNumber` struct. For the moment, the library doesn't allow this. 

Would it be possible to expose it publicly ? It would help a lot for testing and having mocks for Previews.. 

I can do a pull request very quickly of course.

**Comment by bguidolim** [comment]
`PhoneNumber` is not intended to be manipulated. You can use the `parse` function to get the struct you need.
