### ISSUE TITLE
Kazakhstan phone numbers in PhoneNumberTextField

### ISSUE THREAD

**Issue by veerlorden** [marmelroy/PhoneNumberKit#688]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
When I enter Kazakhstan phone number inside PhoneNumberKit.PhoneNumberTextField, I get a Russian flag inside it. For example, I enter +7 7172 745159. If I parse the same number via PhoneNumberKit.parse() method, I get a valid KZ region. 

##### Expected result
Kazakhstan flag in textfield

##### Actual result
Russian flag in textfield

### Environment
SPM, iOS

**Comment by rastaman111** [comment]
Hello, but soon in Kazakhstan they want to introduce a new region 997

**Comment by bguidolim** [comment]
It might be already fixed with the new version.
