### ISSUE TITLE
This would have been the perfect lib.

### ISSUE THREAD

**Issue by rcfrias** [marmelroy/PhoneNumberKit#696]
I am currently using this in my project, but it was disappointing to find that it is not localizable.  Labels and colors of the CountryCodePickerViewController are not customizable.  I will have to end up re-creating the class and handling the events manually unless I've overlooked the right way to do it?  My goal is to display the labels in spanish and change the tint color to something else. Thank you.

**Comment by bguidolim** [comment]
Don't feel disappointed @rcfrias 

The good thing about open source projects is that you can always contribute with a pull request with the features you want to use.

And I will be glad to review and merge it 😃 

Happy coding!

**Comment by bguidolim** [comment]
You might want to check #697 and the strings are already localized, you just need to add the translations according to the keys used in the library.

**Comment by rcfrias** [comment]
Cool I will try it asap
