### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by yonaskolb** [marmelroy/PhoneNumberKit#699]
Is it possible to allow iOS autofill while still having `withExamplePlaceholder` on? Basically we'd like to default to the current country code but still allow autofill

**Comment by bguidolim** [comment]
It's a default behavior of UITextField when there is any value on `text` property already. AFAIK, there is not way to customize or override this.

However, I can suggest two solutions for this:
1. Create a separated country picker, so you can have the PhoneNumberTextField without the country code
2. Use the PhoneNumberField without country code and let the user type the national number (or the international number)

PhoneNumberField already detects the right region via SIM card and fallbacks to the current region set on iOS, so you shouldn't have any problem with letting the user type the national number.

**Comment by bguidolim** [comment]
@yonaskolb can you check if the PR #707 solves your issue?
