### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by clintburgos** [marmelroy/PhoneNumberKit#70]
Will you guys be migrating this to Swift 3?

**Comment by doublesA** [comment]
Having similar error. Version 0.8.5 isn't compiling correctly with swift 3.

**Comment by clintburgos** [comment]
I got it to compile by making a few changes myself. Hopefully we get an official update though.

**Comment by marmelroy** [comment]
Happy to hear @clintburgos. Official Swift 3 version should be ready sometime next week.

**Comment by codytwinton** [comment]
@marmelroy - Any update on the official Swift 3 release?

**Comment by marmelroy** [comment]
It's in active development. You can follow the progress on https://github.com/marmelroy/PhoneNumberKit/tree/1.0

**Comment by marmelroy** [comment]
Released 🚀
