### ISSUE TITLE
Emoji/Flag rendering is broken on iOS 17 (Encoding problems)

### ISSUE THREAD

**Issue by sniperosx** [marmelroy/PhoneNumberKit#703]
### Steps to reproduce

Create a PhoneNumberTextField in IB and setup by using outlet:

```
PhoneNumberKit.CountryCodePicker.commonCountryCodes = ["DE", "AT", "CH"]        

phoneNumberTextField.becomeFirstResponder()
phoneNumberTextField.withFlag = true
phoneNumberTextField.withPrefix = true
phoneNumberTextField.withExamplePlaceholder = false
```

##### Expected result
The text field is rendered like on iOS 16. Showing flag, showing plus sign and the number (placeholder)

##### Actual result
The text field renders missing characters. Assumption that the font has changed on iOS 17.
The flag and the plus sign is affected

### Environment
iOS 17.0 Simulator
Swift 5 
Version: 3.7.2

![Simulator Screenshot - iPhone 14 Pro - 2023-09-26 at 10 56 44](https://github.com/marmelroy/PhoneNumberKit/assets/738515/14b229bb-5785-47ad-9e53-d442d92463f9)

**Comment by bguidolim** [comment]
Hey @sniperosx 

Thanks for reporting it, however I'm not able to reproduce this issue on the demo AsYouType with the same configuration you just described.

Using Xcode 15 and set the deployment target to iOS 17 to make sure.

**Comment by sniperosx** [comment]
Hi @bguidolim, thanks for your fast feedback!
You had the right nose. I was still on Xcode 14 with the iOS 17 beta because of OS X 10.3 (not auto updated?!). 
Since Xcode 15 everything runs as usual. So definitely not a framework problem!

Thank you for the hint. 
Many greetings
