### ISSUE TITLE
Project not build when use this library

### ISSUE THREAD

**Issue by Amid666** [marmelroy/PhoneNumberKit#709]
<img width="1082" alt="Знімок екрана 2023-10-04 о 12 12 14" src="https://github.com/marmelroy/PhoneNumberKit/assets/101818262/1ed508dc-11d1-4f98-9d48-c540fbd6cf5a">
When I build project I have this error. I use version 3.7.4, what I do wrong?

**Comment by AlexanderBondar** [comment]
try to use -   pod 'PhoneNumberKit', '3.7.0'

**Comment by bguidolim** [comment]
I will need some more information to help here, like:
 - Which dependency manager are you using?
 - Have you tried to clean the cache and integrate the new version again?

**Comment by zakblacki** [comment]
I can also confirm project not build when use this library except different error :
 `Compiling for iOS 11.0 but module PhoneNumberKit has a minimum deployment target of 12.0`
although I'm doing this in the context of flutter, except that on my pod file I'm already using platform :ios, '12.1'
and on xcode target runner I'm also using ios minimum deployment target 12.1
also tried cleaning build and updated my cocopad and brew
