### ISSUE TITLE
PhoneNumberTextField issue with US default region.

### ISSUE THREAD

**Issue by SiNBizkit** [marmelroy/PhoneNumberKit#71]
I have an issue with PhoneNumberTextField with US region. I want to input some dummy phone number like 12065554444. But when I input the second character the textfield prepend it with one more "1" character - 1 12. Is that correct behavior?

**Comment by marmelroy** [comment]
Hi @SiNBizkit,

Good find! This is indeed a bug, caused by the Swift 3.0 transition. Fix pushed to the Swift 3.0 branch.
