### ISSUE TITLE
Formatting phone number without dash ("-")

### ISSUE THREAD

**Issue by kienwei518** [marmelroy/PhoneNumberKit#715]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
Pass a phone number to textField.text or type any phone number.  The number come out with a dash e.g. +60 012-3456789

##### Expected result
An option to apply phone number format  by modifying the MetadataPhoneNumberFormat's format value

##### Actual result
All number is come with "-"

### Environment
I able to modify the replaceStringByRegex method by replacing "-" with empty string. However, this code will gone every time I pod install/update. Is there any better solution ?
<img width="839" alt="Screenshot 2023-10-19 at 4 18 49 PM" src="https://github.com/marmelroy/PhoneNumberKit/assets/96861996/f607b0e6-6d2b-4031-b8e6-acdf93959a05">

**Comment by bguidolim** [comment]
It comes from the metadata, as you can check by yourself on JavaScript version.
You might need to change it in a higher level.

**Comment by kienwei518** [comment]
> It comes from the metadata, as you can check by yourself on JavaScript version.
> You might need to change it in a higher level.

By modifying in JavaScript version, it still will gone when I pod install/update right ?
