### ISSUE TITLE
Invalid phoneNumber if no prefix (+, 00)

### ISSUE THREAD

**Issue by zeljkomarinkovic** [marmelroy/PhoneNumberKit#717]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
```swift
        do {
            let number = "46789789789"
            let phoneNumber = try PhoneNumberKit().parse(number)
            print("phoneNumber: \(phoneNumber)")
        } catch {
            print("FAILED")
        }
```

##### Expected result
Valid phoneNumber

##### Actual result
invalid phoneNumber

I've noticed that there is some issue with Swedish phone numbers.

For example 46789789789. This number will return invalid phoneNumber when trying to parse but if we add prefix like + or 00 it will be valid phoneNumber.

Of course instead parsing number I can parse `try PhoneNumberKit().parse("+\(number)")`, but not sure if that's the point.

**Comment by bguidolim** [comment]
The JavaScript version is also throwing invalid number. You should always check there as source of truth.
