### ISSUE TITLE
Build fails with default target library linking configuration

### ISSUE THREAD

**Issue by qwright10** [marmelroy/PhoneNumberKit#718]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [ ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce

- Add PhoneNumberKit as a dependency through SPM
- Build project for macOS w/ Apple Silicon (cannot confirm for Intel/Universal)

##### Expected result

- Project should build without changes to target build configuration
- Project *does* build successfully if "PhoneNumberKit-Dynamic" and "PhoneNumberKit-Static" are removed from "Link Binary With Libraries" under target Build Phases, leaving only "PhoneNumberKit"

##### Actual result

- Build fails with error:
```
clang: error: no such file or directory: '/Users/lcadmin/Library/Developer/Xcode/DerivedData/[...]/Build/Products/Debug/PackageFrameworks/PhoneNumberKit-Dynamic.framework/Versions/A/PhoneNumberKit-Dynamic'
```

### Environment

Building for Apple Silicon macOS
Added through SPM

**Comment by bguidolim** [comment]
I understand your confusion, however, this is actually to be expected. When adding a dependency that offers both Dynamic and Static options, it's necessary to choose just one.

What you've done is indeed correct. You appropriately removed "PhoneNumberKit-Dynamic" and "PhoneNumberKit-Static" from the "Link Binary With Libraries" to maintain the default SPM option. Alternatively, you could choose to keep only Dynamic or only Static.

Ultimately, the choice should be guided by the specific requirements of your app. Hope this clarifies the matter for you.
