### ISSUE TITLE
Invalid Number is getting parsed: +5763252999

### ISSUE THREAD

**Issue by ngup4523** [marmelroy/PhoneNumberKit#723]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
Parse +5763252999 

##### Expected result
Should return invalid number since Colombia(+57) always expects 10 digit number after +57 and given number is 8 digit
Correct results returned from JavaScript version:
_Result from isPossibleNumber(): false
Result from isPossibleNumberWithReason(): TOO_SHORT
Note: Numbers that are not possible have type UNKNOWN, an unknown region, and are considered invalid._

##### Actual result
Returns valid number with numberType as fixedLine

### Environment
CocoaPods

**Comment by ngup4523** [comment]
@bguidolim @michaeldwilliams Cocoapods SDK(v3.7)  results not matching Javascript results

**Comment by ngup4523** [comment]
Can someone look into this? @bguidolim @michaeldwilliams

**Comment by michaeldwilliams** [comment]
@ngup4523 why did you tag me in this? I don't work on this project. Where did you see my name anywhere that made you tag me?

**Comment by bguidolim** [comment]
@ngup4523 I've just tested here and it's returning `invalidNumber`.

**Comment by ngup4523** [comment]
> @ngup4523 I've just tested here and it's returning `invalidNumber`.

You tested in Javascript version or Cocoapods env? @bguidolim

**Comment by bguidolim** [comment]
I've tested using the latest code and metadata of PNK.
