### ISSUE TITLE
Bug Value of optional type 'NSRegularExpression?' must be unwrapped

### ISSUE THREAD

**Issue by TCslapete** [marmelroy/PhoneNumberKit#729]
Hello,

Thanks for your lib, but last version contain an error which does not allow the project to be built.

### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [ ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

##### Actual result
Error :
Value of optional type 'NSRegularExpression?' must be unwrapped to refer to member 'firstMatch' of wrapped base type 'NSRegularExpression'
Chain the optional using '?' to access member 'firstMatch' only for non-'nil' base values
Force-unwrap using '!' to abort execution if the optional value contains 'nil'

![Capture](https://github.com/marmelroy/PhoneNumberKit/assets/153904794/60ed50f9-b4ed-4496-bd3c-b7ede74f0530)

### Environment
Build iOS project with Xcode 15.1 on iPhone 15 pro iOS 17.0.1 with Cocoapods PhoneNumberKit v3.7.6

**Comment by bguidolim** [comment]
Hey @TCslapete 

Some days ago someone open an issue with the same description, but turns out that the Swift version used was not 5.

Could you check which Swift version are you using?
