### ISSUE TITLE
Change PhoneNumberTextField access to open to allow overriding

### ISSUE THREAD

**Issue by byrneciaran** [marmelroy/PhoneNumberKit#73]
Good job on the Swift 3.0 release 💯 

I've come across an issue with the PhoneNumberTextField. I'm overriding this class to draw a custom border and am receiving the compilation error:

> Cannot inherit from non-open class 'PhoneNumberTextField' outside of its defining module

Is it possible to change the access level on the PhoneNumberTextField class to "open" from "public" to facilitate overriding it outside of the module ?

**Comment by marmelroy** [comment]
Thanks @byrneciaran. You're right, it should be open. I will do a big access control sweep this evening and will push a fix.

**Comment by marmelroy** [comment]
Fix pushed. I'll bundle a new release in a few days.
