### ISSUE TITLE
Some French numbers 0694* (French Guiana) are not considered as Valid

### ISSUE THREAD

**Issue by Black-riddle** [marmelroy/PhoneNumberKit#734]
The lib deliberately excludes 0694* numbers 
according to the metadata in the lib a 06 9* can only be followed by a 5, an 8 or a 9 to be valid.
However there are French numbers in French Guiana  with 0694*
Can this be fixed please.

**Comment by bguidolim** [comment]
Could you provide some phone numbers with the issue?

**Comment by Black-riddle** [comment]
@bguidolim This one for example 0694137600
