### ISSUE TITLE
Default region code is incorrect on real devices

### ISSUE THREAD

**Issue by steve-u-level** [marmelroy/PhoneNumberKit#736]
`PhoneNumberKit.defaultRegionCode` on real (non-Simulator) devices relies on `CTCarrier.isoCountryCode` which has been deprecated, and as of iOS 16.4, returns only static values, which are incorrect. See iOS 16.4 release notes: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-16_4-release-notes.

This behavior does not happen on Simulator because `Locale.current` is used instead.

**Comment by bguidolim** [comment]
Please, use the latest version. It was fixed months ago.

**Comment by steve-u-level** [comment]
Thanks! Closing this issue.
