### ISSUE TITLE
Importing PhoneNumberKit causes compile errors

### ISSUE THREAD

**Issue by cody1024d** [marmelroy/PhoneNumberKit#74]
This is the strangest thing.  THe only thing I can think of, is that there is a naming conflict, or something.  But I've searched the repo, and it doesn't look like that's the case.

I have a static method called create, to help with UIView initialization (I'm laying out all views through code).

``` swift
extension UIView : Creatable {
}

// can't use 'Self' in extension of NSObject, so have to use a protocol
public protocol Creatable {
    init()
}

public extension Creatable where Self: UIView {
    static func create(creatorFunc: ((Self)->Void)? = nil) -> Self {
        let retval = self.init()
        retval.translatesAutoresizingMaskIntoConstraints = false
        creatorFunc?(retval)
        return retval
    }
}
```

This is for ease of use, so that I can do something like

``` swift
let fakeView = UITextField.create {
...
}
```

However, when I import PhoneNumberKit, I'm getting compile-time errors saying that a UITextField no longer has a member 'create'.  I'm stumped.  When I remove the import line, it compiles correctly again.

**Comment by cody1024d** [comment]
I've narrowed it down to something within the PhoneTextField file.  I removed that file after importing PhoneNumberKit, and it works.  Obviously that is not a valid solution, but I'm trying to narrow down the culprit

**Comment by marmelroy** [comment]
Hmmm... I'm suspecting it's related to the access control of PhoneNumberTextField. I changed it from```public``` to ```open``` yesterday but haven't bundled it in a release yet. Could you please change it to open on your side and see if it fixes things?

**Comment by cody1024d** [comment]
@marmelroy  I'm actually using the 2.3 branch lol

**Comment by marmelroy** [comment]
We are not actively supporting the Swift 2.3 branch and it will soon be deprecated completely. Please move to the Swift 3.0 branch when you can.
