### ISSUE TITLE
PhoneNumberKit is not recognised phone number until it is completed 

### ISSUE THREAD

**Issue by huthe98** [marmelroy/PhoneNumberKit#740]
### New Issue Checklist

- [x ] Updated PhoneNumberKit to the latest version
- [x ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [ x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
let phoneNumberInfo =  try? phoneNumberKit.parse(text, ignoreType: false)
I want to the country flag once the text start matching any phone number

### Environment
SPM + iOS

**Comment by bguidolim** [comment]
I need more context to help here.
