### ISSUE TITLE
`No such file or directory: '~/DerivedData`

### ISSUE THREAD

**Issue by d-warfield** [marmelroy/PhoneNumberKit#743]
The following error occurs when running my app on an **actual phone** (not the simulator):

`No such file or directory: '~/DerivedData/apple-client-kjiouewknasoiuqwelk/Build/Products/Debug-iphoneos/PackageFrameworks/PhoneNumberKit-Dynamic.framework/PhoneNumberKit-Dynamic'`

It does, however, run fine on the simulator. Any ideas what's going on?

iPhone Model: iPhone 14 Pro Max
iOS Version: 17.3
Xcode Version: 15.2

**Comment by mfan0425** [comment]
Same issue with me

**Comment by mfan0425** [comment]
It looks like a version issue. It might have been resolved. I updated the package to the latest version (3.7.9) and the issue disappeared.

**Comment by ashoukr** [comment]
> Don't add the dynamic library.

This did not work.

**Comment by workhitesh** [comment]
Same issue with me too

**Comment by ashoukr** [comment]
Solution is to compile the project via command line.

**Comment by Mohamed-Khaterr** [comment]
> Solution is to compile the project via command line.

When I try to build project via command line I did get this error 

`The following build commands failed:
	Copy /Users/UserName/Documents/MyApp/MyApp/build/Release-iphoneos/MyApp.app/PhoneNumberKit_PhoneNumberKit.bundle /Users/UserName/Documents/MyApp/MyApp/build/Release-iphoneos/PhoneNumberKit_PhoneNumberKit.bundle (in target 'MyApp' from project 'MyApp')`

**Comment by ashoukr** [comment]
what I did exactly was remove the package, remove the derived data, reinstall the package, build via Xcode cli. 

> > Solution is to compile the project via command line.
> 
> When I try to build project via command line I did get this error
> 
> `The following build commands failed: Copy /Users/UserName/Documents/MyApp/MyApp/build/Release-iphoneos/MyApp.app/PhoneNumberKit_PhoneNumberKit.bundle /Users/UserName/Documents/MyApp/MyApp/build/Release-iphoneos/PhoneNumberKit_PhoneNumberKit.bundle (in target 'MyApp' from project 'MyApp')`

**Comment by iosdeviguru** [comment]
Follow this same steps and same version it will solve this issue on real device 

From Xcode 11+ :

Select File > Swift Packages > Add Package Dependency. Enter https://github.com/marmelroy/PhoneNumberKit.git in the "Choose Package Repository" dialog.
In the next page, specify the version resolving rule as "Up to Next Major" from "3.7.0".
After Xcode checked out the source and resolving the version, you can choose the "PhoneNumberKit" library and add it to your app target.

**Comment by Hello07Anas** [comment]
this work for me "Don't add the dynamic library."
