### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by niji-mathieu-viel** [marmelroy/PhoneNumberKit#745]
Third-party SDKs should include a privacy manifest by Spring according to Apple new requirements : 
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc

Would it be possible to add it to PhoneNumberKit?

Thanks.

**Comment by niji-mathieu-viel** [comment]
From what I understand, as the framework is not collecting any personal data, an empty manifest + podspec / package.swift setup should do the trick (?)

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
</dict>
</plist>
`

**Comment by bguidolim** [comment]
It seems that's the way to go.
