### ISSUE TITLE
Formatter.swift adding an extra 0 for Bangladesh numbers

### ISSUE THREAD

**Issue by mtheresep** [marmelroy/PhoneNumberKit#756]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
1. Utilizing [PhoneNumberKit.format](https://github.com/marmelroy/PhoneNumberKit/blob/master/PhoneNumberKit/PhoneNumberKit.swift#L68-L89) to output `.national` type phone numbers.
2. Choose the Bangladesh country picker option.
3. Type a Bangladesh phone number. (example: 721-123456)

##### Expected result
National result: 721-123456
##### Actual result
National result: **0**721-123456

### Environment

Utilizing this library for an app via Cocoapods. Recently had a Bangladeshi user report that they are not able to add their phone number because of the extra 0 being added.

**Comment by bguidolim** [comment]
Hi @mtheresep 

This is the expected result when formatting the number to national, it's defined in the metadata for this region.
