### ISSUE TITLE
Unable to parse czech numbers from string

### ISSUE THREAD

**Issue by eduard-cihunka** [marmelroy/PhoneNumberKit#759]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)

### Steps to reproduce
I'm trying to parse phone number from string `420777666555` with parse function `phoneNumberKit.parse(phoneNumber.fullPhoneNumber)` where phoneNumberKit is `private let phoneNumberKit = PhoneNumberKit()`. On Version `3.5.10` everything works fine, after update to newest version I'm not able to parse czech republic numbers from string. We need to update to newest version because of apple privacy manifest. From my observations function `func hasValue(_ value: String?) -> Bool` returns different values after update, so maybe the issue could be there. 

### Test examples

![Screenshot 2024-04-09 at 13 38 25](https://github.com/marmelroy/PhoneNumberKit/assets/62911587/0921feba-6748-4940-a6ec-f338baf3b3de)

For better understanding, format is our internal implementation, just maps our internal format to the library one, but fail occurs on the first line where `PhoneNumberKit` trying to parse number from string.

![Screenshot 2024-04-09 at 13 39 22](https://github.com/marmelroy/PhoneNumberKit/assets/62911587/0db4788b-b984-435b-84ed-724468564735)

##### Expected result
Parsed PhoneNumber struct

##### Actual result
Parsing fail and result is nil

### Environment
SPM

**Comment by bguidolim** [comment]
Hey @eduard-cihunka 

It's expected that you provided more information to PNK be able to parse and format phone numbers properly.

There are two ways to achieve this:
1. Sending the complete number, which in this case would be `+420777666555`
2. Sending the national number together with the region code, which is this case you would call the parse function like this: `phoneNumberKit.parse("777666555", withRegion: "CZ")`

Your issue though seems to be simple to fix, probably the property `fullPhoneNumber` of your model is a calculated property, so you can simply add a `+` at the beginning of the string and PNK will be able to do its job.

I hope it helps you.
