### ISSUE TITLE
[Swift 3] Subclass PhoneNumberTextField

### ISSUE THREAD

**Issue by jpstern** [marmelroy/PhoneNumberKit#76]
I see that PhoneNumberTextField is marked open, but the swift 3 compiler is complaining with the error:

Cannot inherit from non-open class 'PhoneNumberTextField' outside of its defining module'

Any ideas?

**Comment by marmelroy** [comment]
Thanks @jpstern. Very interesting... will investigate later this evening.

**Comment by andresgarza** [comment]
I'm also seeing this, but I noticed that the change to make it `open` landed after the latest release.

**Comment by jpstern** [comment]
Ah, good call.  If I pull down from master instead of the latest release it works as expected.
