### ISSUE TITLE
Not able to validate Phone Number for non-US region on 3.7.9 / 3.7/10

### ISSUE THREAD

**Issue by mithleshgomotive** [marmelroy/PhoneNumberKit#762]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [x] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

### Steps to reproduce

Basically I was using `PhoneNumberKit` version `3.3.4` and with this I also had unit-test written. Things were working fine. 
Few weeks back, I bumped the version of PhoneNumberKit library to `3.7.9` (or now `3.7.10`), the same UT was not working for non-US regions. 

UT's working or not working, is fine anyway. But I just noticed the region got changed as I'm working from India. The colleague working from US, for them this change doesn't matter and UT kept on working. 

The UT was failing for India, Poland basically non-US region. 

```
XCTAssertEqual(delegate.validate(phoneField, data: TextFieldComponentData(title: "", value: "123456789012")), .error(description: "Please use a valid phone number."))

/// Breaking down the above UT code:
/// Test PhoneNumber: 123456789012
/// It should fail ideally but it's passing. Hence above UT failed.
```

For one of my colleague in Poland region, the other set of UT started to fail (being region specific). 

I debugged and found that since we are not passing explicitly defaultRegion code to PhoneNumberKit, it's causing to fail because it's taking `user's current region - based on the iPhone's carrier and if not available, the device region.`

Screenshot for reference. 
- In `3.7.10`
- - We can see the region is IN since I'm in India
<img width="1271" alt="Screenshot 2024-04-19 at 4 09 57 PM" src="https://github.com/marmelroy/PhoneNumberKit/assets/154124052/4a5a55b4-1901-490c-a174-a968c5d61697">

------------------------------------------------------------

- In `3.3.4`
- We can see the region is US even I'm in India
<img width="1265" alt="Screenshot 2024-04-19 at 4 47 26 PM" src="https://github.com/marmelroy/PhoneNumberKit/assets/154124052/b9d9d064-4c6b-401d-a3fa-ef36869fb0a1">

The above one is not expected IMO.
I am raising this as an issue because the set of UT was working earlier and now with version bump it started to fail. 

**To fix this issue:**
- I just noticed PhoneNumberKit.isValidPhoneNumber(:_) expects (`region: String`).
- Default parameter is `PhoneNumberKit.defaultRegionCode()`
- I just passed explicitly my required region (i.e., US for this case) and it worked as expected.

Still I wanted to call this out because change in behaviour. Can you please check this and let us know why there is behavioural change here?

##### Expected result

```
XCTAssertEqual(delegate.validate(phoneField, data: TextFieldComponentData(title: "", value: "123456789012")), .error(description: "Please use a valid phone number."))
```
- This test was passing for version `3.3.4` and failing in `3.7.9` / `3.7.10` (India [`IN`] region)
- It should pass.

##### Actual result

- The same UT should work irrespective of version.

### Environment

- Cocoapods
- Mac
- Using XCode 15.3
- PhoneNumberKit Library version - `3.3.4`
- Country - India
  - Similar UT failure has happened for my colleague in Poland.

**Comment by bguidolim** [comment]
Hey @mithleshgomotive 

The main reason why it's working on version 3.3.4 is because it's using a deprecated way to get the default region for iOS 16 and 17 (maybe iOS 15 too), which means that it will always fallback to `US` as default region.

The recent releases relies on system's region if available. The region is needed in order to parse a phone number that doesn't contain the international code.

If you always have the international code, it will work independently of the region set, if the international code is not available, the library will use whatever is available to try to parse the phone number.

So, with that in mind, you need to update your unit tests to pass a region or the full phone number.

I hope it helps.
