### ISSUE TITLE
onPhoneNumberChangeHandler after entering 10digits we are getting value as nil for specific numbers only. can please look at it....

### ISSUE THREAD

**Issue by NelkiSujith** [marmelroy/PhoneNumberKit#766]
### New Issue Checklist

- [ ] Updated PhoneNumberKit to the latest version
- [ ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [ ] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [ ] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

**Comment by bguidolim** [comment]
Closing this due to lack of information
