### ISSUE TITLE
I need to format a "test" phone number to E164 but parse() throws

### ISSUE THREAD

**Issue by sorth-hiya** [marmelroy/PhoneNumberKit#77]
Great library but it fails to parse some phone numbers (e.g invalid area code, etc). For example, in the iOS simulator the sample Contact Kate Bell has the number (555) 564-8583.  I would like to be able to get the E164 format for this number, but parse fails. Could you please provide a way to bypass the area-code validation, so I can still format test phone numbers?

**Comment by Junus** [comment]
@sorth-hiya did you found solution for this?

**Comment by marmelroy** [comment]
With recent versions of PhoneNumberKit you can ignoreType on parse, for example:
``` swift
try phoneNumberKit.parse("+16307792428", ignoreType: true, withRegion: "US")
```

**Comment by varungoyal44** [comment]
I did some research into this number. 555 does not seem to be a valid area code.
