### ISSUE TITLE
Missing support for textContentType autocomplete with example placeholder + prefix enabled

### ISSUE THREAD

**Issue by johnfrancmartin** [marmelroy/PhoneNumberKit#775]
### New Issue Checklist

- [X] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [x] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

### Steps to reproduce
- Create an app with PhoneNumberTextField
- withPrefix = true
- withExamplePlaceholder = true
- Install on device where self-contact card has a phone number
- Run and select phone text field

##### Expected result
- Autocomplete displays with self-contact phone number

##### Actual result
- No autocomplete because the country code prefix is added on didBeginEditing, and iOS autocomplete for phones doesn't show except in empty text fields

### Environment
- SPM
- iOS 17.4

### Fix

Fix provided in #774

**Comment by johnfrancmartin** [comment]
@marmelroy just bumping this to the top if you get a chance

**Comment by bguidolim** [comment]
Fixed with #774
