### ISSUE TITLE
It's impossible to identify Mexican numbers with (1)

### ISSUE THREAD

**Issue by 2jumper3** [marmelroy/PhoneNumberKit#779]
Mexican numbers have an additional digit (1) in some cases. If such a number is provided to `parse`, it returns an "invalid Number" error.

### Steps to reproduce

Provide the Mexican number in international format in `phoneNumberKit.parse`. For example, +52 (1) 55 1111 1111.

##### Expected result

Expected parsedNumber: `PhoneNumber` type

##### Actual result

`invalidNumber` Error

### Environment
SPM 3.7.10

**Comment by bguidolim** [comment]
Hey @2jumper3

I've created the bug template for new issues here exactly to avoid this kind of issues.
This is about metadata, it should be updated at the [libphonenumber](https://github.com/google/libphonenumber) repo.

The bug template contains a link where you can check if the phone number is valid or not using the original library.

The rule of thumb is: the original lib and PhoneNumberKit should have the same response.

**Comment by 2jumper3** [comment]
@bguidolim Hi and many thanks for your answer. 
Did I understand you correctly that this issue needs to be addressed to the Google library, not here?

**Comment by bguidolim** [comment]
That's right.
