### ISSUE TITLE
make it as extension

### ISSUE THREAD

**Issue by StevenArmandLee** [marmelroy/PhoneNumberKit#78]
I'm wondering if you can make this as extension of textfield so that we can easily use another textfield open source for our project?

for example SkyFloatingLabelTextField. so that it is more flexible.

thanks.

**Comment by marmelroy** [comment]
I see the benefit in making PhoneNumberTextField an extension but can't think of a way to do this currently - it's just a bit too complex to be an extension. 

I will close this issue for now...

**Comment by StevenArmandLee** [comment]
I see. Do you have any kind of solution for my problem? As i want implementation SkyFloatingLabelTextField

**Comment by marmelroy** [comment]
I would probably suggest creating either a PhoneNumberTextField that inherits from SkyFloatingLabelTextField or the other way around.
