### ISSUE TITLE
Please review Austria phone number sample for ios

### ISSUE THREAD

**Issue by karapetyangevorg** [marmelroy/PhoneNumberKit#782]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [ ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [ ] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

### Steps to reproduce

let phoneNumber = self.phoneNumberKit.getExampleNumber(forCountry: "AT") = 

##### Expected result

In phoneNumber numberString is "664123456".

##### Actual result

In phoneNumber numberString is "664123456". should be "6641234567"

 Austria phone phone number length is 11

### Environment

iOS

**Comment by bguidolim** [comment]
This is defined by [libphonenumber repo](https://github.com/google/libphonenumber)
