### ISSUE TITLE
Build Error with Xcode 16 Beta 5 - ParseManager: Mutable capture of 'inout' parameter 'buffer' is not allowed in concurrently-executing code

### ISSUE THREAD

**Issue by schlagelk** [marmelroy/PhoneNumberKit#790]
### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [x] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

### Steps to reproduce

Download the latest Xcode 16 beta 5, build the project. You'll see this error
<img width="609" alt="Screenshot 2024-08-06 at 3 42 46 PM" src="https://github.com/user-attachments/assets/55f63d44-cbb3-455c-b88f-83b43a279d85">

##### Expected result

Project compiles

##### Actual result

Project doesn't compile

### Environment

Xcode on main branch

**Comment by shanecowherd** [comment]
This let me compile, not sure if it fixes it, but I just needed to get the app compiling for today:

```swift
func parseMultiple(_ numberStrings: [String], withRegion region: String, ignoreType: Bool, shouldReturnFailedEmptyNumbers: Bool = false) -> [PhoneNumber] {
    var hasError = false
    var results = [PhoneNumber](repeating: PhoneNumber.notPhoneNumber(), count: numberStrings.count) // Temporary array

    DispatchQueue.concurrentPerform(iterations: numberStrings.count) { index in
        let numberString = numberStrings[index]
        do {
            let phoneNumber = try self.parse(numberString, withRegion: region, ignoreType: ignoreType)
            results[index] = phoneNumber // Update the results array
        } catch {
            results[index] = PhoneNumber.notPhoneNumber() // Update the results array
            hasError = true
        }
    }

    if hasError && !shouldReturnFailedEmptyNumbers {
        results = results.filter { $0.type != .notParsed }
    }

    return results
}
```

**Comment by srigginsatebay** [comment]
We have run into the same issue. We localize packages, so I'll apply the patch for now. Thanks!

**Comment by SynthesOne** [comment]
I have also encountered this bug, would appreciate it being fixed in the new version
