### ISSUE TITLE
Won't build for Swift 6

### ISSUE THREAD

**Issue by jcbriones** [marmelroy/PhoneNumberKit#793]
Using Xcode 16 and Swift 6 throws a compile time error: concurrent perform isn't thread safe from what I remember the error was.

```swift
DispatchQueue.concurrentPerform(iterations: numberStrings.count) { index in
    let numberString = numberStrings[index]
    do {
        let phoneNumber = try self.parse(numberString, withRegion: region, ignoreType: ignoreType)
        buffer.baseAddress!.advanced(by: index).initialize(to: phoneNumber)
    } catch {
        buffer.baseAddress!.advanced(by: index).initialize(to: PhoneNumber.notPhoneNumber())
        hasError = true
    }
}
```

### New Issue Checklist

- [x] Updated PhoneNumberKit to the latest version
- [x] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [x] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [x] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

### Steps to reproduce
Download Xcode 16 beta 5 and run the plugin.

##### Expected result
No compile time errors

##### Actual result
Giving a compile time error

### Environment
macOS 15.1, iOS 18.0 simulator, swift 6.

**Comment by bguidolim** [comment]
Hey @jcbriones 

Please, don't get me wrong, but the `New Issue Checklist` exists for a reason.

[x] Updated PhoneNumberKit to the latest version = https://github.com/marmelroy/PhoneNumberKit/releases/tag/3.8.0
[x] I searched for existing GitHub issues = https://github.com/marmelroy/PhoneNumberKit/issues/790 and https://github.com/marmelroy/PhoneNumberKit/pull/791

Check the latest version and let me know if you are still facing the issue.
