### ISSUE TITLE
PNK fails to identify an improper number 

### ISSUE THREAD

**Issue by j-pk** [marmelroy/PhoneNumberKit#8]
I made a simple textfield to test various phone number inputs. 

This # entry ```202 00e 0000``` returns with a ```PremiumRate``` type and the ```toE164``` string value is ```+1202003000```

It does appear to be taking the alphabetical keypad entry you find on a phone and converting its value. So, would this be a valid entry or should an error return stating it's not a number? 

 Anyways, just thought I share my findings.

**Comment by marmelroy** [comment]
Ah yes... good find. Looks like I didn't throw an error at the right place. Fix very soon.

**Comment by marmelroy** [comment]
Fixed with 0.1.6. Thanks again @j-pk

**Comment by marmelroy** [comment]
Also added an automatic test to make sure this issue doesn't come back.
