### ISSUE TITLE
Gambia [GM] +220

### ISSUE THREAD

**Issue by mhmdBarek** [marmelroy/PhoneNumberKit#811]
issues with gambia phone number validation:
### Steps to reproduce
try to validate any phone number that start with prefix 8, it should return false however all of them are returning true. for example: +220 8324432 

another case: 4121212 should return true however its returning false.

##### Expected result

for any prefix that starts with 8: expected result is false
for 4121212: expected result is true

##### Actual result
for any prefix that starts with 8: it is returning true
for 4121212: it is returning false

### Environment
 using cocoapods

**Comment by bguidolim** [comment]
Please follow the bug report checklist.
