### ISSUE TITLE
Gambia [GM +220] phone number validation

### ISSUE THREAD

**Issue by mhmdBarek** [marmelroy/PhoneNumberKit#812]
**Steps to reproduce**
When we try validate the phone number with public func isValidPhoneNumber(_ numberString: String, withRegion region: String = defaultRegionCode(), ignoreType: Bool = false) -> Bool method of the library. It returns true for these phone numbers: +220 8324432  or any number with 8 prefix.
**Expected result**
Library should return false for these inputs, for any number that starts with 8.
**Environment**
Library version: 4.0.0

**Comment by bguidolim** [comment]
### New Issue Checklist

- [ ] Updated PhoneNumberKit to the latest version
- [ ] Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
- [ ] I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
- [ ] I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

**Comment by mhmdBarek** [comment]
> ### Issue Checklist
> * [x]  Updated PhoneNumberKit to the latest version
> * [x]  Phone number formatted correctly on [JavaScript version](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)
> * [x]  I searched for [existing GitHub issues](https://github.com/marmelroy/PhoneNumberKit)
> * [x]  I am aware that this library is not responsible of adding/removing/changing phone number formats and any request should be done at [libphonenumber repo](https://github.com/google/libphonenumber)

**Comment by bguidolim** [comment]
If you followed the checklist, you already know that the library is behaving correctly.
