### ISSUE TITLE
Unrecognized selector crash in PhoneNumberTextField

### ISSUE THREAD

**Issue by jrogers** [marmelroy/PhoneNumberKit#82]
Getting this crash on line 175 in TextField.swift in my app, happens with both 4.0.7 and latest master:

> 2016-10-26 17:33:30.128587 App[535:69350] -[App.LoginViewController textField:shouldChangeCharactersInRange:replacementString:]: unrecognized selector sent to instance 0x10383aa30
> 2016-10-26 17:33:30.129487 App[535:69350] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[App.LoginViewController textField:shouldChangeCharactersInRange:replacementString:]: unrecognized selector sent to instance 0x10383aa30'

```
        guard _delegate?.textField!(textField, shouldChangeCharactersIn: range, replacementString: string) ?? true else {
            return false
        }
```

If I change it to check textField(), it works:

```
        guard _delegate?.textField?(textField, shouldChangeCharactersIn: range, replacementString: string) ?? true else {
            return false
        }
```

Not really sure what the root cause is as it looks like the delegate should be referencing PhoneNumberTextField as the UITextFieldDelegate, but this was a recent change and the code looked like the change I made before efb636bf.

This is with Xcode 8.1 GM, on iOS 10.1 device.

**Comment by cody1024d** [comment]
I'm having the same issue
