### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by dmytro-fido** [marmelroy/PhoneNumberKit#823]
Sorry for doing it though creating an issue on your project, but I haven't found any contacts to reach you somehow.
Our app requires you lib to be updated to 8.13.52 metadata, since it has changes to the phone numbers format our users have.
Is it possible somehow to trigger release now?

**Comment by bguidolim** [comment]
Hi! I will do it soon.
But if you really need this now, you can also use the `master` branch.
