### ISSUE TITLE
Customize Phone Region

### ISSUE THREAD

**Issue by gracietti** [marmelroy/PhoneNumberKit#86]
As I'm using, `phoneTextField.defaultRegion = "BR"`, the user is supposed to type numbers on the format 01 2345-6789, but some Brazilian phones have an extra number (01 23456-7899).

I'm wondering if it's possible to customize "BR" region to accept both types of format above.

**Comment by marmelroy** [comment]
Hi @gracietti, thanks for this.

PhoneNumberKit is using the metadata from Google's libPhoneNumber library. The metadata is updated regularly and is used across the web. It's up to Google to decide what kind of number formats to support...
