### ISSUE TITLE
[HELP NEEDED] How do I preset values for PhoneNumberTextField?

### ISSUE THREAD

**Issue by nuynait** [marmelroy/PhoneNumberKit#88]
I have a setting view, inside setting, there is a phone number field for user to fill out. So I am using the PhoneNumberTextField for that. 

For user who already have the phone number in their profile, I have to display that first and when user clicked, they can edit it.

How do I display? I tried with the text property inside PhoneNumberTextField, but that looks really ugly and when typing it just overlay on that. So I guess that is not the correct way for me to do it.

Really appreciate your help here. Thanks so much for the time.

**Comment by marmelroy** [comment]
Hi @nuynait, sorry for the delay... 

You should parse and format the preset value using PhoneNumberKit's parse and format functions. You can then set it with the text property. 

Hope this helps...
