### ISSUE TITLE
Does not compile with Xcode 8.1

### ISSUE THREAD

**Issue by alex314** [marmelroy/PhoneNumberKit#89]
I cannot get PhoneNumberKit integrated neither using CocoaPods, nor with Carthage:

With CocoaPods Xcode complains the PhoneNumberKit needs to be converted to newest Swift 3 syntax, obviously I cannot let it do the conversion because source files of the framework are locked. Until I do the conversion the compiler generates tons of errors and warnigns.

With Carthage compilation works fine, but it seems like most of the public header files are missing from compiled framework - the PhoneNumberKit is the only public class there with very few available methods, even -parse method is missing, so example code doesn't compile.

**Comment by rwichmann** [comment]
Same here!

**Comment by marmelroy** [comment]
Thanks @alex314 and @rwichmann. I will investigate and fix soon...

**Comment by marmelroy** [comment]
This should be fixed by the newest release (works on my side). Please make sure you are running the latest versions of Cocoapods and Carthage.

**Comment by ibrahimchiha** [comment]
Not compiling on Xcode 9
