### ISSUE TITLE
Add a FixedLineOrMobile type

### ISSUE THREAD

**Issue by lobodin** [marmelroy/PhoneNumberKit#9]
Hi,

I am parsing this number +16307792428 and get the type FixedLine when in fact it is a Mobile number.

Google's libphonenumber would return FIXED_LINE_OR_MOBILE.

I am not sure there is a 100% way to detect if it is a mobile or fixed number in this case. Perhaps returning FixedLineOrMobile would be a better option?

**Comment by marmelroy** [comment]
PhoneNumberKit uses the same metadata as Google's libPhoneNumber so we can't get a better result than FixedLineOrMobile.  

Currently we don't have a FixedLineOrMobile type (I considered it but thought it was too ambiguous when writing that function). Maybe I should add it back.

**Comment by marmelroy** [comment]
Just added a FixedOrMobile type (applied with the same rules as libPhoneNumber) and included the number you mentioned as a test. This is bundled in release 0.1.7. Thanks again for the issue.
