### ISSUE TITLE
PhoneNumberKit still parses type with ignoreType set to true

### ISSUE THREAD

**Issue by sgapr** [marmelroy/PhoneNumberKit#92]
I am getting around 12-15s in doing 686 parses in serial using the following code. Replacing it with libPhoneNumber-iOS, i get around 3s for the same. Is this a regression ? 

```swift
class func normalizedString(phoneNumber: CNPhoneNumber, region: String) -> String? {
       do {
            let phoneNumber = try PhoneNumberUtils.sPhoneNumberKit.parse(phoneNumber.stringValue, withRegion: region)
            return PhoneNumberUtils.sPhoneNumberKit.format(phoneNumber, toType: .e164)
        } catch {
            return nil
        }
}
```

**Comment by marmelroy** [comment]
We now do hard type validation by default and libPhoneNumber-iOS doesn't. This way, we guarantee that the number is 100% valid. 

If you don't care whether or not a number is valid, you can add ignoreType:true to your parse function. E.g.
```swift
 phoneNumberKit.parse("+16307792428", ignoreType: true, withRegion: "US")
```

**Comment by sgapr** [comment]
Still the same. Looking inside the parse code, ignoreType does not seem to cut down any code. Below is the only usage of ignoreType

```swift
   let type = parser.checkNumberType(String(nationalNumber), metadata: regionMetadata, leadingZero: leadingZero)
        if type == .unknown && !ignoreType {
            throw PhoneNumberError.unknownType
        }
```

**Comment by marmelroy** [comment]
You're right, this needs to be fixed

**Comment by marmelroy** [comment]
Should be fixed with release 1.0.4. Thanks again. 

Let me know if it's still slow.

**Comment by sgapr** [comment]
Hi, this is still slow (11 seconds instead of 12-15seconds for 686 parses).
I fired up instruments and most of the time is in `getRegionCode`. I think that line can also be removed if `ignoreType == false`, in the code below

```swift
       if let regionCode = getRegionCode(of: finalNationalNumber, countryCode: countryCode, leadingZero: leadingZero), let foundMetadata = metadataManager.territoriesByCountry[regionCode] {
            regionMetadata = foundMetadata
        }
        var type: PhoneNumberType = .unknown
        if ignoreType == false {
            type = parser.checkNumberType(String(nationalNumber), metadata: regionMetadata, leadingZero: leadingZero)
            if type == .unknown {
                throw PhoneNumberError.unknownType
            }
        }
```

**Comment by sgapr** [comment]
and perhaps, make `getRegionCode` faster by fixing the following line, as you have done in other places. instruments shows that line as the culprit.

```swift
let regions = metadataManager.territories.filter { $0.countryCode == countryCode }
```

**Comment by marmelroy** [comment]
Thanks again @sgapr. Solid suggestions. I'll review tonight.

**Comment by marmelroy** [comment]
Removed .filter calls and performance seems much better. Also, I should point out some additional issues that can affect performance:

- A PhoneNumberKit instance is relatively expensive to allocate (it parses the metadata and keeps it in memory for the object's lifecycle). I can't see the rest of your code but you should try and make sure sPhoneNumberKit is allocated once and deallocated when no longer needed.   

- You should also note that PhoneNumberKit has a special function for parsing multiple numbers that has some performance benefits:
```swift
let rawNumberArray = ["0291 12345678", "+49 291 12345678", "04134 1234", "09123 12345"]
let phoneNumbers = phoneNumberKit.parse(rawNumberArray)
let phoneNumbersCustomDefaultRegion = phoneNumberKit.parse(rawNumberArray, withRegion: "DE",  ignoreType: true)
```

**Comment by sgapr** [comment]
Thanks @marmelroy , performance is good now 👍
