### ISSUE TITLE
Examples don't work.

### ISSUE THREAD

**Issue by dasoga** [marmelroy/PhoneNumberKit#93]
Hi!

I want to test it, but the examples don't run. I tried in Xcode 7.3.1 and Xcode 8.1.

Thanks you!

**Comment by marmelroy** [comment]
Hi @dasoga,

The examples are tested with every build on Travis so can confirm they work. 

Both apps rely on Cocoapods. Please make sure you follow these steps:
- Clone the whole project. 
- Have the latest version of cocoapods installed.
- Run a pod update in the root folder of the example app you want to try. 

Let me know if you still run into any issues...

**Comment by dasoga** [comment]
After the steps. I had to update settings to legacy swift version.
I did this in Xcode 8.1

Thank you!

![screen shot 2016-12-05 at 11 33 53 am](https://cloud.githubusercontent.com/assets/11412369/20895467/2f76c8c8-badf-11e6-9257-a2f5875e458a.png)

**Comment by marmelroy** [comment]
Hmm...

**Comment by marmelroy** [comment]
Can you confirm the version of cocoapods you are running?

**Comment by dasoga** [comment]
Is 1.0.1
I thought that I was updated to 1.1.0.

But is working now after update legacy swift version to the library.
