### ISSUE TITLE
Does not compile in Xcode 8.2

### ISSUE THREAD

**Issue by mrubin** [marmelroy/PhoneNumberKit#94]
PhoneNumberKit does not compile under Xcode 8.2 (I tried version 1.0.3 and 1.1.1). The project file has `SWIFT_VERSION` set to `3.0.1`. Can we please manually change it to `3.0` as a workaround?

**Comment by mrubin** [comment]
I see that you did this in 2ce9e2a8de4766264f67f6f4ea359f4cae61fbf4. Thank you very much!

**Comment by marmelroy** [comment]
Yeah, thanks a lot @mrubin.
