### ISSUE TITLE
how can we change the international code/ area code colour change?

### ISSUE THREAD

**Issue by sreeji44** [marmelroy/PhoneNumberKit#97]
Its not an issue it just a request how we can add colour to only international/ area code. when we add that we can easily identify. is their any way to do it. please share thanks. :)

**Comment by marmelroy** [comment]
Hi @sreeji44 , I'm not sure I understand the question. Can you please clarify what kind of colour change you are after?

**Comment by marmelroy** [comment]
Closing for lack of information..

**Comment by sreeji44** [comment]
For Example +1 (545) 635-2544 here i need to change the international country code +1. because the user cannot know easily. i think you get my question.
