### ISSUE TITLE
Parenthesis in national number

### ISSUE THREAD

**Issue by jazzgil** [marmelroy/PhoneNumberKit#99]
Hi, Thanks for the excellent work on this library!

I've created a separate country picker and a PhoneNumberTextField for entering the national part. However when typing the number, the text field automatically adds parens to the first 3 digits. When I'm using phoneNumberKit.format(), I can set the toType to .international, and withPrefix none, which shows the national number correctly without parens (uses MetadataPhoneNumberFormat.intlFormat), but I've found no such option for PhoneNumberTextField. I've tried withPrefix false, but can't see the difference.

Is there a way to apply this format on PhoneNumberTextField as well?

Appreciate your support.
Gilad

**Comment by marmelroy** [comment]
Hi Gilad,

Sorry for the delay with this. There's no current way to get that format with PhoneNumberTextField (and we don't have the regular expressions that will allow us to support it).
